### ISSUE TITLE
Shadow Satyr's Walk extra energy refund

### ISSUE THREAD

**Issue by aethys256** [SimCMinMax/WoW-BugTracker#1]
**Game Version:**
> 7.3.5 Live Build 25961

**Description:**
> SSW's effect ignores the target hitbox, giving more energy refund.

**Reproduce rate:**
> 100%

**Details:**
> Considering it takes the raw distance (center of the target - center of the player) for the effect computation, you can get 3 + 3 energy (if the hitbox is standard, even more if the mob is bigger) instead of 1 + 3 energy (with the current max range being ~5y for melees).

[Example log](https://www.warcraftlogs.com/reports/dqYpVAPGWaHDxLF2#fight=3&type=resources&source=8&spell=103&view=events)

![image](https://user-images.githubusercontent.com/10969743/36011257-47d51dd2-0d56-11e8-9ad5-9b297248f215.png)

**Howto:**
> Try to be as much as possible close to max range to increase the effect.

**Comment by Aethys256** [comment]
Initially discovered in 7.0, publicly talked about it since ~7.1.5.
Will likely be not fixed, the item will no longer exists in few months.

**Comment by Mystler** [comment]
Closing because ooold.
