### ISSUE TITLE
Dispatch/Crimson Tempest are not modified by Vendetta/Elaborate Planning/Deeper Stratagem % modifiers

### ISSUE THREAD

**Issue by Kiwifruity** [SimCMinMax/WoW-BugTracker#102]
**Game Version:**
> 8.0.1 Alpha Build 25976

**Description:**
> Vendetta's 30% increased damage modifier does not apply to dispatch or Crimson Tempest. Crimson Tempest is also not modified by Elaborate Planning.

**Reproducible:**
> 100%

**Howto:**
> Dispatch a target, use vendetta, dispatch again, compare damage
>Crimson Tempest a target with and without vendetta/Elaborate planning, observe damage

**Comment by Mystler** [comment]
Fixed in 8.0.1.26095.
