### ISSUE TITLE
Crimson Tempest does not proc Elaborate Planning

### ISSUE THREAD

**Issue by Kiwifruity** [SimCMinMax/WoW-BugTracker#103]
**Game Version:**
> 8.0.1 Alpha Build 25976

**Description:**
> Elaborate planning is supposed to proc when a finisher is used, but does not proc when crimson tempest is used

**Reproducible:**
> 100%

**Howto:**
> Talent elaborate planning, use crimson tempest

**Comment by Zarania** [comment]
Duplicate of #75
