### ISSUE TITLE
Crimson Tempest only consumes up to 5 combo points when using Deeper Stratagem

### ISSUE THREAD

**Issue by Kiwifruity** [SimCMinMax/WoW-BugTracker#106]
**Game Version:**
> 8.0.1 Alpha Build 25976

**Description:**
> When using deeper Stratagem, Crimson Tempest will only consume 5 combo points when the player has 6 active combo points. However, the damage of crimson tempest is scaled up to what it should be if 6 combo points were consumed.

**Reproducible:**
> 100%

**Howto:**
> Talent Deeper Strat, generate 6 combo points and use Crimson Tempest. Crimson tempest will only consume 5 combo points

**Comment by Mystler** [comment]
Fixed in 8.0.1.26095.
