### ISSUE TITLE
Shadow Word: Pain Ignoring Void Bolt extension

### ISSUE THREAD

**Issue by lgkern** [SimCMinMax/WoW-BugTracker#107]
**Game Version:**
> 8.0.1 Alpha Build 25976

**Description:**
> Shadow Word: Pain is dropping before its duration is over when you extend its duration with Void Bolt. It occurs only when said debuff has been extended by Void Bolt, otherwise, it behaves normally.

**Reproducible:**
> Yes

**Howto:**
> Apply Shadow Word: Pain to a target and enter Voidform. Then hit it with Void Bolt (extending its duration). Note that the debuff will disappear before its duration is over.

**Comment by lgkern** [comment]
Video demonstrating the bug: https://www.youtube.com/watch?v=5YIwCrwe6UA

**Comment by N1gh7h4wk** [comment]
This is also affecting Vampiric Touch, just that the dot stays on the target, but stops dealing damage

**Comment by lgkern** [comment]
Fixed as of last build.
