### ISSUE TITLE
Nether Tempest goes to the wrong target if mobs are stacked

### ISSUE THREAD

**Issue by Vardex** [SimCMinMax/WoW-BugTracker#1071]
**Game Version:**
10.0.2 live Build 46702

**Description:**
Nether Tempest sometimes goes to another mob than your currently targeted one.

**Details:**
If two mobs are stacked on each other, using Nether Tempest will apply to the other mob rather than your target.

**Reproducible:**
Yes, but can be a bit hard with only two mobs, using a lot of mobs make it super easy to reproduce as your target is more likely to be stacked on another mob.

**Howto:**

1. Manage to physically stack two mobs
2. Cast Nether Tempest
3. Nether Tempest should go on the other mob rather than your target

**Comment by ArcanePorom** [comment]
Fixed today, https://worldofwarcraft.com/en-us/news/23885941/hotfixes-december-16-2022 confirmed to work as intended now.
