### ISSUE TITLE
Unholy's Army ghouls' (both from army of the dead and Apocalypse) energy regen double dips on haste

### ISSUE THREAD

**Issue by Melekus** [SimCMinMax/WoW-BugTracker#108]
**Game Version:**
> 7.3.5 Build 25996

**Description:**
> The Unholy pet ghoul and its empowered version Sludge Belcher both have a higher than expected energy regeneration rate.

**Details:**
I compared the number of Claw/Cleaver (the pet's energy spender) casts over a minute at different amounts of haste without casting anything. The results didn't match the usual pet energy regen model of 10 energy/s * (1+haste%) at normal amounts of haste, but were right at 0% haste. My first guess was that it was haste double dipping on the energy regen and the results seem to indeed follow that model.
Results here : https://docs.google.com/spreadsheets/d/1LPLsmhCU7WUX9X8mSlO_4CxEyWYQyQ__BQST01EvvVU/edit?usp=sharing
I tested it on BfA Alpha 8.0.1 build 25976 and saw the same results.

**Reproducible:**
> Yes

**Howto:**
> Compare the number of Claw/Cleaver casts in a given timeframe at different amounts of haste.

**Comment by Melekus** [comment]
This seem to also affect the ghouls summoned by Army of the Dead and Apocalypse.
The spreadsheet was updated.

**Comment by BanterDK** [comment]
This seems to be fixed in BfA-b26095. However, testing was done using a stopwatch since WClogs is down atm. Will retest/post an update shortly

**Comment by BanterDK** [comment]
Couple months late (lol), but eventually got around to fully testing this. This combined with the stopwatch test months ago lead me to believe this is fixed
[Log ](https://www.warcraftlogs.com/reports/XPxm4hq1avYHzy2B#fight=last&source=4&type=damage-done&view=events)+ [Spreadsheet dissection](https://docs.google.com/spreadsheets/d/1KZnJr7Qpemwf_05BaLXLxKVwOceOSWTdKdovQYP81YE/edit#gid=1865102929)

**Comment by Melekus** [comment]
The bug seems to still be around at least for Army of the Dead.
Considering the log provided by @BanterDK is in blood spec and that the spreadsheet doesn't really show anything by itself (or it's not clear enough? I would've shown the total Energy spent vs Energy available with and without double dip over the whole fight duration), there is no evidence that the bug was ever fixed.

**Comment by Chewsdaydk** [comment]
results from 8.1.5 - https://docs.google.com/spreadsheets/d/1D-45Gry0s0UA0zsYtiH8li5MVEj4mMBskW13UREh4b0/edit#gid=0

**Comment by Melekus** [comment]
Fixed on 8.2 PTR.
