### ISSUE TITLE
Deadly Duo stacks do not increase Kill Command damage.

### ISSUE THREAD

**Issue by Thyminde** [SimCMinMax/WoW-BugTracker#1082]
**Game Version:**
10.0.2 live Build 47213

**Description:**
Kill Command damage is not increased by any amount of Deadly Duo stacks, which was a new effect it was meant to receive when it was reworked Nov 15. 

**Details:**
The description reads: "Mongoose Bite increases the damage of your next Kill Command by 40% and reset chance of your next Kill Command by 25%, Stacking up to 3 times."

- Mongoose bite correctly applies deadly duo stacks to the player.
- Kill Command correctly consumes deadly duo stacks
- By consuming deadly duo stacks, the reset chance of Kill Command is correctly increased.
- However, Kill Command damage is entirely unaffected by deadly duo stacks.

Theories of the cause:
- Deadly duo applies to _259489_ which is the player casted spell, the kc talent itself. but not the pet spell which ends up dealing the damage, which i believe should be _259277_.

**Log snippet:**

```
16:58:15> Your Mongoose Fury stacked You 5.  
16:58:17> Your Mongoose Bite hit Dungeoneer's Training Dummy 44,320 Physical.  
16:58:17> Your Deadly Duo stacked You 3.  
16:58:18> Your Deadly Duo refreshed You.  
16:58:18> Your Deadly Duo faded You.  
16:58:18> Chickenwings Kill Command hit Dungeoneer's Training Dummy 15,291 Physical.  
> 15291 damage upon consuming 3 Deadly Duo stacks.

16:58:18> Your Flanker's Advantage applied You.  
> Flanker's Advantage is expected, because 3 stacks of deadly duo result in a 105% proc rate.

16:58:20> Your Tip of the Spear stacked You 2.  
16:58:20> Chickenwings Kill Command hit Dungeoneer's Training Dummy 15,291 Physical.  
> 15291 damage without consuming any Deadly Duo stacks.

16:58:20> Your Flanker's Advantage faded You.  
16:58:21> Your Spearhead faded You.
```

**Reproducible:**
yes, consistently

**Howto:**
- Talent into Deadly Duo as a survival hunter.
- Use Spearhead.
- Use Kill Command and take note of its damage.
- Use Raptor Strike / Mongoose bite 1-3 times to build up 1-3 Deadly duo stacks.
- Use Kill Command, it should be equal to the previous Kill Command damage accounting for crits.

**Comment by Pewtro** [comment]
Fixed in 10.0.5 47936
