### ISSUE TITLE
Exsanguinate does not function with Crimson Tempest

### ISSUE THREAD

**Issue by Zarania** [SimCMinMax/WoW-BugTracker#109]
**Game Version:**
> 8.0.1 Alpha Build 25976

**Description:**
1. You cannot cast Exsanguinate on a target that only has the Crimson Tempest bleed.

2. Exsanguinate does not speed up the Crimson Tempest bleed

**Reproducible:**
> 100%

**Howto:**
1. Cast Crimson Tempest then Exsanguinate on a target without Rupture or Garrote.  It does not let you.  
2. Cast Crimson Tempest on a target that has Garrote or Rupture then cast Exsanguinate.  The Crimson Tempest dot goes for the full 12 seconds

**Comment by Mystler** [comment]
Fixed in 8.0.1.26095.
