### ISSUE TITLE
Idol of Y'Shaarj does not Soothe Enrages

### ISSUE THREAD

**Issue by seanpeters86** [SimCMinMax/WoW-BugTracker#1091]
**Game Version:**
10.0.5 live Build 48069

**Description:**
Part of Idol of Y'Shaarj is that it should soothe enrages on a mob that has a dispelable enrage. This currently does not work.

**Logs, Images, Videos**
TBD

**Reproducible:**
yes

**Howto:**
1. Find a mob that has an enrage
2. Cast Mindbender on it with Idol of Y'Shaarj talented and notice it is not removed

**Comment by QualityVan** [comment]
I've definitely had this issue but the purge does work properly sometimes. Testing it on the time-lost chieftains and devilsaurs at the shifting sands in thaldraszus and it always removes enrage correctly on MB cast.
