### ISSUE TITLE
Master Assassin buff persists after swapping talents

### ISSUE THREAD

**Issue by Kiwifruity** [SimCMinMax/WoW-BugTracker#110]
**Game Version:**
> 8.0.1 Alpha Build 25976

**Description:**
> If you talent Master Assassin, stealth, and then swap Master Assassin to Nightstalker or Subterfuge, the Master Assassin buff remains active.

**Reproducible:**
> 100%

**Howto:**
> Select Master Assassin talent. Use stealth. Swap talent to nightstalker or subterfuge, master assassin buff will remain active.

**Comment by Mystler** [comment]
Fixed in 8.0.1.26095.
As a note, if you switch back to Master Assassin while in stealth, it takes a short moment for the buff to be applied. This is not a big deal though and I think we can consider the issue fixed.
