### ISSUE TITLE
Using Scatter Shot or Harpoon with the Terms of Engagement Talent on any target will trigger the "Mettle" buff from "Infurious Boots of Reprieve", whether it crowd controls the target or not.

### ISSUE THREAD

**Issue by Tralololo** [SimCMinMax/WoW-BugTracker#1106]
**Game Version:**
> 10.0.1 PTR Build 49365

**Description:**
> Using Scatter Shot or Harpoon with the Terms of Engagement Talent on any target with trigger the "Mettle" buff from "Infurious Boots of Reprieve", despite the effect requiring a "successful application" of a loss of control effect.

**Logs, Images, Videos**
![image](https://user-images.githubusercontent.com/115265727/235363423-ab99a45a-69e3-4e4d-8f88-ba2af73e9f8c.png)

Image showing me using Scatter Shot on a target dummy and receiving the "Mettle" buff, despite the fact Target Dummys cant be Crowd Controlled

**Reproducible:**
> Yes

**Howto:**
> Equip Infurious Boots of Reprieve, Select the Scatter Shot Talent or the "Harpoon" and "Terms of Engagement" Talents. Use Scatter Shot on a target that is immune to Crowd Control (such as a target dummy or a dungeon boss). Note the fact that you receive the primary stat buff "Mettle" from the boots, despite the target not having been successfully crowd controlled. This will not work if you have only Harpoon but not Terms of Engagement.

**Comment by Pewtro** [comment]
These crafted boots will be irrelevant come The War Within.
