### ISSUE TITLE
Bloody Frenzy does not activate Beast Cleave until you've cast a Cobra Shot.

### ISSUE THREAD

**Issue by Tralololo** [SimCMinMax/WoW-BugTracker#1131]
**Game Version:**
> 10.2.0 PTR Build 51239

**Description:**
> Bloody Frenzy is a talent which is supposed to make your pets gain Beast Cleave for the Duration of Call of the Wild. This effect will currently not apply unless you cast a Cobra Shot, an ability we normally wouldn't press during Call of the Wild, especially during AoE. It activates from Serpent Sting

**Logs, Images, Videos**
>https://www.warcraftlogs.com/reports/6CM2JPbgYmtdjT19#fight=last&type=auras&source=27&pins=0%24Separate%24%23244F4B%24casts%240%240.0.0.Any%24154068.0.0.Hunter%24true%240.0.0.Any%24false%24359844%5E0%24Separate%24%23909049%24casts%240%240.0.0.Any%24154068.0.0.Hunter%24true%240.0.0.Any%24false%24193455&ability=118455)

**Reproducible:**
> Yes

**Howto:**
> Select the Bloody Frenzy Talent. Activate Call of the Wild. Note that none of your pets have Beast Cleave active. Cast Cobra Shot. Note that Beast Cleave is now applied to all of your pets. This does not happen with any other spells other than Serpent Sting.

**Comment by Pewtro** [comment]
This has since been fixed.
