### ISSUE TITLE
Stomps from new pets during Call of the Wild with Bloody Frenzy will frequently miss if more than 15 yards away from the target.

### ISSUE THREAD

**Issue by Tralololo** [SimCMinMax/WoW-BugTracker#1132]
**Game Version:**
> 10.2.0 PTR Build 51239

**Description:**
> Bloody Frenzy is a talent which makes all pets stomp whenever Call of the Wild summons a new pet. This includes the newly summoned pet. However, this new pet will spawn to the side of the player and stomp shortly afterward. Therefore, if you are sufficiently far away from your target (>15 yards roughly), this pet will often not have time to reach it before Stomping and will not hit anything.

**Logs, Images, Videos**
> (https://www.warcraftlogs.com/reports/ZtQb7cYdyJT6hwxf#fight=last&type=damage-done&source=25&ability=201754&target=4) The first instance here was done from max range and has the stomp cast not hit a target 4/11 times. The second instance was done at melee range and has the stomp cast hit at all times.

**Reproducible:**
> Yes

**Howto:**
> Select the Bloody Frenzy Talent. Activate Call of the Wild while in melee range of your target. Note that all instances of Stomps from new pets will hit the target. Repeat the process but this time at max range of your target. This time, notice that new pets from Call of the Wild will occasionally stomp before they reach their target.

**Comment by p3lim** [comment]
Build 51601 changes:

> - Bonus pets from Call of the Wild now spawn on top of your target rather than by your side.

**Comment by Pewtro** [comment]
This has since been fixed.
