### ISSUE TITLE
Beast Mastery 10.2 2-set does not benefit from the duration increase of Dire Frenzy.

### ISSUE THREAD

**Issue by Tralololo** [SimCMinMax/WoW-BugTracker#1133]
**Game Version:**
> 10.2.0 PTR Build 51239

**Description:**
> Beast Mastery 10.2 2-set effect summons a Dire Beast whenever you cast Bestial Wrath for 15 seconds. This beast does not benefit from the duration increase of Dire Frenzy, which is supposed to increase the duration of Dire Beasts by 2 seconds.

**Logs, Images, Videos**
> N/A.

**Reproducible:**
> Examples: Yes

**Howto:**
> Equip the 10.2 2-set effect. Select the Dire Frenzy Talent. Cast Bestial Wrath. Note that the newly spawn beast will only last for 15 seconds rather than 17.

**Comment by Pewtro** [comment]
This has since been fixed.
