### ISSUE TITLE
Wild Instincts does not fade after Call of the Wild ends.

### ISSUE THREAD

**Issue by Tralololo** [SimCMinMax/WoW-BugTracker#1134]
**Game Version:**
> 10.2.0 PTR Build 51239

**Description:**
> Wild Instincts is a talent that is supposed to give a stacking pet damage taken increase to your target whenever you cast Kill Command during Call of the Wild. At the moment, this effect does not go away  when Call of the Wild ends, meaning your can keep refreshing the 30% pet damage increase on your target for as long as you want and also apply it to new targets.

**Logs, Images, Videos**
> (https://www.warcraftlogs.com/reports/hDLagzk2C7y9Xr4W#fight=last&type=auras&spells=debuffs&hostility=1&ability=424567&view=events)

**Reproducible:**
> Yes

**Howto:**
> Select the Wild Instincts Talent. Activate Call of the Wild and spam Kill Command. Notice as your Call of the Wild ends, that you can keep refreshing Wild Instincts on your target with Kill Command, and that you're able to apply it to new targets.

**Comment by Pewtro** [comment]
As of 10.2.0.51297 this has been fixed.
