### ISSUE TITLE
Beast Mastery 10.2 4-set only applies Beast Cleave to the most recently spawned Dire Beast and only the most recent dire beast will Kill Command.

### ISSUE THREAD

**Issue by Tralololo** [SimCMinMax/WoW-BugTracker#1135]
**Game Version:**
> 10.2.0 PTR Build 51239

**Description:**
> The Beast Mastery 10.2 4-set is supposed to allow your Dire Beasts to benefit from Beast Cleave. However, this effect will only benefit the Dire Beast that spawned the most recently. Even if you only have one active Dire Beast, if it's not the most recent spawn it will not gain Beast Cleave.

> Also: Only the most recent Dire Beast will cast Kill Command. This can lead to scenarios where Dire Beast A has Beast Cleave Active but is unable to benefit from Kill Cleave as only the newly spawned Dire Beast B can cast Kill Command.

**Logs, Images, Videos**
> (https://www.warcraftlogs.com/reports/pZ93fBJnLhFvdQXq#fight=last&type=auras&pins=0%24Separate%24%23244F4B%24casts%240%240.0.0.Any%24154068.0.0.Hunter%24true%240.0.0.Any%24false%240&ability=118455&view=events) Note that Beast 1 never gains Beast Cleave, even after Beast 2 expires.

**Reproducible:**
> Yes

**Howto:**
> Equip the Beast Mastery 10.2 4-set. Select the Dire Beast and Beast Cleave Talents. Cast Bestial Wrath to summon a Beast via the10.2 2-set, then use Dire Beast. Cast Multi-shot. Note that the first beast you summoned will not be able to gain Beast Cleave, even after the second Dire Beast Expires.

> Cast Kill Command after the second dire beast expires. Note that the older Dire Beast will not Kill Command.

**Comment by HonorWOW** [comment]
My in-game testing suggests Dire Beasts no longer Kill Cleave, even if Kill Cleave is taken and the T31 4P is equipped.

**Comment by Pewtro** [comment]
Last I checked they do, it's just marked as Beast Cleave damage.

**Comment by HonorWOW** [comment]
Yep, you're right. My mistake.

**Comment by Pewtro** [comment]
The tier now reads that only the most recently summoned should benefit, so this is "fixed".
