### ISSUE TITLE
Time Warp and Primal Rage can stack if pressed in the same millisecond.

### ISSUE THREAD

**Issue by Yumuros** [SimCMinMax/WoW-BugTracker#1139]
**Game Version:**
> 10.1.7 live Build 51421

**Description:**
> Unexpected advantage in combat.

**Details:**
> If a Mage Player and Hunter Player manage to press their Bloodlust Button the same milisecond the whole raid will benefit from both buffs.

**Logs, Images, Videos**
>[WCL]( https://www.warcraftlogs.com/reports/rVCKkfWqRQ7Y9TLF#fight=17&type=auras) - Notice how the Hunter and Mage press Lust in the same millisecond in the Amalgamation Chamber Fight. [Time Warp](https://www.warcraftlogs.com/reports/rVCKkfWqRQ7Y9TLF#fight=17&type=auras&ability=80353) [Primal Rage](https://www.warcraftlogs.com/reports/rVCKkfWqRQ7Y9TLF#fight=17&type=auras&ability=264667)

**Reproducible:**
>rarely

**Howto:**
> Press Bloodlust from Hunter and Mage. Likely only if you manage to press them on the same server tick and millisecond.

**Comment by vituscze** [comment]
When that happens, one of the buffs gives 0% haste. Did you check that?

**Comment by Yumuros** [comment]
> When that happens, one of the buffs gives 0% haste. Did you check that?

Not sure if it's reflected in the logs (not the biggest log guy), but our players all notice having both buffs being active on them and duration ticking down. Also, Stat changes were reflected in having both buffs providing stats in the character sheet.

**Comment by vituscze** [comment]
If you check the cast times right around both lust buffs expire, you can see that the cast before expiry are only 30% faster (rather than 69% faster). So this is not a bug.

**Comment by WuSage3** [comment]
Beacon of the Beyond for the ret pally had a 1.519sec cast time at 2:35.918 in that log (well after lust) and a 1.152sec cast time at 0:03.253 into the fight during the "double bloodlust." 

That's about what you'd expect for a 31% haste difference, which is in line with bloodlust and the Prepared Time minor haste buff the ret pally had during the lust window.
Whereas double lust should be giving you an expected approximate 0.90sec cast time on Beacon. I would say the game properly zeroed out one of the buffs here.

**Comment by Yumuros** [comment]
Alright, thanks for pointing out just shared it, as I wasn't sure. So just a visual issue then.

**Comment by Yumuros** [comment]
Alright, thanks for pointing out just shared it, as I wasn't sure. So just a visual issue then.

**Comment by WuSage3** [comment]
Thanks for contributing regardless!
