### ISSUE TITLE
Secret Technique clones getting munched by Tierset clones

### ISSUE THREAD

**Issue by Stealthiii** [SimCMinMax/WoW-BugTracker#1142]
**Game Version:**
> 10.2.0 PTR Build 51239

**Description:**
> Secret Technique clones can be munched if the damage from a 2-set Shadow Eviscerate hits after casting Secret Technique

**Logs, Images, Videos**
> (https://www.warcraftlogs.com/reports/wxbmdL49aW78PT6N#fight=last&type=damage-done&options=256&start=6672&end=275421&source=5&pins=0%24Separate%24%23244F4B%24damage%240%240.0.0.Any%24681588.0.0.Rogue%24true%240.0.0.Any%24false%24-280720&view=events)
![image](https://github.com/SimCMinMax/WoW-BugTracker/assets/93672777/67ef8b7a-0dd7-4d5f-be29-62e4bc431d54)

**Reproducible:**
> Very easy

**Howto:**
>  just do the normal rotation and it will happen naturally

**Comment by fuu1** [comment]
seems fixed.
