### ISSUE TITLE
Mend Pet and Revive Pet stop functioning properly after casting Call of the Wild

### ISSUE THREAD

**Issue by Pewtro** [SimCMinMax/WoW-BugTracker#1157]
**Game Version:**
> 10.2.0 live Build 52106

**Description:**
> What is your bug about?

After casting Call of the Wild Mend Pet / Revive Pet starts acting erratically.
Mend Pet will transform into Revive Pet even if your main pet hasn't died. Presumably because Call of the Wild pets are "real" pets (hence why they also provide their unique family buffs during the cooldown), and therefore trigger whatever condition to check if your pet is dead internally. 
You can no longer move and cast Mend Pet as it will try to cast Revive Pet even if your ability bar shows Mend Pet. 
It will at times stick to being Revive Pet after the cooldown.

**Logs, Images, Videos**
> Please attach Logs, Images, and/or a Video of the bug.

A few examples of the bug in action: 
https://www.youtube.com/watch?v=VKPgnfSjpQc
From Leak showing mend pet transforming into revive pet: 
https://cdn.discordapp.com/attachments/233915177685352448/1172549572392927394/cotw_mend_pet.mp4

In gif form of it attempting to revive a pet already alive: 
https://cdn.discordapp.com/attachments/233915177685352448/1172550544863285338/Wow_2023-11-10_16-54-18.gif

**Reproducible:**
Yes

**Howto:**
See videos above, but really just cast Call of the Wild and notice behaviour of mend pet / revive pet.

**Comment by Tralololo** [comment]
Note: they've split Mend Pet and Revive Pet into separate buttons (temporarily?), so this is not practically a problem anymore.
