### ISSUE TITLE
Target of Opportunity Stuck

### ISSUE THREAD

**Issue by Kutikuti** [SimCMinMax/WoW-BugTracker#116]
**Game Version:**
> 8.0.1 Alpha Build 25976

**Description:**
> Stuck in the fight between Princess Talanji and Grans Ma'Da Ateena

**Details:**
> Went To report a bug and when i came back the two were fighting and the story doesn't move then. They are stuck fire laser at each other : 
https://i.imgur.com/undefined.jpg
Abandoning the quest and taking it again does not solve : Talanji walks to the circle and then they fight again.
Video of it : https://youtu.be/SOEmjP9w_7E

**Reproducible:**
> Don't know

**Howto:**
> Take Target of Opportunity, go do something else, come back : quest stuck

**Comment by Kutikuti** [comment]
There is now an action to launch the battle.
build 26032

**Comment by N1gh7h4wk** [comment]
Still no option to advance this quest for me, build 26095
