### ISSUE TITLE
Windrunners Guidance can be stacked outside of instances and doesn't reset upon entering

### ISSUE THREAD

**Issue by Pewtro** [SimCMinMax/WoW-BugTracker#1160]
**Game Version:**
> 10.2.0 live Build 52106

**Description:**
> What is your bug about?

Windrunners Guidance increases duration of next trueshot by 1 second per stack. 
It correctly fades shortly after entering combat, but it does not reset upon entering the raid. 
So that means you can stack it outside the raid, get summoned in and benefit from the extended trueshot on pull. 

Even though it fades _shortly after_ entering combat, that fade could probably also be a bit more aggressive as seen in the log below - the trueshot is popped 100ms into combat and still benefits from the extended duration. 

**Logs, Images, Videos**
> Please attach Logs, Images, and/or a Video of the bug.

Here is a log of a 28 second trueshot on pull:
https://www.warcraftlogs.com/reports/Pb3XmrKpZfyV2QvM#fight=2&type=auras&source=13&ability=288613&view=events

**Reproducible:**

Yes

**Howto:**
> How do you reproduce it (if you know).

1. Stack windrunners guidance to 10 
2. Get summoned into a raid 
3. Pop trueshot just before or just after (like 100ms in the log above) combat starts as the buff fades shortly after entering combat
4. See a 28 second trueshot

**Comment by JontiH** [comment]
it seems like this has been "fixed", but at the expense of making WRG drop in between ALL combats, making the trueshot extension effectively worthless in m+
