### ISSUE TITLE
Windrunners Guidance stacks drop to 0 as soon as combat ends, even in dungeons

### ISSUE THREAD

**Issue by JontiH** [SimCMinMax/WoW-BugTracker#1161]
**Game Version:**
> 10.2.0 live Build 52106

**Description:**
> What is your bug about?

Windrunner's Guidance, a talent for marksmanship hunters, is currently dropping all stacks as soon as combat is over, even in a dungeon. The talent works by stacking a buff up to 10 that causes the next trueshot cast to have an increased duration. However, because stacks are dropping out of combat, in m+ unless you have encounters that last 2+ minutes, you will not get any benefit from this trueshot duration extension. I assume this is a response to trying to fix https://github.com/SimCMinMax/WoW-BugTracker/issues/1160

**Logs, Images, Videos**
> Please attach Logs, Images, and/or a Video of the bug.

here is a log of a mythic plus dungeon. If you look at the duration of the trueshots, they are the base duration ~18 seconds, vs the 28 second trueshot that would exist if you had 10 WRG stacks. You would assume that if stacks stuck around, eventually the trueshot would be max duration, but they are all the same.
https://www.warcraftlogs.com/reports/kL76vHCh1aRYbcXJ#fight=last&type=auras&ability=288613

This is the same log but looking at stacks of WRG. You can see them dropping immediately after combat
https://www.warcraftlogs.com/reports/kL76vHCh1aRYbcXJ#fight=last&type=auras&ability=424571

**Howto:**
> How do you reproduce it (if you know).

1) Talent Windrunner's Guidance
2) Start a dungeon.
3) Enter combat, and cast aimed shot to generate stacks of WRG. Pay attention to the amount.
4) After combat drops, but when the dungeon is still active, WRG stacks will drop to 0.

**Comment by Pewtro** [comment]
This is no longer the case.
