### ISSUE TITLE
Sudden Doom doesn't proc

### ISSUE THREAD

**Issue by Melekus** [SimCMinMax/WoW-BugTracker#118]
**Game Version:**
> 8.0.1 Alpha Build 25976

**Description:**
> Sudden Doom does not proc.

**Details:**
> Sudden doom is a proc on your auto attacks that makes your next Death Coil free, but it currently does not proc.

**Reproducible:**
> Yes

**Howto:**
> Log in and auto attack anything.

**Comment by chrislopez24** [comment]
![sdfixed](https://user-images.githubusercontent.com/29229983/36314970-c5ca98e4-1336-11e8-9919-5737b116a56d.png)

Fixed in 26032
