### ISSUE TITLE
Voidwraith Void Flay is not scaling with Priest Modifiers

### ISSUE THREAD

**Issue by seanpeters86** [SimCMinMax/WoW-BugTracker#1180]
**Game Version:**
11.0.0 alpha Build 54311

**Description:**
The voidwraith is not scaling with any priest modifiers. 

This includes:
- [ ] Twist of Fate
- [ ] Mastery: Shadow Weaving
- [ ] Shadowform
- [ ] Idol of Y'Shaarj Devoured Pride
- [ ] Voidform

**Logs, Images, Videos**
TBD

**Reproducible:**
yes

**Howto:**
1. Spawn the pet and have it attack a target with and without the various buffs active.

**Comment by Saeldur** [comment]
VW Mastery Log
https://www.warcraftlogs.com/reports/CpHWN2aTFfzGdVZK#fight=2&type=damage-done&source=1&start=211109&end=231532&view=events
