### ISSUE TITLE
Voidwraith unhasted GCDs

### ISSUE THREAD

**Issue by Saeldur** [SimCMinMax/WoW-BugTracker#1182]
Game Version:
11.0.0 alpha Build 54311

Description:
The Voidwraith has hasted cast times but unhasted GCds.

Reproducible:
yes

Log:
https://www.warcraftlogs.com/reports/1tz4TQmYHPywjVaq#fight=last&type=casts&source=3&view=timeline

Howto:

Spawn the pet and have it attack a target and observe

**Comment by seanpeters86** [comment]
https://www.warcraftlogs.com/reports/BYWvTzV7CQX39pFg#fight=12&type=damage-done&source=1&pins=0%24Separate%24%23244F4B%24auras-gained%240%240.0.0.Any%240.0.0.Any%24true%249303187.0.0.Priest%24false%2410060&ability=-451235&view=events

**Comment by seanpeters86** [comment]
looks fixed now but need to test
