### ISSUE TITLE
Crimson Tempest is not in spelldata for Potent Assassin

### ISSUE THREAD

**Issue by Zarania** [SimCMinMax/WoW-BugTracker#119]
**Game Version:**
> 8.0.1 Alpha Build 25976

**Description:**
> Crimson Tempest is not included in the spelldata for Potent Assassin despite the bleed portion being affected by it.

**Reproducible:**
> Yes

**Howto:**
> Check effect 2 on http://bfa.wowhead.com/spell=76803/mastery-potent-assassin

**Comment by Mystler** [comment]
The CT bleed spell is whitelisted in the Mastery.
