### ISSUE TITLE
The Crawg Mada, stuck NPC

### ISSUE THREAD

**Issue by Kutikuti** [SimCMinMax/WoW-BugTracker#123]
**Game Version:**
> 8.0.1 Alpha Build 26032

**Description:**
> Amaka the Crawg Mada is stuck and can't be hit by the quest item

**Details:**
> We have to kill Amaka the Crawg Mada but he is stuck in some tree and can't be hit
https://imgur.com/a/SFqHY

**Reproducible:**
> 100%

**Howto:**
> Have The Crawg Mada

**Comment by Kutikuti** [comment]
You can now walk to him and hit him while on him but there is still a big branch through his house that blocks vision

**Comment by lgkern** [comment]
Still present as today's build
