### ISSUE TITLE
Venom rush refunds energy before energy is spent

### ISSUE THREAD

**Issue by Kiwifruity** [SimCMinMax/WoW-BugTracker#126]
**Game Version:**
> 8.0.1 Alpha Build 26032

**Description:**
> Venom rush causes mutilate to refund 5 energy when used on a poisoned target. The refund portion occurs before the energy for the mutilate is consumed however, which leads to lost energy if mutilate is cast at full or near full energy

**Reproducible:**
> 100%

**Howto:**
> Cast mutilate on a poisoned target when your energy is full. Observe energy refund before energy is spent on mutilate.

**Comment by Zarania** [comment]
![image](https://user-images.githubusercontent.com/8323677/36190654-6c6df5a4-1127-11e8-9cce-53c34c616f98.png)

**Comment by Mystler** [comment]
Fixed in 8.0.1.26095.
