### ISSUE TITLE
Dispatch/Crimson Tempest do not proc poisons

### ISSUE THREAD

**Issue by Kiwifruity** [SimCMinMax/WoW-BugTracker#127]
**Game Version:**
> 8.0.1 Alpha Build 26032

**Description:**
> Dispatch and crimson tempest do not proc poisons. 

**Details:**
> In logs deadly poison procs/crippling refreshes come up at the same timestamp as the spell/melee that procced it. In these logs you can see there's no procs when dispatch is used:

https://www.warcraftlogs.com/reports/XWrYZTkm3yqPfLvg/#fight=last&type=damage-done&source=1&pins=0%24Separate%24%23244F4B%24damage%240%240.0.0.Any%246327306.0.0.Rogue%24true%240.0.0.Any%24false%24113780%5E0%24Separate%24%23909049%24auras-cast%240%240.0.0.Any%246327306.0.0.Rogue%24true%240.0.0.Any%24false%243409&ability=111240&view=events

> Similarly for crimson tempest:

https://www.warcraftlogs.com/reports/LAzmRNr4pDdTJcY2/#fight=last&type=damage-done&pins=0%24Separate%24%23244F4B%24auras-cast%240%240.0.0.Any%240.0.0.Any%24true%240.0.0.Any%24false%243409%5E0%24Separate%24%23909049%24damage%240%240.0.0.Any%246327306.0.0.Rogue%24true%240.0.0.Any%24false%24113780&source=4&ability=121411&view=events

**Reproducible:**
> 100%

**Howto:**
> Cast dispatch/crimson tempest, poisons will never proc on casts

**Comment by Mystler** [comment]
Fixed in 8.0.1.26095.
