### ISSUE TITLE
Wailing Arrow not affected by Trick Shots

### ISSUE THREAD

**Issue by koeros** [SimCMinMax/WoW-BugTracker#1275]
**Game Version:**
> 11.0.2 live Build 56313

**Description:**
> What is your bug about?

Wailing Arrow does not benefit from Trick Shots despite consuming the Trick Shots buff

**Reproducible:**
> Examples: yes

**Howto:**
> How do you reproduce it (if you know).

Cast Multi-Shot on the 5 target cleave dummies in Dornogal to trigger Trick Shots. Cast Trueshot with Readiness to immediately trigger Wailing Arrow and cast it. You will know that only 6 hits register, one for the main target hit and five from the secondary explosion. This consumes the Trick Shots buff.

**Comment by Pewtro** [comment]
Intended and no longer consumes Trick Shots
