### ISSUE TITLE
Mid-cast Aimed Shot consumes Black Arrow Aimed Shot reset cast speed reduction to no effect

### ISSUE THREAD

**Issue by koeros** [SimCMinMax/WoW-BugTracker#1283]
**Game Version:**
> 11.0.2 live Build 56313

**Description:**
> What is your bug about?

Mid-cast Aimed Shot consumes Black Arrow Aimed Shot reset cast speed reduction to no effect

**Reproducible:**
> Examples: yes

**Howto:**
> How do you reproduce it (if you know).

Begin Aimed Shot cast and cancel repeatedly while Black Arrow is up. When you see the Black Arrow Aimed Shot reset, allow the cast to finish. Note that the following cast of Aimed Shot will not benefit from the Black Arrow Aimed Shot reset cast speed reduction.

**Comment by Pewtro** [comment]
Black Arrow has been reworked.
