### ISSUE TITLE
Casting Aimed Shot with Lock and Load and the Black Arrow Aimed Shot reset cast speed reduction active consumes both effects to no additional benefit

### ISSUE THREAD

**Issue by koeros** [SimCMinMax/WoW-BugTracker#1284]
**Game Version:**
> 11.0.2 live Build 56313

**Description:**
> What is your bug about?

Casting Aimed Shot with Lock and Load and the Black Arrow Aimed Shot reset cast speed reduction active consumes both effects to no additional benefit.

**Reproducible:**
> Examples: yes

**Howto:**
> How do you reproduce it (if you know).

Auto-attack a dummy until Lock and Load triggers. Immediately cast Black Arrow and wait for an Aimed Shot reset. Cast Aimed Shot after the reset while Lock and Load is still active. You should observe that the following Aimed Shot does not benefit from the Black Arrow Aimed Shot reset cast speed reduction.

**Comment by Pewtro** [comment]
Black Arrow has been reworked.
