### ISSUE TITLE
The Black Arrow Aimed Shot reset cast speed reduction does not produce a visible player buff

### ISSUE THREAD

**Issue by koeros** [SimCMinMax/WoW-BugTracker#1285]
**Game Version:**
> 11.0.2 live Build 56313

**Description:**
> What is your bug about?

The Black Arrow Aimed Shot reset cast speed reduction does not produce a visible player buff.

**Reproducible:**
> Examples: yes

**Howto:**
> How do you reproduce it (if you know).

Cast Black Arrow and wait for an Aimed Shot reset. You will see that no buff icon appears to denote the cast speed reduction on Aimed Shot. A glow does appear around Aimed Shot to denote the reset, however, it is the same glow produced by Lock and Load.

**Comment by Pewtro** [comment]
Black Arrow has been reworked.
