### ISSUE TITLE
Models and animations disappear in somewhat random locations with some camera angles

### ISSUE THREAD

**Issue by Bloodmallet** [SimCMinMax/WoW-BugTracker#134]
**Game Version:**
> 8.0.1 Alpha Build 26032

**Description:**
> Ghost Wolf (Shaman) and probably any other smaller model disappears in some sort of underwater threshold behaviour.

**Logs, Images, Videos**
> ![image](https://user-images.githubusercontent.com/9075987/36332363-3597f460-1372-11e8-8701-3102ba153651.png)

**Reproducible:**
> yes

**Howto:**
> Be small, look from somewhat higher angle than horizontal, disappear. Ghost Wolf from Shaman works to show this.

**Comment by BanterDK** [comment]
I have noticed seemingly the same (or some variant of) issue  at Pandaria - The Golden Terrace
(The target dummies outside seemed to do the same thing the first time I walked around, wasn't able to replicate the issue)

[Gif 1 - UI/Friendly Nameplates](https://i.gyazo.com/202e943bf4b196b492b1b7ba3b93c56b.gif) -- Need to be in certain positions in that room (downstairs, east room. Behind the Tauren)
[Gif 2 - Fire VFX ](https://i.gyazo.com/be227f8bd935455b51bf59b749439845.gif)-- Easily replicatable for me, viewable all the time

**Comment by Bloodmallet** [comment]
Same behaviour as shown in those two gifs happened yesterday in Freehold when fighting in the Ting of Booty. Those spinning turtle shells weren't visible at all. [Here](https://clips.twitch.tv/SwissCleanMosquitoFunRun) is a recording of this

**Comment by Bloodmallet** [comment]
I renamed the issue, because from what I saw in BanterDK s answer and that dungeon yesterday. This seems to be a broader problem.

**Comment by Bloodmallet** [comment]
Closing due to age
