### ISSUE TITLE
Purified Titan Essence resulting in infinite tokens

### ISSUE THREAD

**Issue by Mystler** [SimCMinMax/WoW-BugTracker#136]
**Game Version:**
> 7.3.5 Build 25996

**Description:**
> If you have all legendaries on two chars, buy a Purified Titan Essence on one of them (e.g. a Druid), and get a legendary token for your other char with all legendaries (e.g. a DK), that token will always turn into itself when using it. It seems the "if you have all legendaries for that class, you will get a token for another one" fallback is only applied to drops and the Essence, but not the resulting tokens.

**Details:**
> ![Infinite Tokens](https://puu.sh/zix1d/c66f84815b.png)

**Reproducible:**
> Yes, if you are "unlucky". Happened two time to a friend of mine, by now.

**Comment by vituscze** [comment]
Should be fixed with these hotfixes: https://worldofwarcraft.com/en-gb/news/21365424/hotfixes-february-20
