### ISSUE TITLE
"Profanity Filter" phasing

### ISSUE THREAD

**Issue by Mystler** [SimCMinMax/WoW-BugTracker#15]
**Game Version:**
> 8.0.1 Alpha Build 25976

**Description:**
> Kajosh despawns when you approach him. ("Profanity Filter" quest in Nazmir)

**Details:**
> After burning the totems for the quest "Profanity Filter" I can see Kajosh near a blood troll camp. As soon as I get within ~30 yards of him he despawns (phases out?) and I cannot continue with the quest. I tried re-logging but that did not help.

**Reproducible:**
> Not sure if this is a general issue or only for me.

**Howto:**
> Do the "Profanity Filter" quest that you find along the way of pilgrimage to Torga in Nazmir.

**Comment by Melekus** [comment]
More details on this : I noticed that the NPC phases out when you switch area between the Blood Bog and Natha'vor, and reappears if you go back in the Blood Bog.
The only work-around at the moment is to use a mount and rush to his side very quickly before he despawns.

Reproducible : it looks to be a general issue.

**Comment by Kutikuti** [comment]
Yeah just got the same issue, you gotta be fast to launch the dialog

**Comment by Kutikuti** [comment]
The zone isn't here anymore

**Comment by Kutikuti** [comment]
found the zone but the phasing issue is gone
