### ISSUE TITLE
Class Hall Mission LUA Error

### ISSUE THREAD

**Issue by Kutikuti** [SimCMinMax/WoW-BugTracker#150]
**Game Version:**
> 8.0.1 Alpha Build 26095

**Description:**
> When openning Class Hall Mission, there is a lua error that pops up

**Details:**
> Just after creating the character, when you click on map of zandalar in The royal Chambers to take the quest (Your Next Move), when you click on complete quest it pops up Class Hall missions and a LUA Error

**Logs, Images, Videos**
Message: 
```
...dOns\Blizzard_AdventureMap\Blizzard_AdventureMap.lua:68: 'for' limit must be a number
Time: Fri Feb 23 09:37:06 2018
Count: 1
Stack: ...dOns\Blizzard_AdventureMap\Blizzard_AdventureMap.lua:68: 'for' limit must be a number
[C]: ?
...dOns\Blizzard_AdventureMap\Blizzard_AdventureMap.lua:68: in function `RefreshInsets'
...ace\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:422: in function `RefreshAll'
...ace\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:50: in function `OnShow'
...dOns\Blizzard_AdventureMap\Blizzard_AdventureMap.lua:45: in function `OnShow'
...Blizzard_OrderHallUI\Blizzard_OrderHallMissionUI.lua:193: in function <...Blizzard_OrderHallUI\Blizzard_OrderHallMissionUI.lua:191>
[C]: in function `Show'
Interface\FrameXML\UIParent.lua:2502: in function `SetUIPanel'
Interface\FrameXML\UIParent.lua:2304: in function `ShowUIPanel'
Interface\FrameXML\UIParent.lua:2212: in function <Interface\FrameXML\UIParent.lua:2208>
[C]: in function `SetAttribute'
Interface\FrameXML\UIParent.lua:2990: in function `ShowUIPanel'
Interface\FrameXML\UIParent.lua:1638: in function <Interface\FrameXML\UIParent.lua:1008>
```

**Reproducible:**
> 100%

**Howto:**
> Create a character
> Take Empowering the Heart to Nathanos
> Click on Map of Zandalar
> Click Complete Quest
> LUA Error

**Comment by Mystler** [comment]
Let me note: This error does not seem to occur on characters created before the latest build (did Nazmir and the Stormwind Scenario). For me, it simply showed a scouting map of the Broken Isles.
