### ISSUE TITLE
How to train your Direhorn stuck

### ISSUE THREAD

**Issue by Kutikuti** [SimCMinMax/WoW-BugTracker#158]
**Game Version:**
> 8.0.1 Alpha Build 26095

**Description:**
> The quest How to train you Direhorn doesn't advance at meet Pinky

**Details:**
> While doing the quest, you jump on the Direhorn, advance on the path, then pinky and then nothing happen.
Starting again the quest doesn't solve

**Logs, Images, Videos**
> https://i.imgur.com/jK21c28.jpg

**Reproducible:**
> 100%

**Howto:**
> Take How to train you dragon
> Start scenario
> Advance on the Path
> stuck at meet pinky

**Comment by Mystler** [comment]
Had the same issue, but it worked for me when I exited the "vehicle" and started it again.

**Comment by Kutikuti** [comment]
Yeah that worked the second time.
Bonus for the first time where i had a disconnect when going into the vehicule. Still not quite good :)
