### ISSUE TITLE
Shadow Blades unknown damage school modifier

### ISSUE THREAD

**Issue by Mystler** [SimCMinMax/WoW-BugTracker#17]
**Game Version:**
> 8.0.1 Alpha Build 25976

**Description:**
> Shadow Blades is likely supposed to turn AA, Backstab, and Shadowstrike into "Shadowstrike" damage, meaning benefits for both Shadow and Physical. However, Backstab and Shadowstrike only seem to deal "Unknown" damage, as of now, and auto attacks are still replaced by a shadow attack. Furthermore, "Shadowstrike" can be confusing because we have an ability with the same name and it may not be clear this is a mixed-school label. ("Shadowstrike deals Shadowstrike damage")

**Reproducible:**
> yes

**Howto:**
> Use Shadow Blades and check out the damage school of Backstab and Shadowstrike in the combat log.

**Comment by RosvallM** [comment]
Worth noting is that the autoattacks are listed as shadow damage in combat log and not shadowstrike or unknown. (8.0.1.25976)

**Comment by Mystler** [comment]
Updated in 8.0.1.26095: Backstab and Shadowstrike deal Shadowstrike damage now. However, auto attacks are still using the old system and get replaced by Shadow Blade attacks that deal Shadow damage. I'd assume this is subject to change as well, in the future.

**Comment by Mystler** [comment]
Closing this since Shadow Blades has been reworked.
