### ISSUE TITLE
Tombstone doesn't reduce Blood tap's cooldown by 2s per stack

### ISSUE THREAD

**Issue by Melekus** [SimCMinMax/WoW-BugTracker#178]
**Game Version:**
> 7.3.5 Build 25996

**Description:**
> The interaction between the Blood Dk talents Tombstone and Blood Tap doesn't happen as expected.

**Details:**
> Blood Tap's cooldown should reduced by 2s whenever a bone shield charge is consumed. This is the case when a bone shield charge is consumed by a melee attack but not when using Tombstone.
Casting Tombstone instead reduces Blood Tap's remaining by 1s per bone shield charge consumed, rather than 2s. 

**Reproducible:**
> Yes.

**Howto:**
> Use both talents together.

**Comment by BanterDK** [comment]
Blood tap no longer exists in PTR/Beta, will close this ticket once pre patch launches
