### ISSUE TITLE
Blood tap cooldown isn't reduced when bone shield is consumed

### ISSUE THREAD

**Issue by Melekus** [SimCMinMax/WoW-BugTracker#179]
**Game Version:**
> 8.0.1 Alpha Build 26131

**Description:**
> Blood tap's cooldown isn't reduced when bone shield is consumed by melee attacks

**Details:**
> Blood tap cooldown is supposed to be reduced by 2s every time a bone shield charge is consumed, yet its cooldown isn't reduced when the player takes a melee attack and a charge is consumed. 

**Reproducible:**
> Yes.

**Howto:**
> Take melee attack damage while bone shield is up with blood tap talented and on cooldown.

**Comment by BanterDK** [comment]
Blood tap has been removed
