### ISSUE TITLE
Crimson Tempest Interactions

### ISSUE THREAD

**Issue by Mystler** [SimCMinMax/WoW-BugTracker#180]
**Game Version:**
> 8.0.1 Alpha Build 26131

**Description:**
> Since the recent change to Crimson Tempest spell data that merged initial damage and dot component into one spell there are some broken interactions.

**Details:**
> - Tooltip duration is wrong, the actual formula seems to be `4s + 2s * CP`. In accordance to this the periodic damage formula should also be `TickDMG * (CP+2)` for each actual timespan.
> - Crimson Tempest is not affected by the Mastery at all.
> - The DoT component is not affected by the 5% increase from Deeper Stratagem.
> - Exsanguinate again does not work with CT.
> - Bleed ticks do not proc the Venomous Vim energy gain. (CT is not listed in the tooltip. Is it Intended? Should this be added?)

**Comment by Mystler** [comment]
Added one more issue to the details above. CT duration is actually 2s longer.
The actual duration formula seems to be `4s + 2s * CP`. In accordance to this the periodic damage formula should also be `TickDMG * (CP+2)`

**Comment by Lorentz21** [comment]
Build 26175
Nightstalker talent works only with initial portion of the damage and does not affect bleed effect

**Comment by Mystler** [comment]
All of the issues listed above appear to be fixed:
- Duration got shortened to what is displayed in the tooltip.
- Mastery and DS affect all of CT now.
- Exsanguinate works again.
- Nightstalker snapshot for the DoT effect works as well.

Since CT is not listed in Venomous Wounds, assume this is intended. Thus, all points should be addressed properly and I am closing the issue.
