### ISSUE TITLE
LUA error when opening guild frame

### ISSUE THREAD

**Issue by Kutikuti** [SimCMinMax/WoW-BugTracker#182]
**Game Version:**
> 8.0.1 Alpha Build 26141

**Description:**
> When you open Guild panel, an lua error pops up

**Details:**
> This seem related to News feed

**Logs, Images, Videos**
LUA Error : 
Message: Unknown: Couldn't find relative frame: $parentDisabledLeft
Time: Thu Mar  1 19:17:20 2018
Count: 9

**Reproducible:**
> 100%

**Howto:**
> Open guild panel

**Comment by Glynnyx** [comment]
I also got the following when opening the guild frame too. 

`Message: Unknown: Couldn't find relative frame: $parentDisabledRight
Time: Sun Mar 11 02:00:28 2018
Count: 9`
