### ISSUE TITLE
Iron Wire only works from stealth

### ISSUE THREAD

**Issue by Mystler** [SimCMinMax/WoW-BugTracker#19]
**Game Version:**
> 8.0.1 Alpha Build 25976

**Description:**
> The Iron Wire talent only works when using Garrote from stealth.

**Details:**
> The silence extension as well as the Iron Wire debuff that makes enemies deal less damage are not applied when you use Garrote without being stealthed.

**Reproducible:**
> yes

**Howto:**
> Use Garrote without being in stealth and check the enemy debuffs.

**Comment by Zarania** [comment]
This seems to be a non issue?  Garrote only silences when used from stealth and Iron Wire only works on those silenced by Garrote

![image](https://user-images.githubusercontent.com/8323677/36058195-54a92b92-0de8-11e8-941c-af92b5feeec9.png)


![image](https://user-images.githubusercontent.com/8323677/36058192-45373af0-0de8-11e8-95c6-eb729e7177d8.png)
