### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by lgkern** [SimCMinMax/WoW-BugTracker#2]
**Game Version:**
> 8.0.1 Alpha Build 25976

**Description:**
> What your bug is about ?
I couldn't open issues

**Reproduce rate:**
> How frequent are you able to reproduce it ? Either a word like "Low" or a perctange like "100%".
100%

**Details:**
> Try to explain the bug, do not hesitate to add attachment like logs/images/videos/...
Maybe now I can? 

**Howto:**
> How do you reproduce it (if you know).
Clicking stuff

**Comment by Aethys256** [comment]
Was a test issue, closing it.
Thanks :)
