### ISSUE TITLE
Healing prediction is off for non-healing spec

### ISSUE THREAD

**Issue by Kutikuti** [SimCMinMax/WoW-BugTracker#20]
**Game Version:**
8.0.1 Alpha Build 25976

**Description:**
The healing prediction of Shadow Mend is exagerating and do not reflect what the real healing is.

Edit : Appear to be affecting multiple spec. See comments

**Details:**
When casting shadow mend, it predict a big heal that will give you over the HP pool :  
https://i.imgur.com/wiSPIzc.jpg

In reality, it's much less : 
https://i.imgur.com/zK272Zy.jpg

Other heal of priest (holy, disc) doesn't seem to be affected 

**Reproducible:**
100%

**Howto:**
Be shadow Priest
Cast Shadow Mend
Observe full hp prediction
Be disapointed

**Comment by Bloodmallet** [comment]
Same prediction overvaluation happens to Healing Surge of Elemental Shamans. I'd expect all dps healing spells with cast time to have a visual overvaluation. To support this claim we'd need a druid is healing touch to check this out (do they still have that?)

**Comment by weakweak** [comment]
Seems to be linked to a damage taken indicator issue:
https://gfycat.com/ImpracticalMedicalAgama
It blinks the all of your remaining health before returning where it is supposed to be.

**Comment by Bloodmallet** [comment]
- Fixed for Elemental Shaman

**Comment by Kutikuti** [comment]
Fixed for Shadow also

**Comment by Kutikuti** [comment]
Fixed for 
Flash of Light, Retribution Paladin
Flash of Light, Protection Paladin

**Comment by Kutikuti** [comment]
And fixed for Healing Surge, Enhancement Shaman.
Closing
