### ISSUE TITLE
Double Tap talent buff doesn't get consumed by Rapid Fire

### ISSUE THREAD

**Issue by teyka21** [SimCMinMax/WoW-BugTracker#200]
**Game Version:**
> 8.0.1 Alpha Build 26175

**Description:**
> Double Tap talent buff doesn't get consumed by Rapid Fire. Works properly with Aimed Shot.

**Details:**
> Double Tap talent buff makes your next Aimed Shot fire second time or Rapid Fire shoot twice its shots. However using Rapid Fire doesn't consume the buff but you still get 100% more shots. After that you can still use Aimed Shot and it will hit twice.

**Logs, Images, Videos**
https://puu.sh/zFJ52/2a63023617.webm

**Reproducible:**
yes

**Howto:**
Spec into Double Tap level 90 talent, use it, use Rapid Fire, use Aimed Shot

**Comment by teyka21** [comment]
Can't label this issue - just in case, Double Tap is a Marksmanship talent

**Comment by nuoHep** [comment]
Build 26367
Fixed, properly consumes Double Tap now
