### ISSUE TITLE
Crimson Tempest doesn't display as a debuff on target nameplates

### ISSUE THREAD

**Issue by timwoj** [SimCMinMax/WoW-BugTracker#203]
**Game Version:**
> 8.0.1 Alpha Build 26231

**Description:**
> Crimson Tempest doesn't display as a debuff on the target nameplates, while Garrote and Rupture both do.

**Details:**
> See description.

**Reproducible:**
> Yes.

**Howto:**
> Turn on enemy nameplates, cast Crimson Tempest on a target.

**Comment by Mystler** [comment]
Fixed in 8.0.1.26297.
