### ISSUE TITLE
Tooltips causing "designer error"

### ISSUE THREAD

**Issue by Mystler** [SimCMinMax/WoW-BugTracker#22]
**Game Version:**
> 8.0.1 Alpha Build 25976

**Description:**
> Some buff's tooltips seem to cause an error message. This is likely because they have an effect that is shown as 0.

**Details:**
> ![Designer Error](https://puu.sh/zjj6P/a3015f0fa1.png)
>
> Affected:
> - ~~Stealth (as Assassination with Nightstalker or Master Assassin)~~
> - ~~Slice and Dice (as Outlaw; seems to have a second energy gain effect that is invalid)~~

**Reproducible:**
> yes

**Howto:**
> Hover over the buff with the mouse cursor to trigger the tooltip display.

**Comment by Aethys256** [comment]
Happens on Valeera and some other rogue legendaries.

**Comment by Bloodmallet** [comment]
Happens with Ghost Wolf in all Shaman specs, too.

**Comment by RosvallM** [comment]
Also happens with Shadow Dance for subtlety rogues when you hover the active buff.

**Comment by Mystler** [comment]
I've seen the ones i reported and Shadow Dance fixed with Build 26032.

**Comment by Bloodmallet** [comment]
Ghost Wolf is fixed too.

**Comment by Mystler** [comment]
I am going to close this issue since all reported tooltip errors seem to be fixed. If there is another one missing feel free to reopen.
