### ISSUE TITLE
Argus the Unmaker [Mythic] - Guardian Druid - Frenzied Regeneration

### ISSUE THREAD

**Issue by cetraben** [SimCMinMax/WoW-BugTracker#223]
**Game Version:**
> 7.3.5 Build 26124

**Description:**
> Frenzied Regeneration Damage Calculations

**Details:**
> Argus the Unmaker [Mythic] - Guardian Druid

The damage taken from Rent Soul does not contribute to the damage taken calculation for Frenzied Regeneration therefore the heal amount is significantly lower than intended.

**Logs, Images, Videos**
> 
https://www.warcraftlogs.com/reports/CRkap2A3QdZzFDhX/#fight=last&type=healing&source=19&pins=0%24Separate%24%23244F4B%24damage%241%240.0.0.Any%240.0.0.Any%24true%24137867795.0.0.Druid%24false%24258837&ability=22842&view=events

00:06:24.987 | Environment Rent Soul Jardr 3907040 |  
00:06:25.698 | Environment Rent Soul Jardr 3907040 |  
00:06:26.593 | Jardr Frenzied Regeneration Jardr Tick +190474 |  
00:06:27.086 | Jardr Frenzied Regeneration Jardr Tick +190473 |  
00:06:27.583 | Jardr Frenzied Regeneration Jardr Tick +190474 |  
00:06:28.096 | Jardr Frenzied Regeneration Jardr Tick +190474 |  
00:06:28.572 | Jardr Frenzied Regeneration Jardr Tick +190474 |  
00:06:29.060 | Jardr Frenzied Regeneration Jardr Tick +190473

**Reproducible:**
> Consistent throughout logs

**Howto:**
> How do you reproduce it (if you know).
N/A

**Comment by Jundarer** [comment]
old
