### ISSUE TITLE
Crimson Tempest not working with Deeper Stratagem

### ISSUE THREAD

**Issue by Mystler** [SimCMinMax/WoW-BugTracker#229]
**Game Version:**
> 8.0.1 Alpha Build 26297

**Description:**
> The last build (accidentally?) removed Crimson Tempest from the Deeper Stratagem whitelist causing it to consume only up to 5 Combo Points.

**Howto:**
> Look at the tooltip of Crimson Tempest with Deeper Stratagem. Also use it at 6cp and see it only consume 5.

**Comment by Lorentz21** [comment]
Build 26367
Fixed, properly consumes 6 combo points now
