### ISSUE TITLE
Arcane Explosion doesn't work with Rule of Threes

### ISSUE THREAD

**Issue by vituscze** [SimCMinMax/WoW-BugTracker#235]
**Game Version:**
> 8.0.1 Alpha Build 26367

**Description:**
> Arcane Charges gained from Arcane Explosion do not seem to activate Rule of Threes.

**Reproducible:**
> yes

**Howto:**
> Cast Arcane Explosion until you get to three charges, Rule of Threes buff isn't applied.

**Comment by cgdangelo** [comment]
Still broken in 8.0.1 Alpha Build 26433. 🤔
