### ISSUE TITLE
"Cease all Summoning" underground

### ISSUE THREAD

**Issue by Nianel** [SimCMinMax/WoW-BugTracker#24]
**Game Version:**
> 8.0.1 Alpha Build 25976

**Description:**
> When you complete the quest at the npc "Summoner Yarz", after the short cinematic, you fall underground after he strangle you.

**Details:**
> https://imgur.com/a/eanav

**Reproducible:**
> Yes

**Howto:**
> Do the "Cease all Summoning" quest in the Torga's Innards.

**Comment by Kutikuti** [comment]
solved in 26491
