### ISSUE TITLE
Rapid Decomposition affects Dancing Rune Weapon

### ISSUE THREAD

**Issue by Melekus** [SimCMinMax/WoW-BugTracker#240]
**Game Version:**
> 8.0.1 Alpha Build 26433

**Description:**
> The new version of the Rapid Decomposition talent affects the pet's blood plague tick rate.

**Details:**
> Dancing Rune Weapon abilities act as if it was a Death Knight without any talent selected : DRW don't copy talent spells cast by their owner, and don't proc talent effects from those abilities. For example, blood boils casted by Dancing Rune Weapon don't proc Hemostasis that was introduced in the same alpha build as the rework of Rapid Decomposition. 
Yet, the Blood Plague applied by Dancing Rune Weapon have their tick rate affected by the Rapid Decomposition Talent : in the log linked below, we can see the tick rate is clearly not 3s.

**Logs, Images, Videos**
> https://www.warcraftlogs.com/reports/1HgKqB96pWzXDwkb#fight=2&type=damage-done&ability=55078&view=events&source=3&target=2.1

**Reproducible:**
> Yes

**Howto:**
> Talent into Rapid Decomposition, cast Dancing Rune Weapon followed by blood boil

**Comment by BanterDK** [comment]
this is still relevant as of b26936 -- [Log](https://www.warcraftlogs.com/reports/pPkR7n2HTgQDCbMx/#fight=last&type=damage-taken&hostility=1&source=2.3&view=events&ability=55078)

**Comment by Melekus** [comment]
Still relevant as of shadowlands beta build 35598. Safe to assume it's intended, although not a great sign of consistent behaviour.
