### ISSUE TITLE
Hemostasis affects Dancing Rune Weapon

### ISSUE THREAD

**Issue by Melekus** [SimCMinMax/WoW-BugTracker#241]
**Game Version:**
> 8.0.1 Alpha Build 26433

**Description:**
> The Hemostasis buff awarded by the same talent increases damage done by Dancing Rune Weapon's Death Strike.

**Details:**
> As stated in https://github.com/SimCMinMax/WoW-BugTracker/issues/240, Dancing Rune Weapon has a history of ignoring the player's talents. This is respected in some way by the Hemostasis talent : the blood boils casted by Dancing Rune Weapon will not trigger an additional stack of the buff on the player. However, when the player casts Death Strike, the buff is consumed and increase both the player's and the Dancing Rune Weapon's Death Strike damage. 

**Logs, Images, Videos**
> https://www.warcraftlogs.com/reports/RaB1bmnvzt3qx7rp/#fight=1&type=damage-done&pins=0%24Separate%24%23244F4B%24auras-gained%240%240.0.0.Any%240.0.0.Any%24true%240.0.0.Any%24false%24273947&source=3&view=events 

**Reproducible:**
> Yes

**Howto:**
> Compare the damage done by Dancing Rune Weapon's Death Strike with and without Hemostasis stacks.

**Comment by BanterDK** [comment]
Still relevant as of b26936 -- [Picture with calculation](https://i.gyazo.com/def05c2cdc1f44ba016321451a9ca5b8.png)

**Comment by Melekus** [comment]
Still relevant as of shadowlands beta build 35598. Safe to assume it's intended, although not a great sign of consistent behaviour.
