### ISSUE TITLE
Storm of Steel being consumed by Pistol shot

### ISSUE THREAD

**Issue by Loktark** [SimCMinMax/WoW-BugTracker#242]
**Game Version:**
> 8.0.1 Alpha Build 26476

**Description:**
> The azerite trait "Storm of Steel" for outlaw rogues is being consumed improperly.

**Details:**
> Storm of steel is being consumed by pistol shot and Dispatch when the tooltip states that it should only effect Dispatch. When consumed by pistol shot the trait is completely wasted as it does not increase the damage of it.

**Reproducible:**
> 100%

**Howto:**
> Cast Sinister strike until you get a 2nd hit to trigger the azerite trait then cast Pistol shot, observe the buff being consumed.

**Comment by Mystler** [comment]
Storm of Steels does not exist anymore.
