### ISSUE TITLE
Broadsides does not affect Ambush/Gouge

### ISSUE THREAD

**Issue by Kiwifruity** [SimCMinMax/WoW-BugTracker#245]
**Game Version:**
> 8.0.1 Alpha Build 26476

**Description:**
> Roll the bones' Broadside buff is supposed to cause combo generators to generate 1 additional combo point and deal 20% more damage. Ambush does not gain the 20% increased damage nor the additional 1 combo point. Gouge also does not gain the additional combo point.

**Reproducible:**
> 100%

**Howto:**
> Roll the bones until you get Broadsides. Use ambush/gouge, observe normal combo points rather than +1

**Comment by Mystler** [comment]
Fixed in the latest build.
