### ISSUE TITLE
Venom Rush active even when not the chosen talent

### ISSUE THREAD

**Issue by weakweak** [SimCMinMax/WoW-BugTracker#25]
**Game Version:**
> 8.0.1 Alpha Build 25976

**Description:**
> Talent Venom Rush Procs regardless of it being active or not.

**Details:**
> Spec into Toxic Blade or Exsanguinate and still benefit from Venom Rush

**Reproducible:**
> 100%

**Howto:**
> Spec into Toxic Blade or Exsanguinate and Mutilate a poisoned target.
https://www.warcraftlogs.com/reports/xYvctPB6fRGWKyg4/#fight=last&type=resources&pins=0%24Separate%24%23244F4B%24damage%240%240.0.0.Any%246326793.0.0.Rogue%24true%240.0.0.Any%24false%24703%5E0%24Separate%24%23909049%24auras-gained%241%240.0.0.Any%240.0.0.Any%24true%240.0.0.Any%24false%24703&spell=103&view=events
https://i.imgur.com/jFHhT6m.png

**Comment by Mystler** [comment]
Fixed in 8.0.1.26095.
