### ISSUE TITLE
Spending Runic Power on Epidemic doesn't proc Runic Corruption

### ISSUE THREAD

**Issue by Melekus** [SimCMinMax/WoW-BugTracker#253]
**Game Version:**
> 8.0.1 Beta Build 26530

**Description:**
> Epidemic doesn't proc Runic Corruption

**Details:**
> Runic Corruption has a 1% chance per Runic Power spent to trigger and increase rune regeneration rate by 100% for 3s. With the latest patch, Epidemic now costs 30 RP and should have a 30% chance to proc Runic Corruption. Yet it doesn't proc it at all.

**Reproducible:**
> Yes

**Howto:**
> Cast Epidemic.

**Comment by BanterDK** [comment]
Fixed in b26567
