### ISSUE TITLE
Rune Strike can result in only 2 runes charging

### ISSUE THREAD

**Issue by Chewsdaydk** [SimCMinMax/WoW-BugTracker#262]
**Game Version:**
> 8.0.1 Beta Build 26604

**Description:**
> Using Rune Strike can cause only 2 runes to be charging with 3 runes active.

**Details:**
> Using Rune Strike before a Rune comes off cooldown will activate that rune and result in only 2 runes charging. [Likely related to this bug](https://github.com/SimCMinMax/WoW-BugTracker/issues/262)

>E.g. If all runes are on cooldown and you use Rune Strike to generate the first Rune before it refreshes. After Rune 2 and 3 come off cooldown Rune 4 and 5 will start charging leaving Rune 6 stuck.

**Logs, Images, Videos**
>[Low res video](https://i.gyazo.com/f003be608006f1a0af35d2a8922ec0f1.mp4) 

>[This footage shows the bug happening on my ElvUI](https://i.gyazo.com/467327421f27c30c53c017548b55e797.mp4)

**Reproducible:**
> 100% of the time

**Howto:**
> Cast Rune Strike before the first Rune comes off cooldown.

**Comment by BanterDK** [comment]
Closed, moved to ticket - #263
