### ISSUE TITLE
Any rune gaining ability (Blood Tap) can result in only 1-2 Runes recharging

### ISSUE THREAD

**Issue by Chewsdaydk** [SimCMinMax/WoW-BugTracker#263]
**Game Version:**
> 7.3.5 Release Build 26365
>8.0.1 Beta b26936

**Description:**
> Any effect that can gain a rune can be used to "cancel" a rune recharge. This ticket uses Blood Tap, and has been made the "main ticket" for this bug

> Using Blood Tap can cause only 2 runes to be charging with 3 runes active.

**Details:**
> Using Blood Tap before a Rune comes off cooldown will activate the Rune and result in only 2 runes charging. 

>Related bugs #261 and #262 

>E.g. If all runes are on cooldown and you use Blood Tap to generate the first Rune before it refreshes. After Rune 2 and 3 come off cooldown Rune 4 and 5 will start charging and Rune 6 will be stuck.

**Logs, Images, Videos**
>  [mp4 -- using ElvUI/Vex Runes](https://i.gyazo.com/904e5dcd5a7b5c7d532ceff85a4507fa.mp4)

>[mp4 -- Default UI ](https://i.gyazo.com/4509601ca1c4d435e11c53ab72469018.mp4)

**Reproducible:**
> 100% of the time

**Howto:**
> Cast Blood Tap before Rune 1 comes off cooldown. / Any rune gaining ability before a rune comes off cooldown

**Comment by Chewsdaydk** [comment]
Using 2 Blood Tap charges with no runes active can result in having the first 4 Runes active, the 5th Rune Recharging and the 6th Rune stuck. https://i.gyazo.com/42a4c58e9c2430dd489ec034e6e309cc.mp4

**Comment by BanterDK** [comment]
Main ticket of related/similar bugs (but using different spells)
Soul Reaper - #261 
Rune Strike - #262 

Other tickets have been closed

**Comment by Chewsdaydk** [comment]
Fixed in (27075) unable to replicate.

**Comment by BanterDK** [comment]
Was reopened because its still on live, but it's relevant for a couple of hours.

Closed

**Comment by Chewsdaydk** [comment]
Fixed (27075)
