### ISSUE TITLE
Lone Wolf multiplier after relog

### ISSUE THREAD

**Issue by nuoHep** [SimCMinMax/WoW-BugTracker#267]
**Game Version:**
> 8.0.1 Beta Build 26640

**Description:**
> Relogging with a fully ramped-up Lone Wolf makes it a 18% damage increase buff. 

**Details:**
> Lone Wolf in BfA has a maximum of 10% and a ramp-up mechanic where it increases in value from 0 to the max in around a minute. But, if you log out with it fully ramped-up and log back in you get 18% from it (the current live value) as long as you don't loose it.
> NB: The tooltip still shows 10%, but looking at ability damage it really is 18%.

**Reproducible:**
> yes

**Howto:**
> 1. wait for Lone Wolf to ramp-up to 10%
> 2. relog
> 3. ???
> 4. profit, you now have an 18% Lone Wolf

---

There is also another 'small' bug related to Lone Wolf ramp-up mechanic: in the short window after it gets applied after a respec/pet dismiss and before it ramps-up to 1% it actually gives the full 10%.

**Comment by Pewtro** [comment]
No longer the case in 9.0.1 beta Build 35482
