### ISSUE TITLE
Changing any talent drops Leeching Poison aura.

### ISSUE THREAD

**Issue by weakweak** [SimCMinMax/WoW-BugTracker#27]
**Game Version:**
> 8.0.1 Alpha Build 25976

**Description:**
> You lose Leeching Poison from your active auras upon changing any talent.

**Details:**
> Any change in your talents drops your current Leeching Poison aura.

**Reproducible:**
> 100%

**Howto:**
> Cast Leeching Poison. Change any talent. Lose Leeching Poison.

**Comment by Mystler** [comment]
Fixed in 8.0.1.26095.
