### ISSUE TITLE
Death and Decay/Defile sometimes do not apply Death and Decay cleave buff.

### ISSUE THREAD

**Issue by Chewsdaydk** [SimCMinMax/WoW-BugTracker#270]
**Game Version:**
> 8.0.1 Beta Build 26715

**Description:**
> When placing Death and Decay/Defile - sometimes the buff will not appear that allows your Scourge Strike/Clawing Shadows/Heart Strike to cleave. 

**Details:**
> Upon placing Death and Decay/Defile, the buff that allows Scourge Strike/Heart Strike/Clawing Shadows to cleave will not appear and you cannot cleave. 

Adjacently Grip of the Dead will not apply in this situation, though DnD/Defile still tick and Festering Wounds from Pestilence still apply.

**Logs, Images, Videos**
> https://www.youtube.com/watch?v=22uBx4u2YLk&feature=youtu.be

**Reproducible:**
> Very frequently. More often than normal functionality.

**Howto:**
> Acherus training dummy's, drop Death and Decay next to the 3 dummies.

**Comment by BanterDK** [comment]
Was able to hone in on its reproductibility :

Will always occur:
 - by casting DnD on lower terrain, then moving to higher terrain ([as seen here](https://i.gyazo.com/4cadaa63b64573c43e157caf4ceb83aa.gif) - Where I do not get the buff)
    - [This condition can also be fulfilled by casting DnD, then jumping (after a *slight* delay), which makes me worry about this bug's impact in dungeons](https://i.gyazo.com/ab61f452374bcc1e99c3092a00b77564.gif)
 - Replicating the bug once seems to disable the ability to acquire the buff completely.  This seems to last until the player has exited combat
    - ie, if this bug occurs in a boss fight, it will likely continue to occur for the rest of a boss fight.

Will never occur:
 - by casting DnD, then waiting for the buff to apply before moving to different level terrain/jumping
    - [Example 1 ](https://i.gyazo.com/aea6c348e4cfbdc98af5122381a22354.gif)-- Moving in/out by fulfilling the above criteria. Bug does not occur
    - [Example 2](https://i.gyazo.com/a5858e354f03167aa687f5881a6591be.gif) -- moving in and out by contradicting the above criteria. Bug occurs

**Comment by BanterDK** [comment]
Additionally, these bugs/toggles are likely kept seperate. [This explains Defile not occuring, the DnD occuring in the footage Chewie provided.](https://youtu.be/22uBx4u2YLk?t=55)

(There is a dead zone at the foot of the dummy, which has around a 1ft radius. Defile was cast within that radius, whereas DnD was cast out of it)

**Comment by Chewsdaydk** [comment]
Bug remains in new beta build (26734) - https://youtu.be/-fy38HMh6nQ

Had it work consistently for dozens of casts until logging in again later, where it started breaking again consistently.

**Comment by Chewsdaydk** [comment]
Fixed in a previous build.
