### ISSUE TITLE
Frozen Orb isn't stopping on many mobs

### ISSUE THREAD

**Issue by KuniZyrekai** [SimCMinMax/WoW-BugTracker#272]
**Game Version:**
> 8.0.1 Beta Build 26640

**Description:**
> Frozen Orb isn't stopping when impacting a mob.

**Details:**
> Throwing Frozen Orb has a high chance of it flying through everything until it hits range limit. It still deals damage and procs Chilled, it just doesn't stop. I thought it was more common on new mobs until I ran Shrine of the Storm, where it proceeded to miss on the vast majority of pulls.

**Logs, Images, Videos**
> Please attach Logs, Images, and/or a Video of the bug.

**Reproducible:**
> Yes. Run a dungeon, that seemed to be the highest percentage of misses.

**Howto:**
> Hit 6, watch screen.

**Comment by BanterDK** [comment]
Hi. Do you think you could record a video of you reproducing this bug? (Gif/mp4)

**Comment by Juliacare** [comment]
Can confirm this is the case on some of my Kingarothi pulls. I'll get back to you with logs if I can have them public for a few hours or screenshots of it occurring.

**Comment by KuniZyrekai** [comment]
Gfycat link and zipped mp4 since I can't directly attach mp4.
[2018-05-30 02-27-59.zip](https://github.com/SimCMinMax/WoW-BugTracker/files/2053305/2018-05-30.02-27-59.zip)

https://gfycat.com/FlippantScaryGyrfalcon

**Comment by Juliacare** [comment]
Two logs from current tier with a similair bug.
Maybe its useful

https://www.warcraftlogs.com/reports/vpQbWALTgrVXdmf6#fight=last&type=damage-done&source=19&start=10135548&end=10155826&ability=-84714

https://www.warcraftlogs.com/reports/vpQbWALTgrVXdmf6#fight=last&type=damage-done&source=19&start=10256155&end=10276434&ability=-84714

**Comment by vituscze** [comment]
Seems to be fixed.
