### ISSUE TITLE
[Talent] Secret Technique does not work

### ISSUE THREAD

**Issue by fuu1** [SimCMinMax/WoW-BugTracker#274]
**Game Version:**
> 8.0.1 Beta Build 26734

**Description:**
>The talent does not trigger at all.
>Does not work with Deeper Strategem, Mastery, or Relentless Strikes
>Showcase video: [link](https://cdn.discordapp.com/attachments/316923898501529600/451841601950449684/secret.mp4)

**Comment by Lorentz21** [comment]
According to tooltip and spell data talent also doesn't work with Deeper Stratagem and Mastery

**Comment by Lorentz21** [comment]
Also doesn't proc Relentless Strikes

**Comment by Lorentz21** [comment]
With talent Deeper Stratagem picked Secret Technique only consumes up to 5 combo points, even if we have 6 at the time of pressing it

**Comment by fuu1** [comment]
works with the latest build, but has a lot of bugs.
