### ISSUE TITLE
Sweeping Claws does not hit Garothi Worldbreaker

### ISSUE THREAD

**Issue by Chewsdaydk** [SimCMinMax/WoW-BugTracker#275]
**Game Version:**
> 7.3.5 Release Build (26654)

**Description:**
> Regular Ghoul pet's Sweeping Claws - Dark Transformation energy spender - does not hit Garothi Worldbreaker.

**Details:**
> Sweeping Claws does not hit Garothi Worldbreaker, yet Sludge Belcher's Vile Gas does hit.

**Logs, Images, Videos**
>  2 separate logs of the problem in practice https://www.warcraftlogs.com/reports/7vpg2hcfmxdj4YCb#fight=4&type=damage-done&source=20   https://www.warcraftlogs.com/reports/G78zWRrYkM6mDAPq/#fight=last&type=damage-done&source=46

**Reproducible:**
> Yes.

**Howto:**
> Spec anything except Sludge Belcher and log damage, on Garothi Worldbreaker.

**Comment by BanterDK** [comment]
rip Sludge Belcher
