### ISSUE TITLE
[talent] Master of the Elements no longer affects Earthquake

### ISSUE THREAD

**Issue by Bloodmallet** [SimCMinMax/WoW-BugTracker#279]
**Game Version:**
> 8.0.1 Beta Build 26788

**Description:**
> Master of the Elements no longer buffs Earthquake and is no longer consumed by it.

**Details:**
> This behavior seems to be a bug because both other talents in that row (Aftershock and Totem Mastery) affect AoE quite significantly. Master of the Elements now only affects Chain Lightning, which is the weaker of our AoE spells.

**Reproducible:**
> yes
**Howto:**
> Take Master of the Elements and cast Earthquake while having the Master of the Elements buff.

**Discovered by**
> shakira - Earthshrine Discord

**Comment by BanterDK** [comment]
Tooltip has been updated. Now reads:
```
Casting Lava Burst increases the damage of your next Nature or Frost spell by 20%.

```
As of 26812, this interaction is working as intended

**Comment by Bloodmallet** [comment]
At its core Earthquake is a nature spell. It states to deal physical damage, but it's locked out when Lightning Bolt is kicked, adding it to the nature departement.
