### ISSUE TITLE
Partial ticks on bleeds grant full effect from [Venomous Wounds]

### ISSUE THREAD

**Issue by weakweak** [SimCMinMax/WoW-BugTracker#28]
**Game Version:**
> 8.0.1 Alpha Build 25976

**Description:**
> Possibly more regen than intented?

**Details:**
> Partial ticks from bleeds such as garrote and rupture grant you the full effect of [Venomous Wounds].
https://www.warcraftlogs.com/reports/BvLxqj2tGz7fTVJ1/#fight=last&type=resources&pins=0%24Separate%24%23244F4B%24damage%240%240.0.0.Any%246326793.0.0.Rogue%24true%240.0.0.Any%24false%24703%5E0%24Separate%24%23909049%24auras-gained%241%240.0.0.Any%240.0.0.Any%24true%240.0.0.Any%24false%24703&spell=103&view=events

**Reproducible:**
> 100%

**Howto:**
> Cast garrote once and see the final partial tick grant full energy just like all other ticks.

**Comment by Mystler** [comment]
I don't think this is a bug or unintended.
