### ISSUE TITLE
Whiteout CDR and Frozen Orb cd visual

### ISSUE THREAD

**Issue by Juliacare** [SimCMinMax/WoW-BugTracker#286]
**Game Version:**
> 8.0.1 Beta Build 26788

**Description:**
> What is your bug about?

Azerite trait "Whiteout" for frost mage

**Details:**
> Try to explain the bug.

The trait should give 0,5sec cooldown reduction to Frozen Orbs cooldown for each icelance used. It however gives a notable second less over 30 icelances used and the actual cooldown timer resets on each cast.

for the first log:
I cast frozen orb on cd, the CD was reduced from 60 to 45,622
Casted 32 icelances inbetween which is 32 * 0,5 = 16 seconds cdr
60 - 16 = 44 seconds
1,622 seconds difference

for the second:
orb cd to 45,371 seconds
31 icelances = 15,5 cdr
which should be 44,5 seconds orb cd

and the twitch clip shows the strange way of resetting the cooldown on the bars. (Look at Frozen Orb)

**Logs, Images, Videos**
> Please attach Logs, Images, and/or a Video of the bug.
https://www.warcraftlogs.com/reports/v8h3T1BwVncPLDxb/#fight=1&type=casts&source=35
https://www.warcraftlogs.com/reports/cJQnbt6h8V4Dagy9/#fight=1&type=casts&source=33&start=6174&end=52837
https://www.warcraftlogs.com/reports/cJQnbt6h8V4Dagy9/#fight=1&type=casts&source=33&start=6174&end=52837
https://clips.twitch.tv/HealthyArborealMouseHumbleLife

**Reproducible:**
> Examples: yes/rarely
yes

**Howto:**
> How do you reproduce it (if you know).

You equip the trait and press icelance whilst frozen orb is on cooldown.

**Comment by vituscze** [comment]
Just double checked on beta, the cooldown reduction is exactly on point. Feel free to report the visual bug separately.
