### ISSUE TITLE
Glacial Advance doesn't trigger Razorice properly if it is not runeforged.

### ISSUE THREAD

**Issue by Melekus** [SimCMinMax/WoW-BugTracker#288]
**Game Version:**
> 8.0.1 Beta Build 26812

**Description:**
> The Razorice debuff drops almost instantly if you don't have a weapon runeforged with Razorice equipped.

**Details:**
> This isn't an issue in normal gameplay where you would have one weapon with Fallen Crusader, and one with Razorice. But if you cast Glacial Advance without having Razorice runeforged on any of your weapons, the razorice debuff will be applied but it will only stay on the target for a very short duration ( around one second ) before disappearing.

**Logs:**
>https://www.warcraftlogs.com/reports/WwQ37YVKcqrRPT9L/#fight=last&type=auras&pins=0%24Separate%24%23244F4B%24casts%240%240.0.0.Any%241240854.0.0.DeathKnight%24true%240.0.0.Any%24false%24194913&spells=debuffs&view=events&hostility=1&target=3&ability=51714

**Reproducible:**
> Yes.

**Howto:**
> Use Glacial Advance while having no weapon runeforged with Razorice

**Comment by BanterDK** [comment]
Cannot reproduce this bug in b26936 (beta). 

PTR is untested, but if its possible it will likely be fixed as well
