### ISSUE TITLE
Horn of Winter can result in only 1 Rune recharging.

### ISSUE THREAD

**Issue by Chewsdaydk** [SimCMinMax/WoW-BugTracker#289]
**Game Version:**
> 8.0.1 Beta Build 26871

**Description:**
> Using Horn of Winter can cause runes to charge incorrectly, with only 1 charging.

**Details:**
> Using Horn of Winter can cause runes to charge incorrectly, where the last Rune will freeze until all other runes have recharged.
> Likely related to these very similar bugs #261  #262  #263  

**Logs, Images, Videos**
> Gif of it with my elvui/Vex Runes - https://i.gyazo.com/696cc7cf7a789ca54cfe89fd3fa4b98f.mp4
> Gif of it with default UI - https://i.gyazo.com/9521ce1e21aec06425c5385391921a25.mp4

**Reproducible:**
> Yes

**Howto:**
> Spec Horn of Winter, spend runes and activate before the first rune recharges.

**Comment by Chewsdaydk** [comment]
Bug also affecting Murderous Efficiency (only spending runes) - don't have legendary belt equipped. 
>https://i.gyazo.com/bfe56e1a8516eea76019467d6ff462d9.mp4

**Comment by BanterDK** [comment]
Closed, moved to ticket - #263
