### ISSUE TITLE
[talent] Exposed Elements stays as a hidden buff to all Overloads if no second Lightning Bolt is cast

### ISSUE THREAD

**Issue by HawkCorrigan** [SimCMinMax/WoW-BugTracker#290]
**Game Version:**
> 8.0.1 Beta Build 26877

**Description:**
> Exposed Elements (talent) debuff is consumed by casting one Lightning Bolt at the target with the debuff. If the player doesn't cast a second Lightning Bolt, all later occuring Overloads are affected by the 100% damage increase.

**Details:**
> For this example we cast Earth Shock -> Lightning Bolt -> Icefury.
> After accounting for Overload damage being 85% of the original cast, the spell deals more damage than expected. Icefury Overload is expected to do `0.85*698=593.3` damage. Instead it deals 1187 damage, which is exactly doubled. (=>`593.3*2=1186.6`).
> On consumption of Exposed Elements the player seems to get a hidden buff without duration or a very long one, that would be consumed by the next Lightning Bolt. As long as this hidden buff is present (so..as long as no second Lightning Bolt is cast or combat drops) all Overloads from all casts benefit from the 100% damage boost.

**Logs, Images, Videos**
> ![icefury](https://user-images.githubusercontent.com/2129161/41676656-8372d46a-74c6-11e8-9088-08340f6170ef.png)
> ![lvb](https://user-images.githubusercontent.com/2129161/41677957-0d206e18-74ca-11e8-971b-df37ebbc7097.png)
> ![lvb2](https://user-images.githubusercontent.com/2129161/41678360-2d2ba712-74cb-11e8-96a8-234cfedefab3.png)

**Reproducible:**
> 100% reproducible

**Howto:**
> Take Exposed Elements (talent), get 60 Maelstrom. Cast Earth Shock -> Lightning Bolt -> Lava Burst -> Icefury -> Chain Lightning. Spam Chain Lightning. All Overloads after Lightning Bolt are buffed by 100%.

**Comment by Bloodmallet** [comment]
I'm going to edit some more information and clarifications into the first post.

**Comment by Bloodmallet** [comment]
Fixed 8.0.1.26936
