### ISSUE TITLE
Blizzard has a base damage value

### ISSUE THREAD

**Issue by KuniZyrekai** [SimCMinMax/WoW-BugTracker#298]
**Game Version:**
> 8.0.1 Beta Build 26936

**Description:**
> Blizzard seems to have a base damage value set, in addition to a coefficient. 

**Details:**
> Blizzard is currently set to 13% SP/tick+a scaled value of 100 at level 120. The below screenshot for the stats given should state 812 damage. Instead it seems to be adding 65.246/tick, before the spec damage reduction aura, at level 116.

**Logs, Images, Videos**
> Please attach Logs, Images, and/or a Video of the bug.
![image](https://user-images.githubusercontent.com/37755674/42004887-c062a67e-7a26-11e8-82a4-757d4d3e6e4d.png)

**Reproducible:**
> Yes

**Howto:**
> Check Blizzard's damage.

**Comment by vituscze** [comment]
Fixed.
