### ISSUE TITLE
Aftershock causes Maelstrom spenders cast at 100 Maelstrom to disable Maelstrom generation until combat ends

### ISSUE THREAD

**Issue by kpey** [SimCMinMax/WoW-BugTracker#300]
**Game Version:**
> 8.0.1 Beta Build 26936

**Description:**
> The Elemental talent Aftershock gives a 25% chance to refund Maelstrom spent on Earth Shock and Earthquake. As of build 26936, casting either of these spells at 100 Maelstrom and getting an Aftershock proc refund is bugged. The Maelstrom refund is not reflected in the interface, despite the energize event seemingly triggering (see log). However, this is not just a visual bug, as casting of Earth Shock and Earthquake is disallowed since the UI displays 40 Maelstrom despite the shaman being at 100 Maelstrom (thanks to the refund).

**Details:**
> Current, bugged flow:
    - Cast Earth Shock at 100 Maelstrom
    - Trigger an Aftershock energize event
    - UI displays 40 Maelstrom, the expected value if Aftershock did not trigger. If Aftershock is triggered, Maelstrom should be at 100.
    - Cast Lightning Bolt
    - Maelstrom is not generated despite the visual 40, possibly due to the fact that Maelstrom is maxed at 100 internally.
    - Earth Shock stays illuminated despite being uncastable
    
> This issue is resolved by exiting combat, which will cause the UI to display the intended 100 Maelstrom. 

**Logs, Images, Videos**
> Video: https://youtu.be/dFfDbX9-bOE Time stamps 0:07 and 1:10
> Screenshot: http://puu.sh/ANeBI/372aa698a4.jpg
> Log, which does not reflect this as the energize event is triggered, indicating a UI issue: https://www.warcraftlogs.com/reports/QcZraRY3LJBGFjy1/#fight=4&type=resources&source=4&start=661731&end=691745&pins=0%24Main%24%239c7738%24casts%240%240.0.0.Any%241929086.0.0.Shaman%24true%240.0.0.Any%24false%248042%5E0%24Main%24%2355c4e6%24casts%240%240.0.0.Any%241929086.0.0.Shaman%24true%240.0.0.Any%24false%24-188196&spell=111

**Reproducible:**
> With ease

**Howto:**
> See bugged flow in Details section for steps to reproduce

**Comment by kpey** [comment]
I'm unable to assign labels, so if someone (@Bloodmallet) could add Shaman Elemental that'd be great.

**Comment by Bloodmallet** [comment]
Adding the following ingame combat log screenshot. As you can see I was Maelstrom capped (Chain Lightning Overloads overenergized me), casted Earth Shock, Aftershock triggered and refunded 60 MS. Next Chain Lightning stated to to overenergize but casting Earth Shock returned "Not enough maelstrom".

![image](https://user-images.githubusercontent.com/9075987/42041841-184a1ecc-7af3-11e8-8656-5833aa0038b5.png)

**Comment by Bloodmallet** [comment]
Fixed in 8.0.1.26970
