### ISSUE TITLE
Rumbling Tremors azerite trait applies Earth Elemental attack damage bonus to all friendly units within 40 yards

### ISSUE THREAD

**Issue by kpey** [SimCMinMax/WoW-BugTracker#301]
**Game Version:**
> 8.0.1 Beta Build 26936

**Description:**
> The [Rumbling Tremors](http://bfa.wowhead.com/spell=279522/rumbling-tremors) azerite trait currently gives an attack damage buff to all friendly units within range despite the tooltip clearly indicating the buff is meant only for the Earth Elemental itself.

**Details:**
> Obtain the Rumbling Tremors trait, cast Earth Elemental (with or without Primal Elementalist) and view the Rumbling Tremors buff on allies. Note the "refresh" event appears to occur instantly with the application.

**Logs, Images, Videos**
> Screenshot:
![](https://puu.sh/ANiH0/033b6c5674.jpg)

**Reproducible:**
> Very easily

**Howto:**
> See Details

**Comment by Bloodmallet** [comment]
Azerite trait was removed
