### ISSUE TITLE
ShadowStrike does not teleport. 

### ISSUE THREAD

**Issue by Scathic** [SimCMinMax/WoW-BugTracker#308]
**Game Version:**
> 8.0.1 Beta Build 26970

**Description:**
> The Teleportation part of SS seems broken. 

**Details:**
> ShadowStrike does the damage still with an extended range but does not teleport you to the target. 

**Logs, Images, Videos**
> Please attach Logs, Images, and/or a Video of the bug.

**Reproducible:**
> Yes

**Howto:**
> Use Shadowstrike

**Comment by Mystler** [comment]
Closing this in favor of #309.
