### ISSUE TITLE
4p T21 prevents combo point generation.

### ISSUE THREAD

**Issue by RosvallM** [SimCMinMax/WoW-BugTracker#321]
**Game Version:**
8.0.1pre build 27101 

**Description:**
Not generating combo points

**Details:**
Currently the 4-Piece Tier 21 set bonus where you have a chance on backstab to refund combo points is broken.
Instead it currently prohibits you from gaining combo points until you leave combat.

**Logs, Images, Videos**
Buff: Shadow Gestures (SpellID 252732)

**Reproducible:**
Always

**Howto:**
Be in combat. Backstab until you proc the tier buff and you will be unable to generate combo points until you leave the fight.

**Comment by Mystler** [comment]
Seems to be fixed now.
