### ISSUE TITLE
Dancing Rune Weapon copies Rune Strike

### ISSUE THREAD

**Issue by Melekus** [SimCMinMax/WoW-BugTracker#323]
**Game Version:**
> 8.0.1 Beta Build 27144

**Description:**
> Dancing Rune Weapon can cast Rune Strike

**Details:**
> Similarly to https://github.com/SimCMinMax/WoW-BugTracker/issues/240 the Rune Strike talent spell is correctly mirrored by Dancing Rune Weapon even though it has a history of not being affected by talents.

**Reproducible:**
> Yes

**Howto:**
> Cast Dancing Rune Weapon followed by Rune Strike

**Comment by Chewsdaydk** [comment]
In SL Alpha talented rune strike is gone, currently Rune Strike is a low level class single rune spender that is replaced with a spec spell before Dancing Rune Weapon is unlocked for Blood,
