### ISSUE TITLE
Incanter's Flow (talent) falls off in combat

### ISSUE THREAD

**Issue by vituscze** [SimCMinMax/WoW-BugTracker#328]
**Game Version:**
> 8.0.1 Build 27178

**Description:**
> The buff given by Incanter's Flow randomly expires even when in combat.

**Details:**
> There doesn't seem to be any patterns to when this buff falls off. Once it's gone, it takes roughly one second before it's applied again (usually starting with only one or two stacks).

**Reproducible:**
> yes

**Howto:**
> Talent into Incanter's Flow and engage combat. The buff will randomly fall off.

**Comment by KuniZyrekai** [comment]
https://giant.gfycat.com/PowerfulDecisiveArchaeopteryx.webm

First happens about 30 seconds in, happens again right before the end.

**Comment by vituscze** [comment]
Looks like the most common buff stack pattern is this:

    0,2,3,4,5,5,4,3,2,1,1,2,3,4,5,5,4,3,2,1,1,2,3,4,5,5,repeat

Each number represent the stack count for a given second.

**Comment by vituscze** [comment]
Seems to be fixed.
