### ISSUE TITLE
Remorseless Winter double dips haste on GCD calculation

### ISSUE THREAD

**Issue by jjs451** [SimCMinMax/WoW-BugTracker#334]
**Game Version:**
> 8.0.1 Beta Build 26970

**Description:**
> Remorseless Winter (Frost DK ability) double dips with haste when calculating its GCD.  

**Details:**
> Instead of the normal formula, `1.5/(1+haste%)`, it uses the formula `(1.5/(1+haste%))/(1+haste%)`

**Logs, Images, Videos**

> https://cdn.discordapp.com/attachments/468834365791797319/474378282264166400/unknown.png
> 
> With 15.86% haste:
> 
> Normal GCD = 1.5 / 1.1586 = 1.294 (seconds)
> RW GCD = 1.5 / 1.1586 / 1.1586 = 1.116 (seconds)

**Reproducible:**
> yes

**Howto:**

> In game, run the following to see the GCD of each cast: `/run GCDE=GCDE or CreateFrame('FRAME', 'GCDE');GCDE:RegisterEvent('UNIT_SPELLCAST_SUCCEEDED');GCDE:SetScript('OnEvent', function (_,_,_,_,id) print(select(1,GetSpellInfo(id))..":",(select(2,GetSpellCooldown(id)))*1000);end);`.  With some amount of haste, cast abilities with known GCDs, then cast RW and compare the results.

**Comment by Melekus** [comment]
Fixed
