### ISSUE TITLE
Honorbound Scouting Report Flight Masters

### ISSUE THREAD

**Issue by bitfluxhound** [SimCMinMax/WoW-BugTracker#346]
**Game Version:**
> 8.0.1 Beta Build 26970

**Description:**
Honorbound reputation quest hub unlocks.

**Details:**
You are unable to select the new unlocked zones as the end points of flight path, but still able to fly from them.

**Logs, Images, Videos**
![wow_2018-08-16_17-01-46](https://user-images.githubusercontent.com/6678789/44235684-5c362580-a178-11e8-9f98-9e55f2f2e1f2.png)
![wow_2018-08-16_16-14-26](https://user-images.githubusercontent.com/6678789/44235686-5e987f80-a178-11e8-90bf-9c16dbdabb8b.png)

**Reproducible:**
100%

**Comment by vituscze** [comment]
Same issue with the 7th Legion ones.

**Comment by Loktark** [comment]
It's unlikely that this is a bug as you can fly to them after completing the upgrade mission and the associated quests.

**Comment by vituscze** [comment]
Seems to be fixed.
