### ISSUE TITLE
Resilient Spellthread does not prevent daze

### ISSUE THREAD

**Issue by ChadLevy** [SimCMinMax/WoW-BugTracker#350]
**Game Version:**
> 8.0.1 build 27404

**Description:**
> The tooltip for Resilient spellthread indicates that the spellthread prevents being dazed while in Kul Tiras or Zandalar. The daze-prevention effect does not appear to be working.

**Logs, Images, Videos**
> ![image](https://user-images.githubusercontent.com/909190/44475556-f70c8500-a5fa-11e8-83e3-3caf14ff1467.png)

**Reproducible:**
> Yes

**Howto:**
> 1. Apply Resilient Spellthread to cloak
> 2. Run through a pack of similar level mobs while mounted. Observe you will likely be dazed and dismounted.

**Comment by AlexanderKenny** [comment]
Tooltip changed to only prevent daze while running/walking. Should retest without a mount and close if needed.

**Comment by ChadLevy** [comment]
Tested by doing roughly 20 world quests without the cloak enhancement or using absorbs like Power Word: Shield. I was dazed 0 times.
