### ISSUE TITLE
Arcane Mage Displacement only applied to one mage when multiple are in a group/raid.

### ISSUE THREAD

**Issue by Razlopp** [SimCMinMax/WoW-BugTracker#354]
**Game Version:**
> 8.0.1 Live 27481

**Description:**
> When multiple arcane mages are in a group/raid only one is given displacement after using blink.

**Details:**
> Example: When 3 arcane mages are in a group the first one to blink will gain displacement, while this mage has the displacement buff the other arcane mages will not gain displacement after they blink.

**Logs, Images, Videos**
> N/A

**Reproducible:**
> Yes, happened everytime we tested within a dungeon.

**Howto:**
> Have multiple arcane mages in a group or dungeon.  Have one mage blink gaining displacement, the following mages will not gain the displacement buff while he/she has it active on them.

**Comment by vituscze** [comment]
Should be fixed now.
