### ISSUE TITLE
Critters Drop Rich Azerite

### ISSUE THREAD

**Issue by AlexanderKenny** [SimCMinMax/WoW-BugTracker#36]
**Game Version:**
> 8.0.1 Alpha Build 25976

**Description:**
> Rich Azerite drops from critters when pvp flagged

**Details:**
> No additional description needed

**Reproducible:**
> 100%

**Howto:**
> Enable /pvp, kill any critter

**Comment by RosvallM** [comment]
Not only critters. Regular red named mobs as well.

**Comment by AlexanderKenny** [comment]
I believe that portion is intentional. The system appears to be similar to something like Operation Murloc Freedom with the collected items coming from mob kills and the like and the PvP portion reduces your collected amount upon death.

**Comment by Kutikuti** [comment]
Fixed in 26141
