### ISSUE TITLE
Subtlety rogue trait Replicating Shadows acts inconsistently

### ISSUE THREAD

**Issue by weakweak** [SimCMinMax/WoW-BugTracker#366]
**Game Version:**
> 8.1.0 PTR Build 27934

**Description:**
> Sub rogue trait Replicating Shadows behaving very oddly and inconsistently.

**Details:**
> Instant damage proc sometimes occurs on more than one target
> Newly applied Nightblade duration from the proc varies in duration
> Something seems to cause a rare full CP refund upon Nightblade application
> Sometimes a trait proc procs Relentless Strikes more than once
> Sometimes refreshes old Nightblades at varying increases in duration
> Sometimes applies two Nightblades on first cast

**Logs, Images, Videos**
> Most issues appear here: https://www.warcraftlogs.com/reports/3cfDQHhydrVgv4ax/#fight=last&type=casts&source=6&pins=0%24Separate%24%23244F4B%24casts%240%240.0.0.Any%24763069.0.0.Rogue%24true%240.0.0.Any%24false%24195452%5E0%24Separate%24%23909049%24damage%240%240.0.0.Any%24763069.0.0.Rogue%24true%240.0.0.Any%24false%24286131%5E0%24Separate%24%23a04D8A%24damage%240%240.0.0.Any%24763069.0.0.Rogue%24true%240.0.0.Any%24false%24195452&view=events

> Here is the specific occasion you regen your combo points fully:
https://www.warcraftlogs.com/reports/N1jrZKpHw2CghPaV/#fight=last&type=resources&source=6&pins=0%24Separate%24%23244F4B%24casts%240%240.0.0.Any%24763069.0.0.Rogue%24true%240.0.0.Any%24false%24212743%5E0%24Separate%24%23909049%24casts%240%240.0.0.Any%24763069.0.0.Rogue%24true%240.0.0.Any%24false%24195452%5E0%24Separate%24%23a04D8A%24casts%240%240.0.0.Any%24763069.0.0.Rogue%24true%240.0.0.Any%24false%24196819&spell=104&view=events&start=783832&end=798522

This feels like it has a few conditions. You have to have DS and have the "extra" 6th combo point proc something. And you have to apply Nightblade to a target without one, and get a proc of applying a second full length Nightblade.

**Reproducible:**
> Some are 100% some seem rare and wonky. 

**Howto:**
> Find 10-20 targets close to each other and start applying Nightblades. Observe how certain conditions such as targets without Nightblade applied to them affect how the trait works.

**Comment by Mystler** [comment]
Closing this as wontfix. Replicating Shadows doesn't work at all on beta anymore anyway.
