### ISSUE TITLE
Bloodseeker will randomly stop working

### ISSUE THREAD

**Issue by Pewtro** [SimCMinMax/WoW-BugTracker#376]
**Game Version:**
> 8.0.1 Live Build 27843
> 8.1.0 PTR Build 27934

**Description:**
> What is your bug about?

The talent Bloodseeker. 

**Details:**
> Try to explain the bug.

It'll randomly completely stop working. 
The only known fix is to talent out of it and back into it. 

**Reproducible:**
> Examples: yes/rarely

Yes, but happens at random.

**Howto:**
> How do you reproduce it (if you know).

Be in combat and play like you normally would with Bloodseeker and use this WA to track when it stops working: https://wago.io/ryQaLq7IX

**Comment by Pewtro** [comment]
@Jundarer This one is Survival, not Beast Mastery 😅

**Comment by Jundarer** [comment]
Whoops fixed :stuck_out_tongue:

**Comment by Thyminde** [comment]
Perhaps worth noting i haven't personally ever had this happen since both beta, and prepatch.

**Comment by Pewtro** [comment]
I'll close it for now, and hope it is indeed fixed. Will reopen when it resurfaces itself 😄
