### ISSUE TITLE
Barrage have no animation

### ISSUE THREAD

**Issue by watcheur** [SimCMinMax/WoW-BugTracker#380]
**Game Version:**
> 8.1.0 Live Build 28724

**Description:**

**Details:**
> Barrage have no animations

**Logs, Images, Videos**
https://i.gyazo.com/80bcd9fe7389fa521985f37b871ccc57.mp4

**Reproducible:**
> Yes

**Howto:**
> Cast barrage

**Comment by Pewtro** [comment]
Has since been fixed.
