### ISSUE TITLE
Trait "Quick Thinking" inconsistencies

### ISSUE THREAD

**Issue by Lorentz21** [SimCMinMax/WoW-BugTracker#384]
**Game Version:**
> 8.0.1 Live Build 27843

**Description:**
> New trait Quick Thinking either doesn't proc or procs too many times for some spells

**Details:**
> Frost:
>> Frozen Orb: doesn't proc the trait with or without Honor Talent "Concentrated Coolness"
>> Blizzard: doesn't proc with talent Freezing Rain buff active

> Fire:
>> Blast Wave: procs one time for cast plus number of targets hit
>> Phoenix Flames: procs once on cast and once on impact
>> Living Bomb: procs twice on cast( cast + application presumably ) and then once for each target it spreads to

**Reproducible:**
> yes

**Howto:**
> Have item with trait active, cast spells listed above and count number of trait procs

**Comment by vituscze** [comment]
Looks like this was just hotifxed on live. Closing.
