### ISSUE TITLE
Lady and the Child benefits from Galactic Guardian

### ISSUE THREAD

**Issue by FaideWW** [SimCMinMax/WoW-BugTracker#39]
**Game Version:**
> 7.3.5 Live Build 25961

**Description:**
> When in combat with two or more mobs with Lady and the Child equipped and Galactic Guardian talented, if you receive a Galactic Guardian proc when you already have one active, the copied Moonfire from Lady and the Child acts benefits from the effects of Galactic Guardian but does not consume the buff.

**Details:**
> Galactic Guardian grants a chance on casting Mangle, Thrash, Swipe, and Maul, to auto-cast a Moonfire on the target and trigger the "Galactic Guardian" buff.  If you cast Moonfire while under the effects of Galactic Guardian, the direct damage of that Moonfire will be increased by 300% and you will gain 8 rage.
> 
> Lady and the Child has two effects, but the relevant one is that each time Moonfire is cast, if a secondary target is present a second Moonfire will be cast on that target.  Naturally, if Galactic Guardian procs and you have LatC equipped, you will have two auto-cast Moonfires.  
> 
> If you have an existing GG proc and GG procs again, the secondary Moonfire will deal 300% increased damage and generate 8 rage as if it were manually cast.  The GG proc will persist and you can then manually cast Moonfire to gain another 8 rage your primary Moonfire will deal 300% increased damage.
>
>[WarcraftLogs example](https://www.warcraftlogs.com/reports/CgYAc8yrphtK4mVw#fight=13&type=resources&source=10&pins=0%24Main%24%23244F4B%24resources%240%2478108014.0.0.Druid%240.0.0.Any%24true%240.0.0.Any%24false%248921%24101%5E0%24Off%24%23909049%24auras-gained%240%240.0.0.Any%240.0.0.Any%24true%2478108014.0.0.Druid%24false%24213708%5E0%24Main%24%23a04D8A%24casts%240%240.0.0.Any%2478108014.0.0.Druid%24true%240.0.0.Any%24false%248921&view=events&start=3693992&end=3704704) - Two separate instances of the bug occurring back to back. You can see that there is a rage gain event from Moonfire from the GG buff refreshing, and then a second gain event from Moonfire being cast.

**Reproducible:**
> Yes

**Howto:**
> Enter combat with two or more mobs with LatC equipped (Target dummies will not work, due to another outstanding bug with LatC where moonfires will not cleave onto them). Cast Swipe until you receive a GG proc, and then continue to press Swipe until you receive a second GG proc while the first one is still active. The second time GG procs you will gain 8 rage and the copied Moonfire will deal significantly more damage.

**Comment by Jundarer** [comment]
old
