### ISSUE TITLE
[Magus of the Dead] melee's targets 

### ISSUE THREAD

**Issue by Chewsdaydk** [SimCMinMax/WoW-BugTracker#391]
**Game Version:**
> 8.1.0 Live Build 28833
> 8.1.0 PTR Build 28833

**Description:**
> Magus from Magus of the Dead will melee targets on top of casting Frostbolt and Shadow Bolt.

**Details:**
> Magus from Magus of the Dead will melee targets on top of casting Frostbolt and Shadow Bolt. If it's not in melee range when it spawns it will move itself into melee range after a couple of casts (possibly related to cast delay bug from #385 

>The melee swings have no effect on the casts and happen while it's in the middle of casting.

**Logs, Images, Videos**
> https://images-ext-1.discordapp.net/external/Xp-hefOtPGUkM2VVDo-ltSjLWAXNYLyH3Uc8VeXorHY/https/cdn.discordapp.com/attachments/355772720857874443/528259650026733569/unknown.png

>https://media.discordapp.net/attachments/405268157440458753/528325985888632842/unknown.png?width=359&height=499

**Reproducible:**
> Yes

**Howto:**
> With Magus of the Dead azerite trait - cast Army of the Dead or Apocalypse and log/observe the Magus.

**Comment by Melekus** [comment]
Log link from which the screenshots were taken: https://www.warcraftlogs.com/reports/BTmtarc7jhA1CzbM#fight=1&source=40.3&type=summary&view=events

**Comment by Chewsdaydk** [comment]
contrary to 8.1.5 patch notes, this bug still exists

**Comment by Chewsdaydk** [comment]
Fixed as of 27/03
