### ISSUE TITLE
Multiple spells have their global cooldown reduced by haste twice.

### ISSUE THREAD

**Issue by Chewsdaydk** [SimCMinMax/WoW-BugTracker#395]
**Game Version:**
> 8.1.0 Live Build 29297

**Description:**
> Bonestorm double dips haste when calculating gcd reduction.

**Details:**
> With 8.76% haste GCD reduction on bonestorm should take it to ~1.379 seconds. It reduces it to 1.268.
>(1.5/(1+8.76%) = 1.379
>(1.5/(1+8.76%))/(1+8.76%) = 1.268

**Logs, Images, Videos**
> ![image](https://user-images.githubusercontent.com/39236684/52567805-0c71a780-2e05-11e9-8547-6a2109b0a546.png)

**Reproducible:**
> yes

**Howto:**
>log or use this macro in game, compare gcd vs haste and see if it's correct reduction 
>
![image](https://user-images.githubusercontent.com/39236684/54792993-5b96cd80-4c38-11e9-8afa-a4444d3e35da.png)

**Comment by Melekus** [comment]
This bug also affects Retribution Paladin's Wake of Ashes and Protection Paladin's Light of the Protector and Hand of the Protector

**Comment by Chewsdaydk** [comment]
Bonestorm is fixed, bug still affecting Wake of Ashes, Light of the Protector and Hand of the Protector.

**Comment by Chewsdaydk** [comment]
All spells in this issue are fixed as of march 26th hotfixes
