### ISSUE TITLE
Demonlogy Warlock: Action after Tyrant

### ISSUE THREAD

**Issue by Tamashi** [SimCMinMax/WoW-BugTracker#399]
**Game Version:**
> 8.1.0 Live Build 28833
> 8.1.0 PTR Build 28833

**Description:**
> What is your bug about?
Demonology Warlock. It shows you to summon the Tyrant, but does not show you what to cast next until the Tyrant is already summoned. If 5 soulshards it should be Hand of Guldan, if lower than 5 Shards, Shadowbolt. It does show correctly what to cast, but only once the cast of the Tyrant is finished, which makes you need to track your soulshards manually to predict the next spell. It would be great if while casting the tyrant, HeroRotations would already show the next action rather than having to finish the cast to find out.

**Comment by AlexanderKenny** [comment]
This is not the hero rotation GitHub you want over here https://github.com/herotc/hero-rotation/issues
