### ISSUE TITLE
[Death Knight] Death Gate leads to the Broken Isles

### ISSUE THREAD

**Issue by Melekus** [SimCMinMax/WoW-BugTracker#4]
**Game Version:**
> 8.0.1 Alpha Build 25976

**Description:**
> The Death Gate Death Knight spell currently teleports to the version of Acherus above the Broken Isles

**Reproduce rate:**
> 100%

**Details:**
> I assume this is a bug since Monks can teleport to the old Peak of Serenity and Druids to Moonglade. This logic would have death knights teleport to Acherus above the Eastern Plaguelands rather than above the Broken Isles. Unless there are plans to move Acherus above Zandalar / Kul'Tiras.

**Howto:**
> Cast Death Gate, click on the gate

**Comment by BanterDK** [comment]
Safe to assume this is intentional
