### ISSUE TITLE
Shadow Vault Rank 2 deals static shadow damage

### ISSUE THREAD

**Issue by Mystler** [SimCMinMax/WoW-BugTracker#423]
**Game Version:**
> 9.0.1 beta Build 34324

**Description:**
> Shadow damage from Vault rank 2 is a simple static AP-based damage ability. No combo points scaling or base physical damage involved, which is not what the main spell tooltip says.

**Details:**
> The shadow damage part from vault rank 2 (which reads just like it is on Eviscerate rank 2) is not at all working as worded (i.e. 50% as additional Shadow damage). The shadow dmg part only triggers with FW up (which is correct) and after the physical dmg part (also correct) but the damage is a simple AP-based damage spell (id 319190). The AP mod of 0.243 in the spell matches. Vault shadow damage is thus always the same value, no matter what number of CP were used for the physical part. (RI)
This could actually be a wording discrepancy. Looking at the spell data for SV rank 2, it says “Shadow Vault now deals additional Shadow damage to targets affected by your Find Weakness.” - This is true and what it does, it just does not match the main tooltip that copies the Eviscerate effect.

**Reproducible:**
> yes

**Howto:**
> Use Vault at various numbers of CP and notice the shadow damage when Find Weakness is up is always the same value (or a crit thereof).

**Comment by EvanMichaels** [comment]
Fixed in latest build
