### ISSUE TITLE
Improved Poisons rank 2 not working

### ISSUE THREAD

**Issue by Mystler** [SimCMinMax/WoW-BugTracker#426]
**Game Version:**
> 9.0.2 beta Build 36949

**Description:**
> Improved Poisons Rank 2 is supposed give you a 100% chance to apply poisons from Stealth. This does not appear to be working and there is no spell assigned to the effect in spell data.

**Reproducible:**
> yes

**Howto:**
> Use Ambush at a no-AA angle from Stealth with this effect unlocked. Poison proc is not guaranteed.

**Comment by EvanMichaels** [comment]
Still happening in 9.0.2

**Comment by Mystler** [comment]
Still the case in 36512.

**Comment by Mystler** [comment]
Still not working. There is no target spell assigned to the effect in Improved Poisons rank 2.

**Comment by EvanMichaels** [comment]
Fixed on PTR
