### ISSUE TITLE
Unholy Blight doesn't increase the damage of Magus of the Dead, Army of the Dead, Gargoyle or Val'kyr

### ISSUE THREAD

**Issue by Chewsdaydk** [SimCMinMax/WoW-BugTracker#439]
**Game Version:**
> 9.0.1 beta Build 34324

**Description:**
> Unholy Blight has a 5% mod to pet damage, stacking up to a 20% mod, tooltip implies this should affect all minions but it only affects the regular and the transformed Ghoul

**Howto:**
> Check damage of the pets without and with Unholy Blight and see if it increases at all

**Comment by BanterDK** [comment]
Possibly not a bug, as the mentioned minions are technically "Guardians", and not the players pet (ie the NPC with a pet bar).

**Comment by Chewsdaydk** [comment]
fixed
