### ISSUE TITLE
Howling Blast automatically pandemics Frost Fever sometimes

### ISSUE THREAD

**Issue by Chewsdaydk** [SimCMinMax/WoW-BugTracker#444]
**Game Version:**
> 9.0.1 beta Build 34324

**Description:**
> Casting Howling Blast applies Frost Fever 24 second DoT, but it often will instantly apply 30% duration pandemic on initial cast

**Logs, Images, Videos**
> https://i.gyazo.com/35df10017475916524203df11420ab26.mp4

**Comment by BanterDK** [comment]
To clarify, "pandemic" is a nickname for the 30% duration feature that DoT's have in the game, and not a spell

**Comment by Chewsdaydk** [comment]
fixed
