### ISSUE TITLE
Hypothermic Presence buff doesn't do anything

### ISSUE THREAD

**Issue by Chewsdaydk** [SimCMinMax/WoW-BugTracker#447]
**Game Version:**
> 9.0.1 beta Build 34324

**Description:**
> Hypothermic Presence should reduce cost of Runic Power spenders, but it allows things such as casting Obliterate with a single rune sometimes, then it will not allow you to Obliterate with 2 Runes, and then it will consume 3 at a time. Each cast of Obliterate during Hypothermic Presence only generates 13 runic power instead of 20. 

**Logs, Images, Videos**
> https://www.youtube.com/watch?v=HXqbvidMouw - clip of it in practice

**Howto:**
> Cast Hypothermic Presence with 1 rune or try and Obliterate with 1 Rune while it's active, observe rp gain. Note that sometimes it will animation cancel Obliterate despite having 2 runes

**Comment by BanterDK** [comment]
Timestamp for video:
00:12 - 00:14 == Obliterate cost 1 rune & returns 13 RP
00:19 == Obliterate that cost 1 rune & returns 13 RP"

01:06 - 01:10 == Obliterate cost 3 rune & returns 20 RP. Hypothermic Presence faded before the cast

**Comment by Chewsdaydk** [comment]
This just doesn't do anything anymore, you get the buff but it doesn't reduce the runic power cost of anything

**Comment by Melekus** [comment]
Fixed.
