### ISSUE TITLE
Risen Ghoul for Frost DK isn't affected by the spec aura

### ISSUE THREAD

**Issue by Chewsdaydk** [SimCMinMax/WoW-BugTracker#448]
**Game Version:**
> 9.0.1 beta Build 34324

**Description:**
> Risen Ghoul for Frost isn't affected by its +7% spec aura, probably because there isn't a pet flag on the spec aura

**Howto:**
> Check damage in game vs checking manually what you'd expect, remove spec aura and it will match. Armour reduction i used here (0.675 mod) was cross referenced between dummies, hopefully it's accurate. All relevant info is in screenshots

**Frost Ghoul**

![image](https://user-images.githubusercontent.com/39236684/81613497-7eed8080-93d6-11ea-9a86-8810844ff249.png)
>Claw
>AP * Ghoul pet AP mod * AP Coeff * Spec aura * armour reduction
>(172+15.0 * 6) * 0.6 * 0.3 * 0.675 = 31

>White damage
>Ghoul inherits 60% ap - (172+15.0* 6) * 0.6 = 157.2 and has a 2 second swing speed
>Avg. Weapon Damage + (Attack Power / 6) * Weapon Speed * spec aura * armour reduc
>0 + (157.2/6) * 2 * 0.675 = 35

**Comment by Melekus** [comment]
A new effect was added on build 35598 to the frost death knight passive aura, increasing pet damage done by the same amount as direct/periodic damage. 

See: https://github.com/simulationcraft/simc/commit/99322bd492999f591c38fe4140640e4bc4daf55b#diff-76b32cba3fcac52ba73a75698348ba02R3611

Damage calculations take this modifier into account.
Fixed.
