### ISSUE TITLE
Bloodworms isn't affected by Blood DK's spec aura

### ISSUE THREAD

**Issue by Chewsdaydk** [SimCMinMax/WoW-BugTracker#450]
**Game Version:**
> 9.0.1 beta Build 34324

**Description:**
> Bloodworms isn't affected by Blood's +29% spec aura, probably because there isn't a pet flag on the spec aura

**Howto:**
> Check damage in game vs checking manually what you'd expect, remove spec aura and it will match. Armour reduction i used here (0.675 mod) was cross referenced between dummies, hopefully it's accurate. All relevant info is in screenshots

**Bloodworms**

![image](https://user-images.githubusercontent.com/39236684/81615954-8020ac80-93da-11ea-8748-d5b808ac7c4d.png)
>White damage
>Bloodworms inherit 25% ap (172+15 * 6) * 1.08 * 0.25 = 70.74 and has a 1.4 second swing speed
>Avg. Weapon Damage + (Attack Power / 6) * Weapon Speed * spec aura * armour reduc
>0 + (70.74/6) * 1.4 * 0.675 = 11

**Comment by Melekus** [comment]
A new effect was added on build 35598 to the blood death knight passive aura, increasing pet damage done by the same amount as direct/periodic damage.

See: simulationcraft/simc@99322bd#diff-76b32cba3fcac52ba73a75698348ba02R3611

Damage calculations take this modifier into account.
Fixed.
