### ISSUE TITLE
Rupture on Sub snapshotting 50% Nightstalker bonus

### ISSUE THREAD

**Issue by Mystler** [SimCMinMax/WoW-BugTracker#472]
**Game Version:**
> 9.0.1 beta Build 35360

**Description:**
> Rupture on Subtlety, when cast from Stealth (with Marked for Death for easy testing), appears to be snapshotting a 50% Nightstalker damage bonus from Assassination instead of the 12% from Sub.

**Comment by fuu1** [comment]
fixed in version beta/ptr 9.0.1.35679
