### ISSUE TITLE
The Nether Precision Conduit is only triggered when Clearcasting expires.

### ISSUE THREAD

**Issue by Dorovon** [SimCMinMax/WoW-BugTracker#497]
**Game Version:**
> 9.0.1 beta Build 35482

**Description:**
> The Nether Precision Conduit is only triggered when Clearcasting expires instead of when a stack is consumed.

**Reproducible:**
> Examples: yes

**Howto:**
> Trigger Clearcasting and then /cancelaura the effect or let it expire. This will trigger the Nether Precision buff. Also, gain multiple stacks of Clearcasting and use one of them. This will not trigger the Nether Precision buff.

**Comment by Sergrand1** [comment]
This has been fixed in 9.0.2.36165
