### ISSUE TITLE
Shifting Power doesn't affect all Mage spells

### ISSUE THREAD

**Issue by vituscze** [SimCMinMax/WoW-BugTracker#506]
**Game Version:**
> 9.0.1 beta Build 35482

**Description:**
> The cooldown reduction from Shifting Power is not applied to Alter Time and the Teleport/Portal spells.

**Reproducible:**
> yes

**Howto:**
> cast Alter Time, cast Shifting Power

**Comment by Dorovon** [comment]
This is fixed for Teleport/Portal spells and Alter Time for Fire/Frost, but it still does not work with Arcane's Alter Time (id=342245).

**Comment by Dorovon** [comment]
Fixed on the PTR.
