### ISSUE TITLE
Certain abilities do not trigger Wild Spirits

### ISSUE THREAD

**Issue by Pewtro** [SimCMinMax/WoW-BugTracker#526]
**Game Version:**
> 9.0.1 beta Build 35432

**Description:**
> The presumed bug (issue) here is that conditionally AOE spells or spells with custom targeting (like Serpent Sting with Hydra's Bite or Wildfire Bomb and its Wildfire Infusion alternatives) trigger the single target version of the proc (spell id `328523`) even when they hit multiple targets. The expectation is that they trigger the AOE version of the proc in this case (spell id `328757`), which is triggered by regular AOE spells.

> Addendum, but not bug:
> Adding to that, pet abilitues such as Kill Command, Bloodshed, Dire Beast etc do not trigger Wild Spirits on the target, which is probably not a bug - but does mean that it's nigh useless for the more pet oriented specializations of Beast Mastery and Survival. 

**Reproducible:**
> Examples: yes

**Howto:**
> Apply Wild Spirits to an area with mobs, and cast a AoE oriented spell that I listed earlier (such as Trickshots affected Rapid Shot or Aimed Shot, or a Hydras Bite affected Serpent Sting)

**Comment by nuoHep** [comment]
> > Likewise an Aimed Shot or Rapid Fire affected by Trickshots will only trigger Wild Spirits on the main target, despite being an AOE spell.
> > Serpent Sting affected by Hydras Bite will also only trigger on the main target, despite being an AOE spell.

Just to make it a bit more factually correct.
The presumed bug (issue) here is that conditionally AOE spells *or* spells with custom targeting (like Serpent Sting with Hydra's Bite or Wildfire Bomb and its Wildfire Infusion alternatives) trigger the single target version of the proc (spell id `328523`) even when they hit multiple targets. The expectation is that they trigger the AOE version of the proc in this case (spell id `328757`), which is triggered by regular AOE spells.

**Comment by Pewtro** [comment]
Generally fixed as of 9.0.2.36206
