### ISSUE TITLE
Broadside not affecting Sepsis CP

### ISSUE THREAD

**Issue by EvanMichaels** [SimCMinMax/WoW-BugTracker#529]
**Game Version:**
> 9.0.1 beta Build 36512

**Description:**
> (Updated) Broadside does not increase the CP generation by Sepsis. Damange is affected correctly.

**Comment by EvanMichaels** [comment]
Updating name and description for latest build. Combo Points for Echoing Reprimand and Bone Spike are now affected by Broadside, but damage is not.

**Comment by Mystler** [comment]
Updated title and description. As of 36512, all covenant abilities that generate CP should now be affected correctly in their damage. Same for CP with the exception of Sepsis.

**Comment by Mystler** [comment]
Fixed on 9.0.5 PTR, even if apparently not via spell data whitelist.
