### ISSUE TITLE
Ignite does not ignore all target-based damage multipliers when spreading

### ISSUE THREAD

**Issue by Dorovon** [SimCMinMax/WoW-BugTracker#532]
**Game Version:**
> 9.0.1 beta Build 35522

**Description:**
> When Phoenix Flames is used to spread Ignite from a target that is taking increased damage from a target-based damage multiplier, this multiplier will not be factored out when copying the Ignite to the destination targets. Prior to Shadowlands, Ignite would factor out these multipliers before spreading so that vulnerable targets could not be used to generate a larger Ignite on other targets. This bug allows massive Ignites to be generated when there are multiple targets with large target-based damage multipliers. A current example is the Altimor the Huntsman encounter in Castle Nathria, where some targets gain many stacks of the [Destabilize](https://shadowlands.wowhead.com/spell=334695/destabilize) debuff.

**Logs, Images, Videos**
[Example 1](https://www.warcraftlogs.com/reports/zT8rgnjWFBqCbHyc#fight=last&type=damage-done&translate=true&start=2750821&end=2765159&ability=-12654&source=21&view=events)
[Example 2](https://www.warcraftlogs.com/reports/1dTBHGxVRLpYrCby#fight=9&type=damage-done&source=6&ability=-12654&start=2556960&end=2562752&view=events)

**Reproducible:**
> yes

**Howto:**
> Generate an Ignite on a target that is taking increased damage from a target-based damage multiplier. After using Phoenix Flames to spread the Ignite to a different target, both Ignites will benefit from the target-based damage multiplier on the source target.

**Comment by vituscze** [comment]
Looks like this isn't happening on live, closing.
