### ISSUE TITLE
Celerity Legendary procs do not trigger Loaded Dice

### ISSUE THREAD

**Issue by Mystler** [SimCMinMax/WoW-BugTracker#535]
**Game Version:**
> 9.0.1 beta Build 35679

**Description:**
- FIXED ~~As an effect that is unmentioned in the tooltip it increases the energy cap during AR by an additional 15.~~
- FIXED ~~It puts Adrenaline Rush on cooldown when it procs.~~
- FIXED ~~The duration of procs is 4s instead of 3.~~
- Does not trigger Loaded Dice.

Thanks to Loktark for providing testing data.
https://www.warcraftlogs.com/reports/PQmFZn9a6XgyL7pH/#fight=3&type=auras&source=3&ability=13750&view=events

About proc triggers: appears to use the periodic heal effect for proc triggers? My current speculation is 8% roll every 2s together with the conduit heal effect.

**Comment by Mystler** [comment]
AR Cooldown is fixed in 35679. Leaving open because of unmatching duration and Loaded Dice

**Comment by Loktark** [comment]
The unmentioned +15 effect that applied to energy cap during AR now grants 15% increased damage dealt during AR instead.

**Comment by EvanMichaels** [comment]
Tooltip updated to confirm 4s duration

**Comment by Mystler** [comment]
Renamed the issue since only Loaded Dice is left which may or may not be a bug.

**Comment by Mystler** [comment]
Assuming no LD is intended and closing this.
