### ISSUE TITLE
Roll the Bones Pandemic Refresh Issues

### ISSUE THREAD

**Issue by ZeraTheRedRogue** [SimCMinMax/WoW-BugTracker#536]
**Game Version:**
> 9.0.1 beta Build 35522

**Description:**
> Roll the Bones is showing the correct duration of time on buff tracking when a pandemic refresh is triggered, however the buffs will still fall off at exactly 30 seconds after the cast is made, regardless of how much time was left of the buff.

**Logs, Images, Videos**
No video/indicative evidence at this time other than consistent testing.

**Reproducible:**
> Any time you re-roll prior to buffs dropping off naturally.

**Comment by EvanMichaels** [comment]
Still occurring as of 35755 build

**Comment by Loktark** [comment]
Not occurring anymore as of build 35854.
