### ISSUE TITLE
Sepsis Final Hit Damage is not affected by Shiv

### ISSUE THREAD

**Issue by EvanMichaels** [SimCMinMax/WoW-BugTracker#537]
**Game Version:**
> 9.0.1 beta Build 35938

**Description:**
> Currently the final damage hit of Sepsis is not on the Shiv whitelist.

**Comment by EvanMichaels** [comment]
Still occurring as of 35755 build

**Comment by Mystler** [comment]
Final tick damage is now working in 35938. Only remaining issue via comment above is that the final tick does not appear to be on the Shiv Rank 2 whitelist. Renaming the issue.

**Comment by Mystler** [comment]
Just realized this is in a separate issue so closing this in favor of #640.
