### ISSUE TITLE
Premeditation - Slice and Dice application bug

### ISSUE THREAD

**Issue by fuu1** [SimCMinMax/WoW-BugTracker#539]
**Game Version:**
> 9.0.1 beta Build 35522

**Description:**
> Slice and Dice gets refreshed regardless of remaining duration. This means that e.g. Slice and Dice with 40 sec remaining will get refreshed to a 13 second one (10 sec base duration + 3 sec from pandemi) 

**Logs, Images, Videos**
> [Video](https://cdn.discordapp.com/attachments/316923898501529600/745749262952038410/Untitled.mp4)

**Reproducible:**
> Easy to reproduce

**Howto:**
> Apply Slice and Dice with high combo points and use Vanish followed by Shadowstrike while being talented into Premeditation

**Comment by Mystler** [comment]
Fixed in 35755 to extend existing SnD. Also works with Dance.
