### ISSUE TITLE
True Bearing triggering issues

### ISSUE THREAD

**Issue by Loktark** [SimCMinMax/WoW-BugTracker#541]
**Game Version:**
> 9.0.1 beta Build 35598

**Description:**
> When True Bearing is initially granted by Roll the Bones your first finisher does not correctly award any additional cooldown reduction. ~~Additionally after True Bearing ends your next finisher benefits from True Bearing when it should not, this occurs whether you allow Roll the Bones to fall off or recast it before the duration ends.~~ Fixed as of 9.0.2 beta Build 36294.
True bearing gained from the Count the Odds conduit correctly grants cooldown reduction from your first finisher(the triggering finisher in some cases), and does not grant it to any finishers after the duration ends.

**Reproducible:**
> Yes

**Comment by Mystler** [comment]
Fixed in 36512.
