### ISSUE TITLE
Finality for Eviscerate and Shadow Vault not working

### ISSUE THREAD

**Issue by Mystler** [SimCMinMax/WoW-BugTracker#544]
**Game Version:**
> 9.0.1 beta Build 35598

**Description:**
- Finality: Eviscerate is removed as soon you use an ability (Shadowstrke, Backstab, even Kick), so it does not last until the next Eviscerate.
- Finality: Shadow Vault is not working at all.

**Comment by EvanMichaels** [comment]
Appears fixed in latest build
