### ISSUE TITLE
Concealed Blunderbuss not behaving consistently

### ISSUE THREAD

**Issue by Mystler** [SimCMinMax/WoW-BugTracker#545]
**Game Version:**
> 9.0.1 beta Build 35598

**Description:**
> With the buff up, the next Pistol Shot does not fire 3 additional times. It appears to be random between 0-3 additional hits? I can't say what affects it but I mostly see no or one additional hit.
> Also, what is Saber Slash...

**Comment by Loktark** [comment]
This is occurring because the additional pistol shots are consuming energy. If you run out of energy before 3 hits occur then the Blunderbuss effect just ends without firing all 3.

**Comment by Mystler** [comment]
Oh boy, too many bugs. I forgot that I opened this one and opened a new one. Closing this one in favor of the new. #553
