### ISSUE TITLE
Envenom applies a debuff

### ISSUE THREAD

**Issue by Mystler** [SimCMinMax/WoW-BugTracker#549]
**Game Version:**
> 9.0.1 beta Build 35598

**Description:**
> Now applies a buff on the player PLUS a debuff on the target.
Not fully confirmed but Envenom debuff might not do anything. If somebody wants to test: I wonder if two rogues using envenom on each other cause them to benefit from both buff and debuff in PvP, essentially double dipping.

**Comment by EvanMichaels** [comment]
Debuff no longer applied on most recent build
