### ISSUE TITLE
Dashing Scoundrel behaving weirldly

### ISSUE THREAD

**Issue by Mystler** [SimCMinMax/WoW-BugTracker#550]
**Game Version:**
> 9.0.1 beta Build 35679

**Description:**
For the Dashing Scoundrel legendary, here some not fully explained observations:
- Envenom crits themselves trigger Dashing Scoundrel Energy (yes, including the one to apply the buff). Spell data kind of suggests this is a deliberate addition, just not mentioned in tooltip.
- ~~Deadly Poison Instant hit crits trigger it but DoT ticks do not.~~
- Deadly Poison Instant crit chance seems to be increased by 30% but DoT tick crit chance by 60%. There appears to be double-dipping going on. Might affect other things like poison application chance as well.

Possible there is also relation to issue #549 but so far nothing indicated a double-dip because of the debuff.

**Comment by Mystler** [comment]
DP tick crits now also trigger the energy gain in 35679. Crit double dipping still seems to be in.

**Comment by EvanMichaels** [comment]
60% crit chance still appears to be happening for Deadly Poison ticks.

https://www.warcraftlogs.com/reports/B6LNC9b32cR1rntZ/#fight=last&type=damage-done&source=1&pins=2%24Separate%24%23244F4B%24auras-gained%240%240.0.0.Any%240.0.0.Any%24true%24431585.0.0.Rogue%24false%2432645%24true%24true

**Comment by Mystler** [comment]
Fixed in 36512. Dashing Scoundrel seems to be behaving as expected now, with the only interesting exception (not in tooltip) being that Envenom itself is affected by the crit increase and energy gain on its own cast. Sepsis should probably be affected too but is not. Closing anyway.
