### ISSUE TITLE
Serrated Bone Spike not working with Dreadblades 

### ISSUE THREAD

**Issue by ZeraTheRedRogue** [SimCMinMax/WoW-BugTracker#552]
**Game Version:**
> 9.0.1 beta Build 35598

**Description:**
> Serrated Bone Spike is not generating full combo points while Dreadblades is active. Tool tip says it should work, however the Dreadblades debuff applied to character doesn't mention Serrated Bone Spike at all.

**Reproducible:**
> Yes.

**Howto:**
> Hit an enemy with Dreadblades and use Serrated Bone Spike on a target. Need to test other covenant abilities, highly likely it won't work with Slaughter or Echoing Reprimand either. Need to test to confirm.

**Comment by Mystler** [comment]
Fixed in 36512.
