### ISSUE TITLE
Mutilated Flesh not working as advertised

### ISSUE THREAD

**Issue by Mystler** [SimCMinMax/WoW-BugTracker#554]
**Game Version:**
> 9.0.1 beta Build 35598

**Description:**
> The Mutilated Flesh DoT from the Doomblade legendary has a 6s base duration (instead of 3s as in tooltip) with 3s periodic ticks that are 5% of MH+OH damage (see #542). Both Mutilate hits trigger it causing it to have a pandemic refreshed duration of about 8s.

> Additionally, the first refresh has a bugged duration and although it expires on the client after the normal duration, it continues ticking on the server up to 12 seconds after the initial hit (for 4 ticks total.) Subsequent durations are more correct, so this is extremely inconsistent.

**Comment by EvanMichaels** [comment]
Calculations seem more consistent now and tooltip is updated to show the base 8s duration. (Although this still refreshes up to 12s.)

**Comment by EvanMichaels** [comment]
In testing, damage was correctly done as 20% of the MH+OH hit spread over 4 ticks.
