### ISSUE TITLE
Perforated Veins Behavior is Questionable

### ISSUE THREAD

**Issue by EvanMichaels** [SimCMinMax/WoW-BugTracker#555]
**Game Version:**
> 9.0.1 beta Build 35598

**Description:**
> Currently the behavior of Perforated Veins appears to not match the expected behavior. The description is, "Shadowstrike increases the damage of your next Backstab by 30%, stacking up to 3 times."

> The current behavior is, indeed, that it stacks 3 times. However the next Backstab only consumes 1 stack, while benefiting from a bonus relative to the stack size. For example, if the player has 3 stacks, they gain 90% additional damage on their next Backstab, go down to 2 stacks, gain 60% on their following Backstab, go down to 1 stack, etc.

> It seems to be implied that _either_ the entire stack is consumed (1 Backstab getting 60% additional damage, then disappearing) or for each Backstab to only gain a 30% buff until the full stack is consumed.

> If this is the intended behavior, the tooltip is fairly unclear about this and it doesn't appear to be consistent with other similar mechanics.

**Logs, Images, Videos**
> https://www.warcraftlogs.com/reports/1Zt9XYQNjC3fqg68/#boss=2417&difficulty=5&wipes=1&type=damage-done&source=296&start=1812229981&end=1812363526&pins=0%24Separate%24%23a04D8A%24auras-gained%240%240.0.0.Any%240.0.0.Any%24true%24446427.0.0.Rogue%24false%24341572&ability=53&view=events

**Reproducible:**
> Yes

**Comment by Mystler** [comment]
Fixed in 35938. Backstab consumes all stacks now.
