### ISSUE TITLE
Echoing Reprimand animacharged combo points aren't applying Rupture with 7 CP

### ISSUE THREAD

**Issue by Shirofune** [SimCMinMax/WoW-BugTracker#556]
**Game Version:**
> 9.0.1 beta Build 35598

**Description:**
> When using Rupture with an animacharged CP, it isn't working with 7 CP, but with always a 22 second duration (which is a 4 CP Rupture), doesn't matter the animacharged CP (2, 3 or 4).

>i.e. using 2 CP animacharged Rupture applies a 22 sec Rupture, but so does 3 and 4 CP

>ER reads "damaging finishers", so I'm not sure if Rupture should trigger it or not, but it's still consuming the animacharged combo point and the duration of Rupture doesn't match your CPs.

**Logs, Images, Videos**
> https://www.youtube.com/watch?v=N6CbbsFzB1Y

**Reproducible:**
> yes

**Howto:**
> Use ER, get to the animacharged CP, use Rupture.

**Comment by EvanMichaels** [comment]
Still happening in 9.0.2

**Comment by Mystler** [comment]
As of 35938, it simply consumes the ER buff without an effect and Rupture duration matches the combo points spent.

**Comment by Mystler** [comment]
Fixed in 36086
