### ISSUE TITLE
Tranquilizing Shot lists melee weapons as a requirement to use, but only works with ranged weapons.

### ISSUE THREAD

**Issue by Thyminde** [SimCMinMax/WoW-BugTracker#563]
**Game Version:**
9.0.1 beta Build 35598

**Description:**
Tranquilizing shot is currently unable to be cast when not using a ranged weapon, despite melee weapons (aswell as ranged weapons) being listed as a weapon requirement in order to use the spell. Attempting to use Tranquilizing shot with anything other than a ranged weapon gives you the error message: "Must have a Axe equipped"

**Reproducible:**
Examples: Yes

**Howto:**
1) Unequip any weaponry, and observe Tranquilizing Shot's tooltip.
2) Attempt to use the ability, and observe the error message.
3) Repeat step 2 with ranged weaponry equipped (guns, bows, crossbows), aswell as 2 handed melee weaponry equipped (Staves, polearms, 2 handed axes, 2 handed swords).

**Comment by Pewtro** [comment]
Fixed in build 35755
