### ISSUE TITLE
Kill Shot is unaffected by Spirit Bond (Survival Hunter mastery)

### ISSUE THREAD

**Issue by Thyminde** [SimCMinMax/WoW-BugTracker#564]
**Game Version:**
9.0.1 beta Build 35598

**Description:**

Kill Shot is unaffected by Spirit Bond (survival hunter mastery bonus) despite otherwise meeting the criteria of a focus cost requirement.

**Reproducible:**

Examples: yes

**Howto:**

1) Observe the Kill Shot tooltip, take note of the listed damage value.
2) Crosscheck the tooltip damage with Raptor Strike, as Kill Shot has precisely twice the AP modifier. however Kill Shot's tooltip will not match this, because it is not affected by Mastery.
3) Fire a Kill Shot Observe the damage, the damage should be give or take 30% lower taking armour values into consideration.
4) Unequip, or Re-Equip a previously unequipped item with mastery, and without versatility. preferably jewelry so that agility does not interfere. repeat steps 2 through 4 and observe the tooltips and dealt damage.

**Comment by Pewtro** [comment]
Fixed in build 35755
