### ISSUE TITLE
Harpoon can fail to cast, resulting in a "no path available" message, when a path is clearly available.

### ISSUE THREAD

**Issue by Thyminde** [SimCMinMax/WoW-BugTracker#565]
**Game Version:**
9.0.1 beta Build 35598

**Description:**
Harpoon can fail to cast in certain zones, it appears that only new Shadowlands zones are affected at all, it most notably happens in dungeons and raids, aswell as The Maw.

**Logs, Images, Videos**
![-](https://user-images.githubusercontent.com/51829317/90963396-86cdbe00-e4b7-11ea-84a5-46e30a0c8053.png)

**Reproducible:**
Examples: rarely, it appears to depend on the exact area you're in, Harpoon either consistently works, or fails depending on where you are.

**Howto:**
1) Either head to the dummies in Oribos, or The Maw, or attempt a dungeon or raid.
2) Attempt to cast Harpoon. on a reasonable target that clearly does not have a blocked path.
3) If it works, it will likely consistently work within the area, if it does not work, it will likely consistently fail within the area

**Comment by Pewtro** [comment]
Seems generally fixed in most recent build.
