### ISSUE TITLE
Premeditation Buff Issues/Persisting Between Talent/Spec Changes

### ISSUE THREAD

**Issue by ZeraTheRedRogue** [SimCMinMax/WoW-BugTracker#567]
**Game Version:**
> 9.0.1 beta Build 35598

**Description:**
> The Premeditation Talent Buff will stay active, even if you change talents/specs. Switching between to/from Predmeditation will also remove ANY remaining amount of active slice and dice buff you currently have. However, if you save combo points for after you swap to Weaponmaster and apply slice and dice, then your next Shadowstrike will still give extra combo points even though you no longer have Premeditation selected as a talent. If Slice and Dice isn't active, then it won't give the extra CP OR the 10 seconds of Slice and Dice.

**Logs, Images, Videos**
> https://youtu.be/xjzZbWXOjXU

**Reproducible:**
> Yes.

**Howto:**
> Choose Premeditation. Stealth, and then un-stealth. Change talent to Weaponmaster. Generate CPs WITHOUT using Shadowstrike. Make sure Slice and Dice buff is active. Use Shadowstrike from stealth.

**Comment by fuu1** [comment]
fixed in the latest ptr hotfix (ptr 9.0.1.36163).
