### ISSUE TITLE
Slaughter Scars Conduit is Affecting Inconsistent Spells

### ISSUE THREAD

**Issue by EvanMichaels** [SimCMinMax/WoW-BugTracker#569]
**Game Version:**
> 9.0.1 beta Build 35598

**Description:**
> Currently the Slaughter Scars conduit is worded as, "Slaughter's damage and critical strike chance increased by $s1%.  Bonuses increased by $s2% if Slaughter Poison is active." However the Conduit is affecting the Critical chance of the periodic component in spell 323659. However, since this does not affect the "instant poison" component, it seems likely this is in error.

> Either this should not affect the DoT portion, or it should also affect the instant portion. But I'm assuming it's intended for the conduit to only increase the Crit% of the primary attack.

**Logs, Images, Videos**
> https://www.warcraftlogs.com/reports/XA9padqPRMKLHkwy/#fight=47&type=damage-done&source=526&start=429439747&end=429713764

**Reproducible:**
> Yes

**Comment by Mystler** [comment]
Slaughter is gone. Closing. We'll wait for how the conduit is updated.
