### ISSUE TITLE
Arcane Harmony buff persists through gear swaps

### ISSUE THREAD

**Issue by cgdangelo** [SimCMinMax/WoW-BugTracker#571]
**Game Version:**
> 9.0.1 beta Build 35598

**Description:**
> The buff provided by Arcane Harmony persists after unequipping the legendary, and buffs Arcane Barrage's damage.

**Reproducible:**
> Yes

**Howto:**
> 1. Equip an Arcane Harmony legendary.
> 2. Build Arcane Harmony stacks with Arcane Missiles.
> 3. Unequip the legendary.
> 4. Use Arcane Barrage and see its damage has benefited from Arcane Harmony.

**Comment by Sergrand1** [comment]
This has been fixed in 9.0.2.36165
