### ISSUE TITLE
Venthyr Covenant ability is not extended by Darkglare (Affliction)

### ISSUE THREAD

**Issue by yourCuteMotoko** [SimCMinMax/WoW-BugTracker#573]
**Game Version:**
> 9.0.1 beta Build 35598

**Description:**
> Impending Catastrophe Damage over time is not affected by Darkglare 8 second dot extension, unlike Kyrian Scouring Tithe and Night Fae Soul Rot

**Logs, Images, Videos**
> Please attach Logs, Images, and/or a Video of the bug if applicable.

**Reproducible:**
> yes

**Howto:**
> Cast Impending Catastrophe and before the damage over time component wears off cast Summon Darkglare

**Comment by Azevara** [comment]
Unclear when this was fixed but as of today on 9.1 PTR this can be closed
