### ISSUE TITLE
Madness of Azj'aqir does not double shard bits generated by Incinerate Critical Hits (Destruction)

### ISSUE THREAD

**Issue by yourCuteMotoko** [SimCMinMax/WoW-BugTracker#575]
**Game Version:**
> 9.0.1 beta Build 35598

**Description:**
> Legendary item Madness of Azj'Aqir doubles shard bits generated on Incinerate hits but not crits. The expected value would be 4 fragments on hit and 6 on crit but the latter gets only 5.

**Logs, Images, Videos**
> Please attach Logs, Images, and/or a Video of the bug if applicable.

**Reproducible:**
> yes

**Howto:**
> How do you reproduce it (if you know).

**Comment by Azevara** [comment]
This was fixed with the 9.0.5 release.
