### ISSUE TITLE
Artifice of the Archmage does not trigger Rule of Threes

### ISSUE THREAD

**Issue by cgdangelo** [SimCMinMax/WoW-BugTracker#576]
**Game Version:**
> 9.0.1 beta Build 35598

**Description:**
> Artifice of the Archmage does not trigger Rule of Threes when generating 4 Arcane Charges.

**Reproducible:**
> Yes

**Howto:**
> 1. Equip the Artifice of the Archmage conduit.
> 1. Select the Rule of Threes talent.
> 1. Use Arcane Blast to build at least 1 Arcane Charge.
> 1. Use Arcane Barrage to hit 2+ targets.
> 1. If Artifice of the Archmage procs on 2+ targets, it will generate 4 Arcane Charges but not trigger a Rule of Threes buff.

**Comment by Sergrand1** [comment]
This has been fixed in 9.0.2.36165
