### ISSUE TITLE
Siphon Storm does not trigger Rule of Threes

### ISSUE THREAD

**Issue by cgdangelo** [SimCMinMax/WoW-BugTracker#578]
**Game Version:**
> 9.0.1 beta Build 35598

**Description:**
> Siphon Storm generates 2 Arcane Charges but does not trigger Rule of Threes.

**Reproducible:**
> Yes

**Howto:**
> 1. Equip a Siphon Storm legendary.
> 1. Select the Rule of Threes talent.
> 1. Use Arcane Blast to generate 1 Arcane Charge.
> 1. Cast Evocation to generate 2 Arcane Charges from Siphon Storm, for a total of 3 Arcane Charges.
> 1. Observe that Rule of Threes is not triggered.

**Comment by Sergrand1** [comment]
This has been fixed in 9.0.2.36165
