### ISSUE TITLE
Certain Frost spells cancel Invisibility fadeout

### ISSUE THREAD

**Issue by vituscze** [SimCMinMax/WoW-BugTracker#58]
**Game Version:**
> 8.0.1 Alpha Build 25976

**Description:**
> When Frostbolt, Flurry and Ebonbolt (and possibly more spells) deal damage, the 3 second fadeout of Invisibility is instantly canceled. For other specs, only casting a spell removes the fadeout (and not impacts/damage events).

**Reproducible:**
> yes

**Howto:**
> Cast Frostbolt and Invisibility instantly after.

**Comment by cgdangelo** [comment]
I think Icicles also cause this.

**Comment by vituscze** [comment]
Nah, it seems that Icicles are fine. Unless you mean Icicle generation, which might be the cause of the Frostbolt thing.

**Comment by vituscze** [comment]
I was sure Flurry wasn't breaking the fadeout when I last checked on live, but it seems to be breaking it on alpha. I'll edit the issue.

**Comment by vituscze** [comment]
Yeah, this definitely changed in BfA. Frozen Orb removes the fadeout on live and it doesn't seem to on alpha.

**Comment by vituscze** [comment]
Video demonstration of the bug: https://www.youtube.com/watch?v=11vjrriDHPw

**Comment by vituscze** [comment]
Frostbolt, Flurry and Ebonbolt don't cause any issues. Haven't managed to test all spells yet, but I'm closing this for now.
