### ISSUE TITLE
Loaded Dice Buff Incorrectly Consumed by Slice and Dice

### ISSUE THREAD

**Issue by Loktark** [SimCMinMax/WoW-BugTracker#582]
**Game Version:**
> 9.0.1 beta Build 35679

**Description:**
> Loaded dice is consumed by Slice and Dice causing your next cast of Roll the Bones to not correctly always grant at least 2 buffs. This is likely leftover from Legion when you could have both effects at once, however it does not grant the increased effectiveness of Slice and Dice that it use to when consumed this way.

**Logs, Images, Videos**
> https://www.warcraftlogs.com/reports/fgR4wXJVFBNrkpLW/#fight=1&type=auras&source=3

**Comment by EvanMichaels** [comment]
Still happens on latest 9.0.2 build

**Comment by Mystler** [comment]
Still true in 36294.

**Comment by Mystler** [comment]
Fixed in 36512.
