### ISSUE TITLE
Shadow Priest Mastery Bugs

### ISSUE THREAD

**Issue by Ursus-Maritimus** [SimCMinMax/WoW-BugTracker#590]
**Game Version:**
9.0.1 beta Build 35679

**Description:**
The dots snapshot the %, in the sense that if u swp you apply the x% once, but swp itself does not get the benefit. 
If you swp > VT, VT gets the % of the swp application, swp gets none.

DP does not give any %

so if u want the bonus on your dots u have to VT > SWP > VT > SWP

 same thing in voidform, if u have 2 dots on a target and Voidform, it does not get the benefit at all on the dots, until u reapply them

**Reproducible:**
Yes

**Comment by justpersonalthings** [comment]
spells not affected by shadow mastery: void torrent, mindbender, shadowfiend, shadowy apparitions, void eruption

**Comment by justpersonalthings** [comment]
Mind Bender and Shadow Fiend are still not affected by shadow's mastery. Everything else has been fixed so far.
