### ISSUE TITLE
Echoing Reprimand animacharged combo points iteration with Deepening Shadows is wrong.

### ISSUE THREAD

**Issue by Shirofune** [SimCMinMax/WoW-BugTracker#595]
**Game Version:**
> 9.0.1 beta Build 35679

**Description:**
> Echoing Reprimand animacharged combo points iteration with Deepening Shadows is wrong.

> Instead of applying the 7 CP reduction (14 seconds) it's applying the reduction of the CP that is animacharged (2 -> 4 seconds, 3 -> 6 seconds, 4 -> 8 seconds)

**Reproducible:**
> Examples: yes

**Howto:**
> Get Shadow Dance on CD. Use ER. Use Eviscerate with the animacharged CP. Look at the CDR applied to Shadow Dance.

**Comment by EvanMichaels** [comment]
At least in terms of the tooltip, this seems intentional. Not good, but intentional.  "Deal damage as if they consume 7 combo points." does not apply to any of the secondary effects of CP spending, which is part of why the ability is so weak.

**Comment by Mystler** [comment]
Closing this since it should now affect passives like this and the ability was updated from "deal damage as if" to "function as if".
