### ISSUE TITLE
Mark of the Master Assassin Buff Persisting Upon Removal of Legendary

### ISSUE THREAD

**Issue by ZeraTheRedRogue** [SimCMinMax/WoW-BugTracker#596]
**Game Version:**
> 9.0.1 beta Build 35679

**Description:**
> If you enter stealth while wearing a legendary with the Mark of the Master Assassin effect, you will gain the buff. However, if you remove the legendary and swap it for a different one, the legendary effect of the Master Assassin will remain on your character until you exit stealth, functioning for the first 5 seconds of a pull despite wearing a different legendary.

**Logs, Images, Videos**
Will include a video file to this once uploaded on hosting site

**Reproducible:**
>Yes.

**Howto:**
> Equip Mark of the Master Assassin Legendary. 
> Enter Stealth.
> Change Master Assassin Legendary for a different one, while remaining in Stealth.
> Engage a target.

**Comment by Mystler** [comment]
Fixed in 36512.
