### ISSUE TITLE
Dancing Steel Increases Blade Flurry's Cooldown without Being in Tooltip

### ISSUE THREAD

**Issue by EvanMichaels** [SimCMinMax/WoW-BugTracker#597]
**Game Version:**
> 9.0.1 beta Build 35679

**Description:**
> Although this has been present in live spell data, Dancing Steel increases the cooldown of Blade Flurry by 3 seconds in addition to the duration. This is not indicated anywhere in the tooltip for the Talent.

**Comment by ZeraTheRedRogue** [comment]
As of Build 35938, Dancing Steel is not increasing the cooldown of Blade Flurry any longer.
