### ISSUE TITLE
Echoing Reprimand Not Affecting Secret Technique

### ISSUE THREAD

**Issue by EvanMichaels** [SimCMinMax/WoW-BugTracker#600]
**Game Version:**
> 9.0.1 beta Build 35679

**Description:**
> When consuming an Animacharged combo point to cast Secret Technique, the damage values appear to be the same as they would when naturally using that combo point value.

**Reproducible:**
> Yes

**Comment by EvanMichaels** [comment]
Still occurring in build 35755

**Comment by EvanMichaels** [comment]
In the latest build, this no longer consumes the ER buff, but does not work either.

**Comment by Mystler** [comment]
Appears fixed in 36086
