### ISSUE TITLE
The Freezing Winds buff will sometimes remain when no Frozen Orb is active

### ISSUE THREAD

**Issue by Dorovon** [SimCMinMax/WoW-BugTracker#606]
**Game Version:**
> 9.0.1 beta Build 35679

**Description:**
> The Frost Mage legendary Freezing Winds functions by applying a 30-second buff called Freezing Winds to the player. When the player has no active Frozen Orbs this buff is removed from the player early. There is at least one bug that makes it possible to achieve a state where the buff is never removed early and always lasts the full 30 seconds.

**Reproducible:**
> yes

**Howto:**
> Equip the Freezing Winds legendary, enter an instance, cast Frozen Orb, and leave the instance before Frozen Orb expires. After doing this, the Freezing Winds buff will no longer be removed when the player does not have an active Frozen Orb.

**Comment by The-PaleRider** [comment]
Persists through death and changing Zone/Instances

**Comment by vituscze** [comment]
In 9.0.2.36165, this bug now happens all the time and doesn't require any zone changes to trigger.
