### ISSUE TITLE
Unholy Blight applies Virulent Plague and other DoT's on targets at infinite range

### ISSUE THREAD

**Issue by Chewsdaydk** [SimCMinMax/WoW-BugTracker#608]
**Game Version:**
> 9.0.1 beta Build 35679

**Description:**
> Unholy Blight applies Virulent Plague each second for 6 seconds (+Frost Fever and Blood Plague with Superstrain) - currently it also applies these to your active targets and everything within 8 yards of them at an infinite range

**Logs, Images, Videos**
> https://www.youtube.com/watch?v=tz1pXg9BL8g

**Comment by Melekus** [comment]
Was unable to reproduce on PTR build 35989, seems fixed.
