### ISSUE TITLE
Slick Ice doesn't reduce GCD below 0.75 sec

### ISSUE THREAD

**Issue by vituscze** [SimCMinMax/WoW-BugTracker#610]
**Game Version:**
> 9.0.1 beta Build 35679

**Description:**
> While the buff from Slick Ice (Frost Mage legendary effect) reduces the GCD of Frostbolt, it doesn't reduce it below 0.75 sec. The cast time of Frostbolt can be reduced under 0.75 sec quite easily (Icy Veins, 10 stacks of Slick Ice and Time Warp alone result in 0.79 sec cast time), which results in gaps between Frostbolt casts.

**Logs, Images, Videos**

```
9/1 21:57:44.406  SPELL_CAST_START,Player-4184-00069708,"Norri-Torghast",0x511,0x0,0000000000000000,nil,0x80000000,0x80000000,116,"Frostbolt",0x10
9/1 21:57:44.945  SPELL_CAST_SUCCESS,Player-4184-00069708,"Norri-Torghast",0x511,0x0,Creature-0-2085-2222-14102-154564-00004C8031,"Valiant's Humility",0x10a28,0x0,116,"Frostbolt",0x10,Player-4184-00069708,0000000000000000,21900,21900,80,1053,193,0,0,43885,52500,1000,-1726.70,-5841.02,1707,2.7563,141
9/1 21:57:45.199  SPELL_CAST_START,Player-4184-00069708,"Norri-Torghast",0x511,0x0,0000000000000000,nil,0x80000000,0x80000000,116,"Frostbolt",0x10
```

**Reproducible:**
> yes

**Howto:**
> have ~10% haste from gear, cast Time Warp, Icy Veins and reach 10 stacks of Slick Ice, notice that Frostbolt casts faster than GCD

**Comment by neoxz04** [comment]
Haste can only reduce GCD to a minimum of 0.75 sec in general. Is Slick Ice supposed to break that rule?

**Comment by vituscze** [comment]
Slick Ice isn't haste buff, similar effects have reduced GCD below 0.75 sec in the past.

**Comment by vituscze** [comment]
After some more investigation, it seems that effects which reduce GCD of a spell by a percentage do indeed reduce min GCD below 0.75 sec. However, the min GCD reduction is based on the spell's original GCD rather than its actual GCD.

As an example, the Storm Elemental talent (which reduces cast time and GCD of Lightning Bolt by up to 60%) reduces GCD in the following way:

![image](https://cdn.discordapp.com/attachments/244072280919900160/750751910738526248/unknown.png)

You can see that the GCD gets stuck at 0.75 sec for quite a while (stacks 11-16) and then finally goes below 0.75 sec.

**Comment by vituscze** [comment]
No longer relevant.
