### ISSUE TITLE
Premeditation - Buff gets applied multiple times during shadowdance

### ISSUE THREAD

**Issue by fuu1** [SimCMinMax/WoW-BugTracker#618]
**Game Version:**
> 9.0.1 beta Build 35755

**Description:**
> Premeditation procs after/during shd application multiple times.
> It currently gets a 2nd application if the first buff is consumed in the first gcd
> Consuming the 2nd buff applies it again after ~4 secs

**Logs, Images, Videos**
>Log: [Combatlog.txt](https://pastebin.com/JfqNAdiv)
> Video: [Video.mp4](https://cdn.discordapp.com/attachments/398549488723296258/750977798566314044/2020-09-03_09-16-56.mp4)

**Reproducible:**
> Easy

**Howto:**
> Use Shadow Dance while talented into Premeditation and use one of either sequences while keeping an eye on your buffs:
> 1. Shadow Dance-Shadow strike-Shadow Strike
> 2. Shadow Dance- Shadow strike- Finisher - Shadow Strike

**Comment by ashokmathur** [comment]
This bug is leading to 1 minute+ SnD buffs if you keep chain shadow dancing+striking. See attached image

![image](https://user-images.githubusercontent.com/70525715/92117857-b936bf80-edc3-11ea-9526-0544cffab8f0.png)

**Comment by fuu1** [comment]
fixed in the latest ptr hotfix (ptr 9.0.1.36163).
