### ISSUE TITLE
Akaari Shadowstrikes Double-Dip Damage Multipliers

### ISSUE THREAD

**Issue by EvanMichaels** [SimCMinMax/WoW-BugTracker#621]
**Game Version:**
> 9.0.1 beta Build 35755

**Description:**
> It appears that as part of the Akaari internal damage calculations, the base damage of the Akaari-triggered Shadowstrike proc appears to fold in the post-buff base damage from the original Shadowstrike. This damage then appears to be passed along to the ability, which _also_ is modified by the damage multipliers. This causes the Akaari Shadowstrike to do far more damage than intended.

> Spec Passive = 21%, Shadow Dance = 15%, Nightstalker = 12%. Would multiply out to 1.55848. Which seems to match testing when using Nightstalker and Enveloping Shadows. When using Dark Shadow, this gap is larger. 

**Logs, Images, Videos**
![image](https://user-images.githubusercontent.com/24741480/92276171-7c032800-eebe-11ea-9443-cb843a5c5d6a.png)

Green = Original Shadowstrike casts
Purple and Orange = Akaari procs

**Reproducible:**
> Yes

**Howto:**
> Either naturally observe Akaari proc damage results, or simply use Symbols of Death right before an Akaari proc is due to trigger.

**Comment by Shirofune** [comment]
I might be wrong here, but through my testing, what I realized is that Akaari's isn't double dipping, instead, the Shadowstrike of Akaari is always 200% AP:

![image](https://user-images.githubusercontent.com/15874551/92876530-7fd90200-f40a-11ea-8e23-56de4847c0be.png)

What we have instead is a situation in which we have a totally new instance of Shadowstrike, with 200% AP, and it's own chance to crit.

This is an example of the original SS not critting, but Akaari's critting:

![image](https://user-images.githubusercontent.com/15874551/92876757-c0388000-f40a-11ea-8569-b3d5d3926d82.png)

I also didn't see a single Akaari proc below 1.3k~ damage in my testing.

**Comment by EvanMichaels** [comment]
Certainly could be. Hard to tell what it's doing internally. The internal damage calculation is wrong one way or another.

**Comment by EvanMichaels** [comment]
Although at least in my case, I'm not sure it's 200% damage. It definitely seems lower than that, but higher than it should be. It's seemingly closer to 1.5x base than 2.0x. 

My hunch here is that it is double dipping the passive damage increases. Spec Passive = 21%, Shadow Dance = 15%, Nightstalker = 12%.  Would multiply out to 1.55848.

That would match what I am seeing exactly. So this seems to be the likely cause.

**Comment by Shirofune** [comment]
Forgot to say, my testing is done outside of any % damage increases. No SoD, no ShD.

I agree the numbers don't match perfectly, the crit damage of Akaari being x4 should be close to 3700-3800, but it's only 3k. I wouldn't blame it on the 5% variance either. Maybe the crit scaling of Akaari isn't x2?

No idea what's going on there.

**Comment by EvanMichaels** [comment]
I mean you will have a damage modifier when casting Shadowstrike one way or another--either Shadow Dance or the Stealth bonus. And the 21% class passive.

**Comment by Shirofune** [comment]
You're completely right, I forgot about the Stealth bonus. Numbers match now.

**Comment by EvanMichaels** [comment]
This appears fixed in the latest build with the transition to the new damage spell. Closing.
