### ISSUE TITLE
Death Knight's Talent Voracious increases Death Strike healing by an incorrect amount.

### ISSUE THREAD

**Issue by Melekus** [SimCMinMax/WoW-BugTracker#627]
**Game Version:**
> 9.0.1 beta Build 35789

**Description:**
> Death Knight's talent Voracious' tooltip states that it increases Death Strike Healing by 20% but it seems like it instead increases Death Strike's base healing from 7% maximum HP to 10% (without the 20% added further).
I haven't been able to check how Voracious behaves on scenarios where Death Strike healing from damage taken takes over the %max HP formula.

edit:The 7% maxhp -> 10% maxhp by itself results in a ~43% increase in healing, very far from the 20% in tooltip.

**Reproducible:**
> Yes

**Howto:**
> Compare healing done by Death Strike with no damage intake with and without Voracious talented.

**Comment by Melekus** [comment]
Addendum:
The tooltip of Death Strike changes from "25% of all damage taken in the last 5s, minimum 7% of maximum health" to "30% of all damage taken in the last 5s, minimum 10% of maximum health" when Voracious is talented. 
The 7% -> 10% maximum health base heal is a ~42.9% increase and the 25% -> 30% of damage taken is a 20% increase, as the tooltip indicates.

This is either a bug on Death Strike's interaction with Voracious, or the Voracious talent tooltip is missing critical information about how it affects Death Strike's base healing.

**Comment by srenauld** [comment]
It's 10.5%, the tooltip is indeed floored.

The tooltip is missing critical info, or the tooltip was written before the effect was added.

**Comment by Kyrasis** [comment]
This bug has been fixed.

**Comment by Armadk** [comment]
The tooltip is now accurate in DF beta.
