### ISSUE TITLE
Shadow Dance has no ICD anymore

### ISSUE THREAD

**Issue by Mystler** [SimCMinMax/WoW-BugTracker#628]
**Game Version:**
> 9.0.1 beta Build 35789

**Description:**
> While it's hard to be sure to what degree this is a bug or an accident, it certainly can be a reason for frustration. Shadow Dance used to have a few seconds of Internal Cooldown so that pressing the ability multiple times could not trigger it multiple times.
This is now gone, so if you hit it twice in a row, you can also burn all 2 charges by accident. Even macros are not able to fully fix this because of bar lag.

**Comment by fuu1** [comment]
Shadow dance now triggers a 8 sec cooldown on ptr.
fixed (ptr 9.0.1.36163).
