### ISSUE TITLE
Talents Primal Instincts bug with Harpoon

### ISSUE THREAD

**Issue by Nianel** [SimCMinMax/WoW-BugTracker#63]
**Game Version:**
> 8.0.1 Alpha Build 25976

**Description:**
> With the talent Primal Instincts on Survival spec, the Harpoon doesn't give the 15% crit.

**Details:**
> https://gyazo.com/786f71d36f60909c163c3b41dba9ac08

**Reproducible:**
> Yes

**Howto:**
> Take the talent Primal Instincts and Harpoon your target for have the buff Primal Instinct : Ferocity.

**Comment by nuoHep** [comment]
Looks like this is intended.

`Primal Instincts` Harpoon portion reads `increases the Critical Strike chance of your abilities` and looking at the actual buff applied (http://bfa.wowhead.com/spell=260442/primal-instinct-ferocity) we can see that it *actually means* `your abilities` as it operates in terms of a white list.
