### ISSUE TITLE
Between the Eyes debuff is weaker than expected and doesn't work with Blade Flurry

### ISSUE THREAD

**Issue by EvanMichaels** [SimCMinMax/WoW-BugTracker#632]
**Game Version:**
> 9.0.1 beta Build 35789

**Description:**
> This is not so much a 'bug' since it was expected, but want to bring it up as it will be somewhat confusing to players. Between the Eyes' new debuff seems inspired by the popularity of Blood of the Enemy, but unfortunately this debuff does not actually function like Blood of the Enemy at all. 

> Since target debuffs are ignored for the purposes of Blade Flurry damage, the additional bonus Crit damage is not replicated to secondary targets. With Blood of the Enemy -> BtE (as people use on live) since Seething Rage is a buff, the damage was replicated which is why it was so widely used.

> Additionally, since it is a target modifier it is also significantly weaker than it may appear. A 20% Crit damage *buff* will take the player from a 200% Crit to a 240% Crit. However, the current BtE debuff only takes the player to a 220% Crit.

**Comment by Mystler** [comment]
Closing since Between the Eyes was changed back to crit chance, which translates into Blade Flurry again.
