### ISSUE TITLE
UI Error Message Every Cast of Envenom + Slaughter

### ISSUE THREAD

**Issue by EvanMichaels** [SimCMinMax/WoW-BugTracker#633]
**Game Version:**
> 9.0.2 beta Build 35854

**Description:**
> The player consistently receives a "You do not have Deadly Poison or Wound Poison Active" UI error message when casting Envenom while using Slaughter Poison.

**Reproducible:**
> Yes

**Comment by Mystler** [comment]
Closing since Slaughter is gone.
