### ISSUE TITLE
Master Poisoner Doesn't Affect Numbing Poison

### ISSUE THREAD

**Issue by EvanMichaels** [SimCMinMax/WoW-BugTracker#634]
**Game Version:**
> 9.0.2 beta Build 35854

**Description:**
> As of the latest build, the Master Poisoner talent seems to have no impact on the potency of Numbing Poison. If this only applies to Crippling Poison, it should say directly rather than just 'non-damaging effects.'

**Comment by Mystler** [comment]
Fixed in 36512.
