### ISSUE TITLE
Empowered Release conduit for Venhyr Hunters does not increase proc chance of Flayer's Mark

### ISSUE THREAD

**Issue by Pewtro** [SimCMinMax/WoW-BugTracker#635]
**Game Version:**
> 9.0.2 beta Build 35854

**Description:**
> Empowered release is meant to increase the proc chance of Flayer's Mark by 5% (from 15% -> 20%), but it doesn't. 

**Logs, Images, Videos**
> https://www.warcraftlogs.com/reports/gN2anVyw6FCXMxjt/#fight=last&source=43&type=summary
> 7340 Flayed Shot ticks
> 1101 Flayer's Mark procs
> 1101/7340 = 0.15, so it's still flat 15% proc chance. 

**Reproducible:**
> yes

**Howto:**
> Cast a lot of Flayed Shot with Empowered Release equipped and notice ~15% proc chance still.

**Comment by Pewtro** [comment]
Added a log from the current build (9.0.2.35938) where it's still bugged.

**Comment by Jayezi** [comment]
As of 9.0.2.36086 I get a much more expected 19.4% rate comapred to 14.8% and 14.3% in the last two builds.
https://www.warcraftlogs.com/reports/wgrhpaBv8tRkzJnW/#boss=-3&difficulty=0&source=15&type=auras

**Comment by Pewtro** [comment]
Closing as it seems fixed in build 9.0.2.36086
