### ISSUE TITLE
Shiv Doesn't Affect Sepsis Final Damage (Updated)

### ISSUE THREAD

**Issue by EvanMichaels** [SimCMinMax/WoW-BugTracker#640]
**Game Version:**
> 9.0.2 beta Build 35854

**Description:**
> The current Shiv debuff whitelist contains most sources of Nature damage for Assassination, including Nothing Personal, Poison Bomb, and Envenom. However it does not currently affect Sepsis despite doing Nature damage.

**Reproducible:**
> Yes

**Comment by EvanMichaels** [comment]
Sepsis was updated to have the periodic damage affected by Shiv in the latest build, but the final damage spell still does not appear to be whitelisted.

**Comment by Mystler** [comment]
Fixed in 36512.
