### ISSUE TITLE
Dreadblades Does Not Break Stealth

### ISSUE THREAD

**Issue by EvanMichaels** [SimCMinMax/WoW-BugTracker#641]
**Game Version:**
> 9.0.2 beta Build 35854

**Description:**
> Dreadblades currently has the 'Does Not Break Stealth' flag, making it possible to use it from stealth and deal the damage to your target without actually breaking out of stealth.

**Reproducible:**
> Yes

**Comment by Mystler** [comment]
Fixed in 36512.
