### ISSUE TITLE
Deeply Rooted Elements triggers Ascendance cooldown

### ISSUE THREAD

**Issue by Bloodmallet** [SimCMinMax/WoW-BugTracker#648]
**Game Version:**
> 9.0.2 beta Build 35854

**Description:**
> The random Ascendance proc legendary Deeply Rooted Elements activates Ascendance cooldown period.

**Logs, Images, Videos**
> Please attach Logs, Images, and/or a Video of the bug if applicable.

**Reproducible:**
> yes

**Howto:**
> Have Ascendance ready (don't use it) -> cast Lava Burst until legendary proc; see Ascendance suddenly activating its cooldown

**Comment by nixlnixlnixl** [comment]
game version: 9.0.2 beta Build 36512
![deeproots](https://user-images.githubusercontent.com/73984865/98210498-57bcd980-1f49-11eb-86b1-e47ee61fd282.PNG)
legendary proc has procced (and not faded) and on the action bar you can see ascendance still off cd. Fixed.
