### ISSUE TITLE
Trailblazer doesn't disappear with melee aa

### ISSUE THREAD

**Issue by Nianel** [SimCMinMax/WoW-BugTracker#65]
**Game Version:**
> 8.0.1 Alpha Build 25976

**Description:**
> The talent Trailblazer doesn't disappear when you do auto attack at melee on Survival

**Details:**
> https://gyazo.com/39a0ed8280be579e98fdfe38070bde44

**Reproducible:**
> Yes

**Howto:**
> Take the talent Trailblazer and auto attack

**Comment by Pewtro** [comment]
Fixed in 35944.
