### ISSUE TITLE
Elemental Equilibrium does not affect Echoing Shock

### ISSUE THREAD

**Issue by Bloodmallet** [SimCMinMax/WoW-BugTracker#654]
**Game Version:**
> 9.0.2 beta Build 35854

**Description:**
> Echoing Shock deals Elemental damage, thus should consume all Elemental Equilibrium buffs, just like Elemental Blast. But it doesn't.

**Logs, Images, Videos**
> Please attach Logs, Images, and/or a Video of the bug if applicable.

**Reproducible:**
> yes

**Howto:**
- Lightning Bolt -> Frost Shock -> Echoing Shock; Echoing Shock does not consume buffs, is not empowered

**Comment by nixlnixlnixl** [comment]
The legendary effect was reworked to 

> dealing direct fire/frost/nature dmg within 10 seconds will increase all damage dealt by 15% for 10 seconds. This can only occur once every 30 seconds

On its iteration It continued to not work with Echoing shock which only contributed the fire portion of the requirement. However.

game version 9.0.2 beta build 36512 it now works as intended.
![eeq](https://user-images.githubusercontent.com/73984865/98212675-9e600300-1f4c-11eb-9631-9b6989138e37.PNG)
