### ISSUE TITLE
High Voltage grants wrong Maelstrom value

### ISSUE THREAD

**Issue by Bloodmallet** [SimCMinMax/WoW-BugTracker#659]
**Game Version:**
> 9.0.2 beta Build 35854

**Description:**
> High Voltage grants 6 Maelstrom, even though Lightning Bolt grants 8.

**Logs, Images, Videos**
![image](https://user-images.githubusercontent.com/9075987/93024099-fb49d780-f5f3-11ea-87df-6c23d43e8056.png)

**Reproducible:**
> yes

**Howto:**
> Lightning Bolt; see proc giving wrong Maelstrom amount

**Comment by nixlnixlnixl** [comment]
9.0.2 beta Build 36512
![hv](https://user-images.githubusercontent.com/73984865/98214974-dae12e00-1f4f-11eb-9216-4a54ea8de05c.PNG)
works
