### ISSUE TITLE
Birds of Prey doesn't extend the duration of Aspect of the Eagle

### ISSUE THREAD

**Issue by Nianel** [SimCMinMax/WoW-BugTracker#66]
**Game Version:**
> 8.0.1 Alpha Build 25976

**Description:**
> Birds of Prey doesn't extend the duration of Aspect of the Eagle when you do your Raptor strike at the same target of your pet

**Details:**
> https://gyazo.com/3d710886a28e7939d998e35735c7aa8b

**Reproducible:**
> Yes

**Howto:**
> Take the talents Birds of Prey and hit the same target of your pet with the buff of Aspect of the Eagle

**Comment by nuoHep** [comment]
In one of the builds the talent was changed to extend the duration of Coordinated Assault, as AotE is now an 'utility' cooldown. And as of the latest build (at least) it's now properly extending CA.
