### ISSUE TITLE
Echoed Lightning Bolts don't stack Wind Gust

### ISSUE THREAD

**Issue by Bloodmallet** [SimCMinMax/WoW-BugTracker#660]
**Game Version:**
> 9.0.2 beta Build 35854

**Description:**
> Echoing Lightning Bolt during Storm Elemental does not grant a Wind Gust stack.

**Logs, Images, Videos**
![image](https://user-images.githubusercontent.com/9075987/93024141-6dbab780-f5f4-11ea-95a5-4483a6865cc3.png)

**Reproducible:**
> yes

**Howto:**
> Storm Elemental -> Echoing Shock -> Lightning Bolt; no

**Comment by nixlnixlnixl** [comment]
game version: 9.0.2 beta Build 36512
![gust](https://user-images.githubusercontent.com/73984865/98210057-a74ed580-1f48-11eb-84f5-9cd0fb8b2f4c.PNG)
echo grants the stack now.
