### ISSUE TITLE
Damage increase from Bloodshed does not affect second pet from Animal Companion

### ISSUE THREAD

**Issue by Pewtro** [SimCMinMax/WoW-BugTracker#662]
**Game Version:**
> 9.0.2 beta Build 35854

**Description:**
> Bloodshed debuff only gives main pet a damage increase.
> This means that when specced into Animal Companion, you're nerfing your pet damage by 35% (from Animal Companion) and thus gaining much less value from Bloodshed since it only affects main pet and not the secondary pet. 

**Reproducible:**
> yes

**Howto:**
> Spec into Animal Companion and Bloodshed.
> Note the damage both pets do with their melee attacks without bloodshed debuff and with the bloodshed debuff.
> Notice how main pet damage goes up, but secondary pet damage does not.

**Comment by nuoHep** [comment]
I'd frame this as `Animal Companion pet does not perform Bloodshed`.
Given how the AC pet is supposed to be an almost full blown 2nd pet - it does everything the main pet does apart form basic attacks and gains almost all of the buffs the main pet gets (apart from AotW) - it makes sense that it should perform Bloodshed too. Which would automatically make it benefit from it.

**Comment by Pewtro** [comment]
Fixed in 9.0.2.36206
