### ISSUE TITLE
Grove Invigoration (Soulbind Ability-Night Fae- Niya) not giving Mastery bonus when triggered via Sepsis

### ISSUE THREAD

**Issue by ZeraTheRedRogue** [SimCMinMax/WoW-BugTracker#668]
**Game Version:**
> 9.0.2 beta Build 35938

**Description:**
> The Redirected Anima buff from Grove Invigoration is giving the maximum health bonus, but is giving 0 mastery. This ability was changed in the most recent build from giving a flat % gain of mastery per stuck to a numerical value of mastery, however it now is giving 0 Mastery regardless of how many stacks you have. Not sure if other classes are having the same issue with their Night Fae class ability, definitely occurring with Sepsis, though.

**Reproducible:**
> Yes

**Howto:**
> Use Niya as your soulbind. Activate Grove Invigoration. Gain stacks of Redirected Anima, cast sepsis and not no change in mastery value. Buff even shows 0 mastery is being applied.

**Comment by Mystler** [comment]
Fixed in 36512.
