### ISSUE TITLE
Flagellation (323654) Not Applying If Already Applied By Other Rogue

### ISSUE THREAD

**Issue by Scathic** [SimCMinMax/WoW-BugTracker#680]
**Game Version:**
> 9.0.2 beta Build 35978

**Description:**
> The instant spell will trigger, but no slashes will build if another rogue already has the slash debuff applied to the target.

**Logs, Images, Videos**
> n/a

**Reproducible:**
> Yes

**Howto:**
> Have two rogues hit the same training dummy.

**Comment by Mystler** [comment]
Has been fixed in one of the last builds.
