### ISSUE TITLE
Flagellation's Range is not affected by the Acrobatic Strikes talent

### ISSUE THREAD

**Issue by ZeraTheRedRogue** [SimCMinMax/WoW-BugTracker#681]
**Game Version:**
> 9.0.2 beta Build 35978

**Description:**
Flagellation's range is not improved when running the talent Acrobatic Strikes.

**Reproducible:**
Yes

**Howto:**
Go Venthyr as a Rogue, learn Flagellation from your covenant, go into Outlaw specialization, observe no range change when using Acrobatic Strikes as a talent.

**Comment by Mystler** [comment]
Appears to be fixed.
