### ISSUE TITLE
Wild Spirits triggers multiple times from certain spellcasts

### ISSUE THREAD

**Issue by Kedrihan** [SimCMinMax/WoW-BugTracker#684]
**Game Version:**
> 9.0.2 beta Build 35978

**Description:**
The rework of hunter's Wild Spirits makes damage on 5 target proc at each shot instead of at each spell cast
Not intended by Blizzard -> https://us.forums.blizzard.com/en/wow/t/feedback-hunter-class-changes/490705/943

**Reproducible:**
Yes

**Howto:**
Cast Wild Spirit on several mobs, then use Rapid Fire for example -> each shot of Rapid Fire will trigger the damage on 5 targets
Also works with Barrage and Volley

**Comment by Kedrihan** [comment]
Now, with the hotfix, WIld Spirits does not trigger from certain spells : https://us.forums.blizzard.com/en/wow/t/feedback-hunter-class-changes/490705/971

**Comment by Pewtro** [comment]
In build 9.0.2.36086, this was changed once more now it again triggers off every hit from Aimed Shot and Chimaera shot

**Comment by Pewtro** [comment]
As per build 9.0.2.36532 this is the status of Wild Spirits and multi proccing:
* Barbed Shot w/Stomp will proc it twice (3 times with Animal Companion)
* Bestial Wrath initial hit with Animal Companion will proc it twice
* A Double tapped Aimed Shot will proc it twice at close range, but not at far range
* Aimed Shot with the new serpentstalker legendary will proc it twice (which can be combined with Double Tap for 3-4 procs)

**Comment by Pewtro** [comment]
As of build 36753 - this is now happening with Bursting Shot. 
![image](https://user-images.githubusercontent.com/29204244/100555358-2ced4900-329b-11eb-8bb7-270a7eac0d46.png)

**Comment by Pewtro** [comment]
Bursting Shot was hotfixed, so was interactions with Animal Companion. 

This means that the status as of 1st December: 

- A Double tapped Aimed Shot will proc it twice at close range, but not at far range
- Aimed Shot with the new serpentstalker legendary will proc it twice (which can be combined with Double Tap for 3-4 procs)
- Barbed Shot w/Stomp will proc it twice
- Dire Beast with Stomp will proc it twice.

**Comment by Pewtro** [comment]
As of 13th February the following still double proc Wild Spirits:
- A Double tapped Aimed Shot will proc it twice at close range, but not at far range
- Barbed Shot w/Stomp will proc it twice
- Dire Beast with Stomp will proc it twice.

**Comment by Pewtro** [comment]
Not relevant once we leave Shadowlands - closing.
