### ISSUE TITLE
Vesper Totem is not affected by Elemental Fury

### ISSUE THREAD

**Issue by Bloodmallet** [SimCMinMax/WoW-BugTracker#688]
**Game Version:**
> 9.0.2 beta Build 35978

**Description:**
> Damage explosions and healing explosions of Vesper Totem crit for 200% instead of 250%.

**Logs, Images, Videos**
> Please attach Logs, Images, and/or a Video of the bug if applicable.

**Reproducible:**
> yes

**Howto:**
> Cast a criting Vesper Totem

**Comment by nixlnixlnixl** [comment]
game version: 9.0.2 beta Build 36512
![vesperheal](https://user-images.githubusercontent.com/73984865/98209637-efb9c380-1f47-11eb-915d-15f0e36a33e7.PNG)
![vesper damage](https://user-images.githubusercontent.com/73984865/98209638-f0525a00-1f47-11eb-8bc4-80e2ffd85271.PNG)
both healing and dmg going to 250%
