### ISSUE TITLE
Primordial Wave is not affected by Elemental Fury

### ISSUE THREAD

**Issue by Bloodmallet** [SimCMinMax/WoW-BugTracker#689]
**Game Version:**
> 9.0.2 beta Build 35978

**Description:**
> Primordial Wave crits for 200% instead of 250%.

**Logs, Images, Videos**
> Please attach Logs, Images, and/or a Video of the bug if applicable.

**Reproducible:**
> yes

**Howto:**
> Cast a criting Primordial Wave

**Comment by nixlnixlnixl** [comment]
game version: 9.0.2 build 36512
![Ca123123qweasdqepture](https://user-images.githubusercontent.com/73984865/98209149-1f1c0080-1f47-11eb-9cce-6dfafceb728a.PNG)
seems to be at 250% now.
