### ISSUE TITLE
Saber Slash extra attack grants no additional combo point.

### ISSUE THREAD

**Issue by weakweak** [SimCMinMax/WoW-BugTracker#70]
**Game Version:**
> 8.0.1 Alpha Build 25976

**Description:**
> Saber Slash extra attack grants no additional combo point.

**Details:**
> -
https://www.warcraftlogs.com/reports/Hc1TC3wBhmgFGMLz/#fight=last&type=resources&source=1&pins=0%24Separate%24%23244F4B%24damage%240%240.0.0.Any%246326793.0.0.Rogue%24true%240.0.0.Any%24false%24193315%5E0%24Separate%24%23909049%24damage%240%240.0.0.Any%246326793.0.0.Rogue%24true%240.0.0.Any%24false%24197834&spell=104&view=events

**Reproducible:**
> 100%

**Howto:**
> Press Saber Slash over and over again

**Comment by Mystler** [comment]
This was an intentional change. Closing the issue.
