### ISSUE TITLE
Reverberating Strike anima power doesn't deal damage for 20 CPs

### ISSUE THREAD

**Issue by TheMangoFuture** [SimCMinMax/WoW-BugTracker#700]
**Game Version:**
> 9.0.2 beta Build 35978

**Description:**
> The Anima power "Reverberating Strike" says when you use the Animacharged CP on a finisher, it will deal damage as if it used 20 Combo Points. This isn't happening for at least Eviscerate.

**Logs, Images, Videos**
> Attaching a screenshot of me using Eviscerate on the animacharged CP.

**Reproducible:**
> Yes

**Howto:**
> Get this anima power in Torghast, and use Eviscerate on the animacharged CP. 

![Eviscerate dealing 5.8k damage on a crit ](https://user-images.githubusercontent.com/36246534/94980737-93075b00-04fa-11eb-8bea-d3beffbe772c.png)

**Comment by TheMangoFuture** [comment]
At my current ilvl, Eviscerate does an extra 519 damage per rank. A 20CP Eviscerate should do 10,379 damage baseline if my math is right.

**Comment by TheMangoFuture** [comment]
Doesn't look like Shadow Vault works either

**Comment by Mystler** [comment]
Appears fixed in 36512.
