### ISSUE TITLE
Hypothermic Presence bugs rune costs

### ISSUE THREAD

**Issue by Chewsdaydk** [SimCMinMax/WoW-BugTracker#702]
**Game Version:**
> 9.0.2 beta Build 35978

**Description:**
> Originally reported in #447, Hypothermic Presence allows you to Obliterate with 1 Rune while active, and will not let you obliterate again until you have 3 runes after it expires. Previously it reduced RP generation while active but this is fixed now.

**Logs, Images, Videos**
> https://www.youtube.com/watch?v=8jPfXHcYlyc&ab_channel=chewsday

**Reproducible:**
> yes

**Howto:**
> Easiest to replicate by casting Hypothermic Presence with 1 rune available, then cast Obliterate over and over again and both parts of the bug will be obvious.

**Comment by Melekus** [comment]
Fixed as of 2020-11-03.

Probably fixed on build 36294 when the effect data for Hypothermic Presence was changed from 'All Schools' to 'Frost'.
https://github.com/simulationcraft/simc/commit/e783598b0db51a5fd9ff3b3ba4efadf3c32d4ed1#diff-95ef87f674802e1f56927997015eb82ecd44f7d59788e0146fd31e8b19f646a7L13161
