### ISSUE TITLE
Dwarf Death Knights start with less bag space than the other races.

### ISSUE THREAD

**Issue by Melekus** [SimCMinMax/WoW-BugTracker#710]
**Game Version:**
> 9.0.1 PTR Build 35989

**Description:**
> With the revamped death knight starting experience, every race can now be a death knight, starting either at level 8 or level 10. Dwarves are the only race to start with their backpack and only one deathweave bag (12 slot). All the other races start with their backpack and 4 deathweave bags instead, for an additional 36 slots of inventory.

**Reproducible:**
> Yes.

**Howto:**
> Create a Dwarf death knight and compare its inventory size to any other races' death knight.

**Comment by cetraben** [comment]
![image](https://user-images.githubusercontent.com/25280504/96273336-234ba280-0fc7-11eb-9cb4-e8ac414054b7.png)

Looks to be resolved now.
