### ISSUE TITLE
Dire Command legendary triggers twice as often when talented into Animal Companion 

### ISSUE THREAD

**Issue by Pewtro** [SimCMinMax/WoW-BugTracker#711]
**Game Version:**
> 9.0.2 beta Build 36165

**Description:**
> Dire Command is a 15% proc chance. However when talented into Animal Companion - we're seeing a 30% proc chance. 

**Logs, Images, Videos**
> https://www.warcraftlogs.com/reports/M6pBkJN7Rtqgd3wX/#fight=last&source=7&type=damage-done
As you can see, a total of 3443 Kill Command casts (button presses);
https://www.warcraftlogs.com/reports/M6pBkJN7Rtqgd3wX/#fight=last&source=7&type=auras
And 1027 Dire Beast procs. That is roughly a 29.83% proc chance.

**Reproducible:**
> Examples: yes

**Howto:**
> Talent into Animal Companion and use the Dire Command legendary and hit Kill command. 
> Do the same without talented into Animal Companion and it'll much rarer

**Comment by Pewtro** [comment]
The talent version of this in DF suffers the same problem.

**Comment by Tralololo** [comment]
As of 2022-10-24 the Talent version of this is fixed on PTR and Beta.

**Comment by Pewtro** [comment]
Since the legendary is the only one affected, and it becomes irrelevant come DF launch - closing.
