### ISSUE TITLE
Unleashed Frenzy Conduit provides less strength than expected

### ISSUE THREAD

**Issue by nyterage** [SimCMinMax/WoW-BugTracker#714]
**Game Version:**
> 9.0.2 beta Build 36086

**Description:**
> Unleashed Frenzy, a conduit for Frost Death Knight, provides less of a strength increase than expected. 

**Logs, Images, Videos**
> 0 Stacks as a baseline
> https://imgur.com/Qv6waFl
>
> 1 Stack of Unleashed Frenzy
> https://imgur.com/vHBNfLK
>
> 2 Stacks of Unleashed Frenzy
> https://imgur.com/YhirXPw

**Reproducible:**
> Yes

**Howto:**
> Ensure you have gear that provides strength equipped
> Equip Unleashed Frenzy to your soulbind
> Trigger Unleashed Frenzy's strength buff
> Observe strength increase versus expected increase.

**Comment by Melekus** [comment]
The spelldata for Unleashed Frenzy shows 
```
#1 (id=837178)   : Apply Aura (6) | Modify Attribute% (80)
                   Base Value: 0 | Scaled Value: 0 | PvP Coefficient: 1.00000 | Target: Self (1)
```

Modify Attribute% (80) buffs increase only the base stats of a player, so Unleashed Frenzy only increases strength by 5% of the strength gained with levels.

Other strength increasing effects like Pillar of Frost show usage of Modify Total Stat% (137) instead, and increase strength by the correct amount ingame.
```
#1 (id=43590)    : Apply Aura (6) | Modify Total Stat% (137)
                   Base Value: 10 | Scaled Value: 10 | PvP Coefficient: 0.66667 | Misc Value 2: 0x1 | Target: Self (1)
```

**Comment by Ceriloch** [comment]
"Modify Attribute% (80) buffs increase only the base stats of a player, so Unleashed Frenzy only increases strength by 5% of the strength gained with levels."  Is there any good way to know what the effects do?  Generally I've looked through the various apply_effecting_aura family and found the affect and seen what was done there, and matched that implementation, but in this case, there was no implementation.  For ones like this, is there some reference somewhere that can be used? or is this really just a time & experience thing to learn?

Built for war in player/soulbinds.cpp was the only place I could find any sort of mention in the source for using an A_MOD_PERCENT_STAT (80) and it looks like they were just applying it to the whole stat as well.  So there may be a bug with that one too.

Looking through SpellData/allspells.txt there doesn't look to be very many things that are using "Modify Attribute%".

Any pointers on where to start searching for how to get this one to apply properly?

**Comment by Melekus** [comment]
Effect label changed in spelldata to Modify Stats (137) as of beta build 36206.

**Comment by Chewsdaydk** [comment]
this should be fixed?
