### ISSUE TITLE
Nessingwary's Trapping Apparatus legendary does not work with Steel Trap or Hi-Explosive Trap

### ISSUE THREAD

**Issue by Ghosteld** [SimCMinMax/WoW-BugTracker#717]
**Game Version:**
> 9.0.2 beta Build 36086

**Description:**
> The legendary does not give focus or the focus regen buff whenever Steel Trap or Hi-Explosive Trap Triggers

**Logs, Images, Videos**
> Please attach Logs, Images, and/or a Video of the bug if applicable.
![trap leggo bug](https://user-images.githubusercontent.com/40084807/96193507-98c45e00-0f48-11eb-8a5c-941a38028d01.png)

**Reproducible:**
> Yes, always

**Howto:**
>Throw trap and notice that you don't get the focus or the focus regen buff.

**Comment by Pewtro** [comment]
As of build 9.0.2.36532 this works with Steel Trap - but not Hi-Explosive.

**Comment by Pewtro** [comment]
Not relevant once we leave Shadowlands - closing.
