### ISSUE TITLE
Soul of the Archmage is granting completely different talents

### ISSUE THREAD

**Issue by vituscze** [SimCMinMax/WoW-BugTracker#72]
**Game Version:**
> 8.0.1 Alpha Build 25976

**Description:**
> Soul of the Archmage is now granting Alexstrasza's Fury for Fire and Splitting Ice for Frost.

**Reproducible:**
> yes

**Howto:**
> Buy the ring at the legendary vendor.

**Comment by RosvallM** [comment]
General issue opened here: https://github.com/SimCMinMax/WoW-BugTracker/issues/97
Closed as duplicate.
