### ISSUE TITLE
Unholy Death Knight's Reanimated Shambler (Necroblast) has a base damage value

### ISSUE THREAD

**Issue by Chewsdaydk** [SimCMinMax/WoW-BugTracker#725]
**Game Version:**
> 9.0.2 beta Build 36086

**Description:**
> Necroblast from Reanimated Shambler appears to have a base/scaled value in addition to regular ap coefficient, which seems to be around 150 at level 60.

**Logs, Images, Videos**
> Please attach Logs, Images, and/or a Video of the bug if applicable.
![image](https://user-images.githubusercontent.com/39236684/96455244-dc52ec80-1214-11eb-80ab-528518e078ef.png)

`Effects          :
#1 (id=831038)   : School Damage (2): shadow
                   Base Value: 1 | Scaled Value: 1 | AP Coefficient: 1.50000 |`

**Reproducible:**
yes

**Howto:**
> Calculate expected damage using ap coefficient like above sheet and disparity is clear and consistent

**Comment by Chewsdaydk** [comment]
more info here https://github.com/simulationcraft/simc/pull/5432#issuecomment-711435656

**Comment by Khazakdk** [comment]
Appears to be fixed as of build 36532.  Ran through a handful of the gear sets used to generate the above spreadsheet and got in game results that lined up with the math.  (The +- 2.5% seems to be applying now as well)

**Comment by Chewsdaydk** [comment]
fixed
