### ISSUE TITLE
Dire Command tooltip does not indicate that the legendary effect might not work for offspecs.

### ISSUE THREAD

**Issue by Thyminde** [SimCMinMax/WoW-BugTracker#730]
**Game Version:**
9.0.2 beta Build 36267

**Description:**
Dire Command does not work for SV, despite the tooltip suggesting that it might. simply stating "Kill Command has a 10% chance to also summon a Dire Beast to attack your target."

Even though the legendary itself isnt craftable as SV directly. And likely isnt intended to work for Survival, players would be no stranger to the concept of swapping specializations for this purpose. As similar would be done in order to select azerite traits that were not neccesarily intended to work, but still (partially) worked for offspecs. for instance igneous potentional for elemental/restoration shaman. or death throes for priests.

The legendary effect also appears to be based directly on the azerite trait "dire concequences" which has worked for Survival throughout BFA, further adding to potentional confusion,

**Reproducible:**
yes

**Howto:**
Equip a legendary with Dire Command, and spam kill command for an extended period of time as Survival, and note how it does not proc. nor does the tooltip grey out, or otherwise indicate it may not work.

**Comment by nuoHep** [comment]
Fixed in 36401
