### ISSUE TITLE
Bonus Objectives "Stopping Zardrax" in Nazmir: Sound of destroyed totems delayed and too loud

### ISSUE THREAD

**Issue by Bloodmallet** [SimCMinMax/WoW-BugTracker#74]
**Game Version:**
> 8.0.1 Alpha Build 25976

**Description:**
> Sound of destroyed totems is delayed and a lot louder than all other sounds.

**Details:**
> When doing the Bonus Objective "Stopping Zardrax" the sound of a destroyed totem (there are plenty to destroy) is too loud and delayed by roughly a second. 
![image](https://user-images.githubusercontent.com/9075987/36054050-b1df15b8-0df4-11e8-85b5-de177b78e9f3.png)

**Reproducible:**
> yes

**Howto:**
> Have Bonus Objective active, destroy such a totem.

**Comment by Kutikuti** [comment]
Fixed in 26491
