### ISSUE TITLE
Crimson Tempest does not proc Elaborate Planning

### ISSUE THREAD

**Issue by Zarania** [SimCMinMax/WoW-BugTracker#75]
**Game Version:**
8.0.1 Alpha Build 25976

**Description:**
Crimson Tempest does not proc Elaborate Planning despite being a finishing move

**Reproducible:**
Yes

**Howto:**
Spec both talents, cast Crimson Tempest

**Comment by Mystler** [comment]
Fixed in 8.0.1.26095.
