### ISSUE TITLE
Nesingwary's Trapping Apparatus legendary power does not affect passive focus regeneration.

### ISSUE THREAD

**Issue by Thyminde** [SimCMinMax/WoW-BugTracker#751]
**Game Version:**
> 9.0.2 beta Build 36532

**Description:**
> Nesingwary's Trapping Apparatus does not affect passive focus regeneration. despite the tooltip mentioning `"... and increase all Focus gained by 100% for 5 sec."` Active focus generators, including the legendary itself work fine and are increased by 100%.

**Reproducible:**
> Always

**Howto:**
>Equip a Shadowlands legendary with the Nesingwary's Trapping Apparatus power. And take note of your passive focus regeneration after activating it. Alternatively use  ` /script DEFAULT_CHAT_FRAME:AddMessage(GetPowerRegen())` to print your focus regeneration to the chatframe.

**Comment by Pewtro** [comment]
Not relevant once we leave Shadowlands - closing.
