### ISSUE TITLE
Hunter Scopes are not affected by Nadija Exacting Preparation Soulbind Trait

### ISSUE THREAD

**Issue by Ghosteld** [SimCMinMax/WoW-BugTracker#755]
**Game Version:**
> 9.0.2 beta Build 36294

**Description:**
> The Nadija Exacting Preparation Soulbind trait does not increase the benefit of both hunter scopes. ( Infra-Green Reflex Sight and Optical Target Embiggener

**Logs, Images, Videos**
> Please attach Logs, Images, and/or a Video of the bug if applicable.
Without the trait:
![Nadija without bug](https://user-images.githubusercontent.com/40084807/99678854-8ffd0580-2a7b-11eb-8788-84cc4c8c6285.png) and with the trait:
![Nadija with bug](https://user-images.githubusercontent.com/40084807/99678880-95f2e680-2a7b-11eb-8709-c7c882f61adf.png)

**Reproducible:**
> Always.

**Howto:**
> Look at your crit or haste rating without the trait and then with the trait and see how both ratings are the same when the scopes proc.

**Comment by Pewtro** [comment]
This has been fixed at some point.

**Comment by Pewtro** [comment]
Nevermind still bugged 😃

**Comment by Pewtro** [comment]
Not relevant once we leave Shadowlands - closing.
