### ISSUE TITLE
Secrets of the Unblinking Vigil buff is consumed on impact

### ISSUE THREAD

**Issue by nuoHep** [SimCMinMax/WoW-BugTracker#760]
**Game Version:**
> 9.0.2 beta Build 36710

**Description:**
> Secrets of the Unblinking Vigil buff gets consumed on Aimed Shot impact (instead of cast).
> Heavily penalizes casting Multi-Shot after an Aimed Shot because the buff gets effectively wasted (as it's a focus reducing buff which requires a cast) if it procs, removing half of the benefit of the legendary.

**Logs, Images, Videos**
> Aimed Shot -> Multi-Shot. An in-flight Aimed Shot consumes the just procced Secrets of the Unblinking Vigil buff.
> ![image](https://user-images.githubusercontent.com/59478/99920316-bb117e80-2d33-11eb-9e7a-05dd85d48ce6.png)

**Reproducible:**
> yes

**Howto:**
> * Equip Secrets of the Unblinking Vigil legendary
> * Cast Aimed Shot
> * Cast Multi-Shot
> * Repeat the above 2 steps until Vigil procs
> * Observe how the buff gets consumed by the in-flight Aimed Shot

**Comment by Pewtro** [comment]
Fixed according to https://blue.mmo-champion.com/topic/1112335-hotfixes-december-1-2020/
