### ISSUE TITLE
Arcane Echo triggers on the Mage's target instead of Touch of the Magi's target

### ISSUE THREAD

**Issue by Dorovon** [SimCMinMax/WoW-BugTracker#762]
**Game Version:**
> 9.0.2 live Build 36753

**Description:**
> The Arcane Mage talent Arcane Echo triggers a pulse of damage when the Mage deals damage to the target Touch of the Magi is active on. Instead of triggering on that target, the Arcane Echo will trigger on the enemy the Mage has targeted.
https://www.youtube.com/watch?v=aLtxSlacENQ

**Reproducible:**
> yes

**Howto:**
> Cast Touch of the Magi on an enemy, begin casting a spell that will trigger Arcane Echo, and target a different enemy.

**Comment by ArcanePorom** [comment]
This was fixed as of 10.2.

**Comment by ArcanePorom** [comment]
This was fixed as of 10.2.
