### ISSUE TITLE
Shadowcore oil interrupts Steady Focus buff.

### ISSUE THREAD

**Issue by Ghosteld** [SimCMinMax/WoW-BugTracker#765]
**Game Version:**
> 9.0.2 live Build 36753

**Description:**
> Whenever Shadowcore oil, the weapon enchant, procs in between 2 steady shots then we don't gain our talent Steady Focus buff.

**Details:**
> Steady Focus requires 2 Steady Shots in a row to give us the Steady Focus buff. Whenever Shadowcore oil (a weapon enchant) procs after a Steady Shot then the second Steady Shot won't give us Steady Focus. 

**Logs, Images, Videos**
> 
![steady focus](https://user-images.githubusercontent.com/40084807/100634975-3b397480-3330-11eb-8378-1330153b6795.png)

**Reproducible:**
> Always.

**Howto:**
> Shoot Steady Shot, see if Shadowcore Oil procs then shoot Another Steady Shot and notice how you don't gain Steady Focus.

**Comment by Pewtro** [comment]
This has been hotfixed 30th November https://worldofwarcraft.com/en-gb/news/23580183/hotfixes-november-30-2020
