### ISSUE TITLE
Echoing Reprimand is Applying Find Weakness for Outlaw and Assassination

### ISSUE THREAD

**Issue by EvanMichaels** [SimCMinMax/WoW-BugTracker#787]
**Game Version:**
> 9.0.2 live Build 36753

**Description:**
> If using Echoing Reprimand from Stealth or Vanish, an 18 second Find Weakness buff is applied for non-Subtlety specs.

**Logs, Images, Videos**
> https://www.warcraftlogs.com/reports/BA9JwqVtKm6Q3cfn/#fight=last&type=damage-done&pins=0%24Separate%24%23244F4B%24auras-gained%241%240.0.0.Any%240.0.0.Any%24true%240.0.0.Any%24false%24316220&view=events&ability=323547

**Reproducible:**
> 100%

**Howto:**
> Use Echoing Reprimand from Stealth or Vanish as Outlaw or Assassination specialization

**Comment by Mystler** [comment]
Hearing this has been fixed on 9.0.5 PTR now.
