### ISSUE TITLE
Sepsis allows the use of an additional Stealth ability if combined with Vanish

### ISSUE THREAD

**Issue by fuu1** [SimCMinMax/WoW-BugTracker#788]
**Game Version:**
> 9.0.2 live Build 36753

**Description:**
>If you use Vanish shortly before the the sepsis buff get applied you are able to use an additional stealth ability before consuming the sepsis buff. The practical use/impact of the bug is rather low.

**Logs, Images, Videos**
> Video: [link](https://cdn.discordapp.com/attachments/398549488723296258/795014901067808808/subtlety.mp4)

**Reproducible:**
> Easy

**Howto:**
> Use Sepsis and use Vanish shortly (tested with ~.5 sec) before the debuff runs out, continue by using a stealth ability (Shadowstrike/Ambush).

**Comment by fuu1** [comment]
You can use a Finisher between the stealth casts too. 
This means you can do:
stealth ability - finisher - stealth ability - stealth ability or
stealth ability - stealth ability - finisher - stealth ability
what makes it more useful than initially anticipated.

**Comment by Mystler** [comment]
Still the case on 9.0.5 PTR. Easy to reproduce, does not seem to work if Shadowstrike weaponmasters though.

**Comment by Mystler** [comment]
It looke like this has been fixed by reverting to the previous bug that Vanish and Sepsis are consumed together again.

**Comment by Mystler** [comment]
Closing in favor of the new issue #872.
