### ISSUE TITLE
Releasing spirit occasionally pulls mobs across the dungeon

### ISSUE THREAD

**Issue by vituscze** [SimCMinMax/WoW-BugTracker#793]
**Game Version:**
> 9.0.2 live Build 36753

**Description:**
> Sometimes, dying on a trash pack and releasing causes the player to immediately enter combat and aggro the same trash pack. This happens even if the trash pack is nowhere near the respawn point. This issue seems to be affecting mostly Frost mages at the moment.

**Details:**
> Sometimes, this is caused by an active Frozen Orb which continues doing damage after the player releases. However, this also happens quite often without any obvious cause whatsoever.

**Reproducible:**
> rarely

**Howto:**
> Pull a trash pack with a group, die, and release. Sometimes, the mage immediately enters combat and the trash pack starts running towards them.

**Comment by Valaran1** [comment]
https://www.twitch.tv/videos/885194186

**Comment by donkeyman69** [comment]
Exactly the same thing as happened to Valaran1 happens to me at least once a day (about 5-10 dungeons), got Shadow Play running now to catch them and ta-dah one popped up literally the run after I activated it.

[video](https://www.youtube.com/watch?v=7QZ_YmjWAGo)

Also notice that Frost Orb wasn't used, even close to the pack resetting, only on pull and then even was back up before dying.

**Comment by donkeyman69** [comment]
[Second dungeon of the day and it happens again =)](https://www.youtube.com/watch?v=BOleYhceWyk)

**Comment by vituscze** [comment]
Might have been fixed in 9.1. Will reopen if we get new reports.
