### ISSUE TITLE
Shiv does not work with Broadside

### ISSUE THREAD

**Issue by Vaughn1234** [SimCMinMax/WoW-BugTracker#801]
**Game Version:**
> 9.0.2 live Build 36753

**Description:**
> Both the 20% increased damage as well as the extra Combo Point of Shiv does not work with Broadside.

**Details:**
> This makes it the only builder not working with Broadside. Also, Shiv does work with Shadowblades for Subtlety.

**Logs, Images, Videos**
> 

https://user-images.githubusercontent.com/77858896/105577866-84c89d80-5d7c-11eb-9eda-17dbe0e43fa3.mp4

**Reproducible:**
> yes

**Howto:**
> Use Shiv while having the Broadside buff.

**Comment by EvanMichaels** [comment]
Fixed in 9.1
