### ISSUE TITLE
Brutal Projectiles applies increased damage buff late

### ISSUE THREAD

**Issue by AllSkillzzz** [SimCMinMax/WoW-BugTracker#803]
**Game Version:**
> 9.0.2 live Build 36753

**Description:**
> The marksmanship conduit Brutal Projectiles has major bugs.

**Details:**
> The conduit calculates the stacks on shots hit and not fired, this causes the conduit to bug an not get max stacks whenever you are further from melee range and even in melee range you still cant get max stacks. This bug has been around since beta and has yet to be addressed, 

**Logs, Images, Videos**
> https://clips.twitch.tv/HedonisticHeadstrongStarLitty
Here is a clip of it not working properly from melee range,
i fire 14 shots an get 12 stacks only, my buff ends and no enhanced damage from the last 2 shots, due to the buff starting late.
> https://clips.twitch.tv/HeadstrongSavageLouseTBCheesePull
> Another clip this time from decent range, which as a marks hunter you wanna be, you get less than half benefit if you are further from your target, but you still never get full benefit even if you are melee range, the buff ends after the channel and the shots have not connected yet.

**Reproducible:**
> Yes, very easy to test and show.

**Howto:**
> Can be reproduced anytime you have brutal projectiles buff up and then start the rapidfire channel, depending on the distance you are from the target then you will get either 12 stacks using a double tapped rapidfire or 6 stacks if a normal rapidfire, this is still below the shots fired which is 14 with double tap and 7 without it.

**Comment by Pewtro** [comment]
Fixed on PTR
