### ISSUE TITLE
Venomous Wounds change not in effect 

### ISSUE THREAD

**Issue by ZeraTheRedRogue** [SimCMinMax/WoW-BugTracker#807]
**Game Version:**
> 9.0.1 PTR Build 35989

**Description:**
> The Venomous Wounds passive tooltip and energy granted is still 7, not 8 as patch notes imply.

**Reproducible:**
> Yes

**Howto:**
> (Using Details) The Energy Generated while a single target has a garrote and is poisoned will show upticks of 7 at a time, not 8.

**Comment by Mystler** [comment]
Should be fixed with 9.0.5 PTR Build 37705.
