### ISSUE TITLE
Serrated Bone Spike Assassination Mastery Change is Inconsistent

### ISSUE THREAD

**Issue by EvanMichaels** [SimCMinMax/WoW-BugTracker#809]
**Game Version:**
> 9.0.5 PTR Build 37623

**Description:**
> Serrated Bone Spike was added to the Mastery: Potent Assassin whitelist in the initial 9.0.5 PTR build, however it was only added to the Spell Direct Amount modifier (Effect 1) and not to the Spell Periodic Amount (Effect 2.) This seems odd since the direct portion is not considered a Bleed (and is pure Physical damage) while the periodic is.

**Comment by Mystler** [comment]
With 9.0.5 PTR Build 37705, all of it is now affected by Mastery. Whether the direct damage is a "bleed" is probably up for debate but at least the spell data goal of mastery scaling was achieved now.
