### ISSUE TITLE
Doomblade / Mutilated Flesh damage is using target modifiers from debuff amps

### ISSUE THREAD

**Issue by EvanMichaels** [SimCMinMax/WoW-BugTracker#812]
**Game Version:**
> 9.0.2 live Build 36753

**Description:**
> This is an issue that appeared in beta but was fixed towards the end of beta. However it appears to have resurfaced on live. Although the second Mutilate hit is refreshing the DoT, it is not dealing the correct amount of residual damage. This is causing the Legendary to deal significantly less damage than it is intended to.

**Details:**
> In the log below, the first hit is 679, the second is 328. This immediately pandemics up with a refresh visible in the logs. The DoT then ticks 3 times for 71 damage. The total DoT damage should be 302, but is only 213. It is not that it is totally ignoring the OH hit, as it triggers a refresh and OH crits are shown to bias the damage. However, it is somehow losing residual damage or a tick--perhaps due to the pandemic duration and odd tick rate.

**Logs, Images, Videos**
> https://www.warcraftlogs.com/reports/NHFz4RgYy9nBXMwK/#fight=1&type=damage-done&start=8799&end=143672&pins=0%24Separate%24%23244F4B%24auras-gained%241%240.0.0.Any%240.0.0.Any%24true%240.0.0.Any%24false%24340431%5E2%24Separate%24%23909049%24damage%240%240.0.0.Any%24188078822.0.0.Rogue%24true%240.0.0.Any%24false%245374%5E2%24Separate%24%23a04D8A%24damage%240%240.0.0.Any%24188078822.0.0.Rogue%24true%240.0.0.Any%24false%2427576%5E2%24Separate%24%23DF5353%24damage%240%240.0.0.Any%24188078822.0.0.Rogue%24true%240.0.0.Any%24false%24340431&source=7&view=events

**Reproducible:**
> 100%

**Comment by EvanMichaels** [comment]
As a note, it used to tick over 12 seconds: https://github.com/SimCMinMax/WoW-BugTracker/issues/554

**Comment by EvanMichaels** [comment]
At also seems possible for the DoT _application_ to be Parried somehow.

![image](https://user-images.githubusercontent.com/24741480/108616810-f9741380-73de-11eb-9209-f9949cb70a19.png)

**Comment by Mikiish** [comment]
After multiple hours of trying to figure out I think Mutilated Flesh dot is reduced by armor.
I tested on the Trained Dummy at Boralus and every single times the effective/tooltip was ~0.70 so that I witnessed a 30% damage reduction from tooltip every time. The few case where the number is 74 is because of Sinful Revelation being applied.
I first tested the effective/tooltip value of another spell : Mutilate and the numbers were not matching, made me thing it was not armor related. But then I tested for other spells : Backstab / Shadowstrike / Shiv / Ambush and others and every time it shows a 30% difference between Tooltip damage and Effective damage.

Wierdly enough this highlighted another wierdness : Mutilate is dealing with armor differently than other spells. Indeed the Mutilate effective/tooltip value is always ~0.835 and funny enough sqrt(0.70)=0.835. This make me think Mutilate "bypass" a part of the armor, but that's another topic.

**Comment by Lorentz21** [comment]
@Mikiish I thought about armour double dip as well but if you try hitting dummies of different levels they'd give the same 0.7 multiplier even tho their K-value should be different and thus phys damage reduction

**Comment by EvanMichaels** [comment]
I don't think it is "double dipping" but it seems reasonable this may be affected by armor considering the periodic effect does not have a Mechanic: Bleeding attribute on it.

**Comment by Mikiish** [comment]
I tested on the Melee Target dummy in Argent Tournament Grounds (lvl 30 dummy) and the effective/tooltip value was ~0.92.

**Comment by Mystler** [comment]
I just redid the maths regarding Doomblade to cross-check and the theory checks out fine indeed. Mutilated Flesh uses an ignite-style mechanic adding every actually dealt Mutilate damage (value that appears in log and thus is mitigated by armor) to the damage buffer. The ticks then basically deal one third of the remaining buffer as physical damage. This physical damage is reduced by armor again (calculated with matching mitigation values against Level 60 and Level 42 dummies).

**Comment by Mikiish** [comment]
I'm not sure if I should create a new thread about it. 

But on the same point, Mutilated Flesh dot is increased by Sinful Revelation damage amp debuff. Basically same logic than the armor reduction : the +6% damage amp is applied twice (once on Mutialte, then on the dot).

**Comment by Mystler** [comment]
I don't think this is necessary, it's probably a related target flag issue. I refined the title to make that more clear.

**Comment by Mystler** [comment]
The armor reduction was fixed. Still double dips off target amps.

**Comment by EvanMichaels** [comment]
Marking this resolved as of latest 9.1 build testing.
