### ISSUE TITLE
Envenom Buff No Longer Pandemics

### ISSUE THREAD

**Issue by EvanMichaels** [SimCMinMax/WoW-BugTracker#813]
**Game Version:**
> 9.0.2 live Build 36753

**Description:**
> At some point in Shadowlands beta, the Envenom buff appears to have been changed to no longer pandemic, but just has a base refresh timer. This is inconsistent with past iterations of the Envenom buff and given that it was not mentioned in any patch notes, we are assuming this was in error.

**Details:**
> Overall this results in 10-15% lower than expected Envenom buff uptime with a typical rotational priority.

**Logs, Images, Videos**
> Envenom observed pandemicing as late as Nyalotha:
![image](https://user-images.githubusercontent.com/24741480/108637890-9fb12f00-745a-11eb-9088-4ec7d5ef7640.png)

> Envenom no longer pandemicing on Shadowlands live:
![image](https://user-images.githubusercontent.com/24741480/108637911-b788b300-745a-11eb-9b62-0df600d11180.png)

**Reproducible:**
> Yes

**Comment by Mystler** [comment]
Hotfixed to pandemic again on PTR.
