### ISSUE TITLE
Serrated Bone Spike direct damage not affected by Assassination Mastery

### ISSUE THREAD

**Issue by Mystler** [SimCMinMax/WoW-BugTracker#824]
**Game Version:**
> 9.0.5 PTR Build 37774

**Description:**
Bone Spike was silently removed from the direct damage effect of Potent Assassin, which now only affects SBS periodic damage. This does not sound in line with the generic line in the patch notes.

**Comment by ZeraTheRedRogue** [comment]
While testing on build 37844, SBS initial hit damage seems to once again be buffed by Potent Assassin mastery. Using identical gear and non-critical hits, an Assassination SBS hit was 2634 and an Outlaw SBS hit was 1983. The Tooltip also shows this damage increase.

**Comment by Mystler** [comment]
Yeah, it's fixed in spell data too now. Must have missed it in the diff. Thanks!
