### ISSUE TITLE
Serrated Bone Spike tooltip randomly reverts to 9.0.2 version

### ISSUE THREAD

**Issue by ZeraTheRedRogue** [SimCMinMax/WoW-BugTracker#828]
**Game Version:**
> 9.0.5 PTR Build 37844

**Description:**
> When logging in and out of the PTR, the Serrated Bone Spike tooltip will occasionally revert to the 9.0.2 version, though the damage and effects appear to be working as the intended 9.0.5 PTR build would suggest. Uncertain if this is causing any underlying issues or not.

**Reproducible:**
> Not easily replicated, as it seems random to when you log in/log out of the PTR client.

**Comment by Mystler** [comment]
I'm going ahead and closing this again as it's not really a Rogue/SBS bug but a client-side hotfix caching issue of some sort that should not be an issue on Live now anyway.
