### ISSUE TITLE
Heal estimator is very off

### ISSUE THREAD

**Issue by Zarania** [SimCMinMax/WoW-BugTracker#83]
**Game Version:**
8.0.1 Alpha Build 25976

**Description:**
The healing estimator shows the healing a lot larger than happens

![image](https://user-images.githubusercontent.com/8323677/36059008-a6fbc21a-0dfc-11e8-9441-4b27f1106dd0.png)

![image](https://user-images.githubusercontent.com/8323677/36059011-b19b0c58-0dfc-11e8-89ab-38e5496502aa.png)

**Reproducible:**
Yes

**Howto:**
Cast healing surge

**Comment by Aethys256** [comment]
Duplicate of https://github.com/SimCMinMax/WoW-BugTracker/issues/20
