### ISSUE TITLE
Shadow Blades does not increase CP generation of Serrated Bone Spike

### ISSUE THREAD

**Issue by ZeraTheRedRogue** [SimCMinMax/WoW-BugTracker#835]
**Game Version:**
> 9.0.5 live Build 38134

**Description:**
> Shadow Blades does not increase combo point generation of Serrated Bone Spike by 1, despite being a combo point generator. It also does not cause Shadow Blades damage. This is inconsistent with the other two covenant abilities that generate combo points.

**Details:**
> Despite being a combo point generator, Shadow Blades does not affect Serrated Bone Spike. It does work on both Sepsis and Echoing Reprimand, however, both dealing the extra shadow damage and generating 1 additional combo point. (For some reason, the Sepsis tooltip doesn't update to show 2 CP will be generated, but it does generate 2. Echoing Reprimand updates correctly.)

**Reproducible:**
> Yes

**Howto:**
> Cast Shadow blades, Cast Serrated Bone Spike on a single target repeatedly. Only 2 CP will be generated repeatedly.

**Comment by EvanMichaels** [comment]
This should be fixed now.
