### ISSUE TITLE
Lua error. Rogue combopoint out of index

### ISSUE THREAD

**Issue by RosvallM** [SimCMinMax/WoW-BugTracker#84]
**Game Version:**
> 8.0.1 Alpha Build 25976

**Description:**
> Due to Soul of the Shadowblade bug (described here: https://github.com/SimCMinMax/WoW-BugTracker/issues/85) you're able to select both Anticipation as well as Deeper Stratagem. This leads to a total of 11 combo points which is not supported and throws a LUA error.

**Details:**
> https://i.imgur.com/xaVtC3y.jpg
https://i.imgur.com/6D59Hmq.jpg

**Reproducible:**
> Examples: Yes

**Howto:**
> Equip "Soul of the Shadowblade" (item=150936) and Select the level 45 talent Anticipation.

**Comment by Mystler** [comment]
Anticipation is gone. Closing this issue.
