### ISSUE TITLE
Harmonic Echo does not trigger on the 4th stack of Radiant Spark Vulnerability

### ISSUE THREAD

**Issue by Dorovon** [SimCMinMax/WoW-BugTracker#841]
**Game Version:**
> 9.1.0 PTR Build 38312

**Description:**
> When using the Harmonic Echo legendary, the bonus damage does not trigger from damage that consumes the 4th stack of Radiant Spark Vulnerability.

**Logs, Images, Videos**
> ![image](https://user-images.githubusercontent.com/50294688/115233866-a7492900-a0d5-11eb-8881-aded52df4d5e.png)

**Reproducible:**
> yes

**Howto:**
> Equip the Harmonic Echo legendary, cast Radiant Spark on a target, and cast spells into the target until the 4th stack of Radiant Spark Vulnerability is removed. Harmonic Echo will only be triggered three times, as it fails to trigger on the last spell.

**Comment by vituscze** [comment]
Fixed according to hotfix notes.
