### ISSUE TITLE
Radiant Spark BUG

### ISSUE THREAD

**Issue by Theamara81** [SimCMinMax/WoW-BugTracker#843]
**Game Version:**
> 9.1.0 PTR Build 38312

**Description:**
> When more kyrian mages use RS on the same target, the second Radiant Spark resets the vulnerability debuff of the first one. Due to this bug, it is not advisable to have more than one kyrian mage in a group. 

**Reproducible:**
> yes

**Howto:**
> Obvious

**Comment by Dorovon** [comment]
Duplicate of https://github.com/SimCMinMax/WoW-BugTracker/issues/840
