### ISSUE TITLE
Harmonic Echo ignores damage taken multipliers

### ISSUE THREAD

**Issue by vituscze** [SimCMinMax/WoW-BugTracker#844]
**Game Version:**
> 9.1.0 PTR Build 38312

**Description:**
> The damage done by the AoE component of Harmonic Echo ignores any damage taken multipliers present on the target. In particular, if the target with Radiant Spark debuff does not have any damage reduction and a nearby target does, this bug allows the legendary to bypass the damage reduction entirely.

**Reproducible:**
> yes

**Howto:**
> Find two targets, one of which has a large damage reduction. Cast Radiant Spark on the normal target and trigger Harmonic Echo. Observe that the secondary target (with the damage reduction) takes full damage.

**Comment by Dorovon** [comment]
Fixed in PTR build 9.1.0.38950.
