### ISSUE TITLE
Poison bomb procs on target rather than mob ability was cast on

### ISSUE THREAD

**Issue by Kiwifruity** [SimCMinMax/WoW-BugTracker#86]
**Game Version:**
> 8.0.1 Alpha Build 25976

**Description:**
> Poison bomb procs under the target mob, rather than the mob that the player cast a finisher on. This occurs no matter how far away the targeted mob is. If the player is targeting a friendly target and casting on a focus target, poison bomb will not proc at all.

**Details:**
> https://i.imgur.com/2ygarBO.gifv

**Reproducible:**
> 100%

**Howto:**
> Set up some focus or mouseover macros for some abilities, focus mob A, target mob B. Use macros to cast on mob A, observe poison bomb proccing on mob B.

**Comment by Mystler** [comment]
Still exists

**Comment by Mystler** [comment]
Nevermind my previous comment, this was fixed alright.
