### ISSUE TITLE
Mastery: Main Gauche does not proc from most main-hand abilities

### ISSUE THREAD

**Issue by soloxcx** [SimCMinMax/WoW-BugTracker#890]
**Game Version:**
> 9.2.0 Live Build 42979

**Description:**
> The tooltip on Main Gauche implies any main-hand attack can be its source, but this is wrong. It can only proc from Sinister Strike (and its second hit), main-hand auto attacks, main-hand Killing Spree hits, and the main-hand hit from the Triple Threat conduit. 

**Details:**
> I'm not sure if this should just be labeled a tooltip error or if this is an actual bug where more sources of Main Gauche is the intended behavior.

**Logs, Images, Videos**
> This has been well established for years, though @EvanMichaels might have a log that specifically proves that Triple Threat is a source. 

**Reproducible:**
> Always.

**Howto:**
> Be Outlaw and unlock Mastery: Main Gauche.

**Comment by EvanMichaels** [comment]
Current MG procs are: Melee white damage MH swings, Killing Spree MH hits, and Sinister Strike (all hits, including Triple Threat.)

As of last testing, MH abilities (abilities flagged as "Requires Main-Hand Weapon (106)") that do not proc MG are:

Dispatch, Ghostly Strike, MH Covenant abilities (Echoing Reprimand, Sepsis, SBS) Ambush, Kidney Shot, Blade Flurry instant AoE damage, Blade Rush.

**Comment by EvanMichaels** [comment]
Triple Threat is shown as proc'ing here:
![image](https://user-images.githubusercontent.com/24741480/161896342-33744faa-b26f-411a-a4b2-f71bef832596.png)

**Comment by soloxcx** [comment]
they actually fixed this after 5 years
