### ISSUE TITLE
Venomous Wounds tooltip incorrect energy refund listed when Venom Rush talent selected

### ISSUE THREAD

**Issue by Kiwifruity** [SimCMinMax/WoW-BugTracker#92]
**Game Version:**
> 8.0.1 Alpha Build 25976

**Description:**
> Venomous Wounds gives 7 energy back when bleed damage is dealt to a poisoned target. In legion, the venom rush talent increased the energy back to 10. In BFA Venom rush has changed to a 5 energy refund attached to mutilate, however when you select the talent it increases the Venomous Wounds tooltip from 7 energy to 12 energy. It does not actually increase the energy gained from Venomous wounds to 12, its just a tooltip bug.

This bug also effects the tooltip for Venomous Vim 

**Reproducible:**
> 100%

**Howto:**
> Take venom rush talent. Observe Venomous Wounds tooltip saying 12 energy refund.

**Comment by Mystler** [comment]
Fixed in 8.0.1.26095.
