### ISSUE TITLE
Mind Sear unusable after multiple Mind Devourer procs under 50 Insanity

### ISSUE THREAD

**Issue by Twintop** [SimCMinMax/WoW-BugTracker#951]
**Game Version:**
10.0.2 beta Build 45779

**Description:**
As of this beta build, a proc of the Shadow Priest talent Mind Devourer also allows for Mind Sear to be cast+channelled at 0 Insanity cost. When you have a Mind Devourer proc and get another proc (refreshing the duration) **and** are under 50 Insanity total, Mind Sear is no longer able to be used.

**Logs, Images, Videos**
Mind Sear is in the `=` slot / end of bottom action bar in both screenshots.

Example screenshot of Mind Sear not being usable under these conditions (post second proc):
![image](https://user-images.githubusercontent.com/1485707/192930271-f6ae15dc-dd46-4de8-9a5e-22f9da898f4d.png)

Vs. normal usage with only 1 proc:
![image](https://user-images.githubusercontent.com/1485707/192930358-c6eee6ce-8fee-41a2-a6bc-1b02b0605404.png)

**Reproducible:**
Yes

**Howto:**
1. Cast Mind Blast until you get a Mind Devourer proc.
2. Keep casting Mind Blast to get a second Mind Devourer proc that refreshes the duration of the buff *while* being under 50 Insanity.

Having many Shadow Word: Pains out, having the Shadowy Insight talent, and casting Mind Blast only when at low Insanity makes it easier to get these conditions met.

**Comment by seanpeters86** [comment]
was not able to reproduce on 46047
