### ISSUE TITLE
Gathering Shadows (Shadow 2pc) only buffs n-1 ticks of Mind Sear

### ISSUE THREAD

**Issue by jaervified** [SimCMinMax/WoW-BugTracker#966]
**Game Version:**
10.0.2 live Build 47213

**Description:**
Gathering Shadows (Shadow 2pc) is only buffing n-1 ticks of Mind Sear because the buff drops right as the last tick happens. This means based on the number of ticks you should get, you are getting 1 less buffed ticks worth of damage:

| Total Ticks | Buffed Ticks |
| --- | --- |
| 4 | 3 |
| 3 | 2 |
| 2 | 1 |

**Logs, Images, Videos**

![](https://i.imgur.com/LUSKwlQ.png)

![](https://i.imgur.com/fHQAYK4.png)

![](https://i.imgur.com/rYTzjDx.png)

**Reproducible:**
> Examples: yes/rarely

**Howto:**
1. Get stacks of Gathering Shadows
2. Channel a Mind Sear
3. Last tick does less damage than the previous 3

**Comment by seanpeters86** [comment]
![gathering_shadows_bug](https://user-images.githubusercontent.com/10604059/199581571-9e617a08-53bd-4f56-b1c7-e770d7d99a3c.png)

still happening on beta

**Comment by seanpeters86** [comment]
still happening on live servers
