### ISSUE TITLE
Serrated Shots does not work with certain bleed effects.

### ISSUE THREAD

**Issue by Tralololo** [SimCMinMax/WoW-BugTracker#968]
**Game Version:**
> 10.0.2 beta Build 46092

**Description:**
> The Serrated Shots talent does not benefit the bleeds: Bloodseeker (Survival Hunter Talent), Embrace of Kimbul (Zandalari Racial). Hit the Mark (Marksman Hunter 2-set for Dragonflight season 1)

**Logs, Images, Videos**

> N/A

**Reproducible:**
> Yes

**Howto:**
> Use the listed abilities, note their ticking damage in the combat log, then unselect Serrated Shots in the talent tree. Use the listed abilities again. Note their damage in combat log again and note the lack of difference.

**Comment by Pewtro** [comment]
No longer relevant in The War Within as Serrated Shots is gone.
