### ISSUE TITLE
Serpent Sting tooltip does not update with Serrated Shots.

### ISSUE THREAD

**Issue by Tralololo** [SimCMinMax/WoW-BugTracker#969]
**Game Version:**
> 10.0.2 beta Build 46092

**Description:**
> Tooltip of Serpent Sting does not update its damage value when selecting the talent "Serrated Shots". Combat logs show that the damage value does go up in reality, but the tooltip does not update properly.

**Logs, Images, Videos**
> N/A

**Reproducible:**
> Yes

**Howto:**
> Replication: Select the Serpent Sting talent, take note of its tooltip values. Then select the talent Serrated Shots. Notice that the value on Serpent Stings tooltip doesn’t increase when Serrated Shots is Selected.

**Comment by Pewtro** [comment]
No longer relevant in The War Within as Serpent Sting as a stand-alone spell is gone.
