### ISSUE TITLE
Soul of the [...] legendary ring enables talents based on position

### ISSUE THREAD

**Issue by Bloodmallet** [SimCMinMax/WoW-BugTracker#97]
**Game Version:**
> 8.0.1 Alpha Build 25976

**Description:**
> The legendary class rings "Soul of the [...]" enable talents based on the live position of the talents they should yield. If a spec has a different talent there now, this is enabled.

**Details:**
> Reports about this are already in #72 ,  #96 and #85 . Based on these reports it's very likely that any of these talent repositions or exchanges allow these legendary rings to enable unintented talents.

**Reproducible:**
> Yes

**Howto:**
> Equip legendary ring "Soul of the [...]" and get a talent activated based on the live position of the intended talent.

**Comment by fuu1** [comment]
seems to be fixed in the lat build:
![image](https://user-images.githubusercontent.com/25006752/38414431-bec4d644-398e-11e8-8906-ed7c4a76f7f7.png)
didn't test on DK/Mage

**Comment by vituscze** [comment]
Fixed for mages.

**Comment by Melekus** [comment]
Fixed for DK as well.
