### ISSUE TITLE
GCD of Spearhead is not Hasted.

### ISSUE THREAD

**Issue by Tralololo** [SimCMinMax/WoW-BugTracker#979]
**Game Version:**
> 10.0.2 beta Build 46092

**Description:**
> Global Cooldown of Speadhead is not Hasted

**Logs, Images, Videos**
> N/A

**Reproducible:**
> Yes

**Howto:**
> Use Spearhead. Measure the time it takes for the Global Cooldown to recharge. Add or remove ring with haste on it. Use Spearhead again and measure the time. Notice that the duration doesn’t change.

**Comment by Pewtro** [comment]
This has been fixed
