### ISSUE TITLE
Deadly Duo Spearhead extension value will randomly be set to 1 second after some usage.

### ISSUE THREAD

**Issue by Tralololo** [SimCMinMax/WoW-BugTracker#980]
**Game Version:**
> 10.0.2 beta Build 46092

**Description:**
> With the Deadly Duo talent Selected, Kill Command resets are supposed to extend the duration of Spearhead by either 0.8 seconds or 1.5 seconds depending on points spent on the talent. Randomly after using this talent for some time, this value will be set to 1.0 seconds regardless of the points you had spent initially. This includes the tooltip value.

**Logs, Images, Videos**
> N/A

**Reproducible:**
> No

**Howto:**
> N/A

**Comment by Pewtro** [comment]
This has been presumed fixed, as it has gone unnoticed for some time.
