### ISSUE TITLE
Sentinel Owl duration drifts towards 5 seconds outside of combat

### ISSUE THREAD

**Issue by Tralololo** [SimCMinMax/WoW-BugTracker#981]
**Game Version:**
> 10.0.2 beta Build 46092

**Description:**
> Sentinel Owl is supposed to gain duration as you are spending focus, and the currently "stored" duration will be shown on the spell icon. However, when outside of combat, the "stored" duration will gradually grow towards 5 seconds regardless of whether you are spending focus or not. 

**Logs, Images, Videos**
> N/A

**Reproducible:**
> Yes

**Howto:**
> Select the Sentinel Owl talent.Wait for a short duration. Observe the duration value slowly ticking up on the Sentinel Owl icon towards 5 seconds and then stopping. Cast the spell and notice you have 5 seconds of Sentinel Owl.

**Comment by Pewtro** [comment]
No longer relevant in The War Within as Sentinel Owl is gone.
