### ISSUE TITLE
Ice Floes doesn't function properly with some spells

### ISSUE THREAD

**Issue by vituscze** [SimCMinMax/WoW-BugTracker#990]
**Game Version:**
> 10.0.2 beta Build 45746

**Description:**
> Ice Floes does not work with Arcane Surge at all. Arcane Blast and Shifting Power benefit but do not consume Ice Floes. Arcane Echo and Flurry (cast without Brain Freeze) consume Ice Floes, despite being instants.

**Reproducible:**
> yes

**Howto:**
> cast Ice Floes and cast one of the previously mentioned spells

**Comment by vituscze** [comment]
Arcane Echo and Flurry still consume Ice Floes, the other spells were fixed.

**Comment by ArcanePorom** [comment]
Arcane Blast with Presence of Mind and Arcane Missiles with Clearcasting and Slipstream consume Ice Floes.

**Comment by ArcanePorom** [comment]
Ice floes now works normally while Arcane Echo is active. Additionally, Flurry does not consume when you have a Brain Freeze proc.
