### ISSUE TITLE
Cascading Power doesn't trigger Clearcasting correctly

### ISSUE THREAD

**Issue by vituscze** [SimCMinMax/WoW-BugTracker#994]
**Game Version:**
> 10.0.2 beta Build 45746

**Description:**
> After using Mana Gem with Cascading Power, the next Arcane Missiles doesn’t channel faster and doesn’t fire additional missiles with Amplification.

**Reproducible:**
> yes

**Howto:**
> talent into Amplification, use Mana Gem, cast Arcane Missiles, it only fires 5 missiles

**Comment by ArcanePorom** [comment]
To add to this, the Clearcasting you get also do not benefit from Slipstream, however if you already have a Clearcasting buff this bug does not occur at all.

**Comment by ArcanePorom** [comment]
This is fixed on 10.2 PTR, will close this ticket after change is verified on live.
