### ISSUE TITLE
Concentration is not consumed by Arcane Explosion

### ISSUE THREAD

**Issue by vituscze** [SimCMinMax/WoW-BugTracker#995]
**Game Version:**
> 10.0.2 beta Build 45746

**Description:**
> when both Concentration and Clearcasting are active, casting Arcane Explosion doesn't consume any of them, despite benefiting from Clearcasting

**Reproducible:**
> yes

**Howto:**
> proc both Clearcasting and Concentration, cast Arcane Explosion

**Comment by ArcanePorom** [comment]
When this happens, Arcane Explosion does consume the hidden auras that Clearcasting applies (Amplification, Slipstream); however, using a Arcane Missiles will consume the Concentration buff with no Clearcasting benefits and doing so refreshes any Clearcasting procs you have to work properly again.

**Comment by ArcanePorom** [comment]
When this happens, Arcane Explosion cost 0 mana for the duration of Concentration.

**Comment by ArcanePorom** [comment]
Worth adding that that as of 10.1.5 the Arcane Explosion does not proc Concentrated Power while this bug is active.

**Comment by ArcanePorom** [comment]
Fixed in TWW 11.0 pre-patch.
